unbind r
bind r source-file ~/.tmux.conf

set -g mouse on

set-option -g status-position top
set -g base-index 1
set -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
# set -g @plugin 'christoomey/vim-tmux-navigator'

# Tokyo Night theme settings
set -g @theme_transparent_status_bar 'true'
set -g @theme_disable_plugins 1

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left " "

# Easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

# Vim-Tmux-Navigator settings
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
