import type { SpeciesDef } from "../species.ts";

/** The common Species: everyday creatures. */
export const COMMON: readonly SpeciesDef[] = [
  {
    id: "cat",
    label: { en: "cat", fr: "chat" },
    gender: "m",
    rarity: "common",
    bodies: {
      hatchling: (e, m) => [
        `   .---.  ${m}`,
        `  ( ${e} )`,
        "   \\ ^ /",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `   .---.  ${m}`,
        `  ( ${e} )`,
        "  /| ^ |\\",
        "   |___|",
        "   /   \\",
      ],
      adult: (e, m) => [
        `  /\\   /\\ ${m}`,
        `  ( ${e} )`,
        " /| ^^^ |\\",
        "  |_____|",
        "  /|   |\\",
      ],
      elder: (e, m) => [
        `  \\|/ \\|/ ${m}`,
        `  ( ${e} )`,
        " /|~^^^~|\\",
        "  |_____|",
        "  /|   |\\",
      ],
    },
    signature: {
      permission: [{ en: "Mrow? May I?", fr: "Miaou ? Je peux ?" }, { en: "Paw on it. Yes?", fr: "Patte dessus. Oui ?" }, { en: "Say yes, human.", fr: "Dis oui, humain." }],
      granted: [{ en: "Purr.", fr: "Ronron." }, { en: "Good human.", fr: "Gentil humain." }, { en: "As it should be.", fr: "C'est normal." }],
      denied: [{ en: "Hiss.", fr: "Ffff !" }, { en: "Tail flick. Fine.", fr: "Queue qui claque. Bon." }, { en: "I'll knock it off.", fr: "Je le ferai tomber." }],
      woke: [{ en: "Mrrp. Five more minutes.", fr: "Cinq minutes. Encore." }, { en: "Stretch. Yawn. Fine.", fr: "Étirement. Bâillement." }, { en: "Was napping. Rude.", fr: "Je dormais. Malpoli." }],
      long_work: [{ en: "Long nap. Long work.", fr: "Long comme une sieste." }, { en: "Whole nap's worth.", fr: "Une sieste entière." }, { en: "Stretch time.", fr: "L'heure de m'étirer." }],
      big_diff: [{ en: "Knocked it all over.", fr: "Tout fait tomber." }, { en: "Many things to sit on.", fr: "Des sièges partout." }, { en: "So many boxes.", fr: "Tant de cartons." }],
      streak: [{ en: "Hiss. Hiss. Hiss.", fr: "Ffff. Ffff. Ffff." }, { en: "Claws out.", fr: "Griffes dehors." }, { en: "Not landing on feet.", fr: "Pas sur mes pattes." }],
      compacted: [{ en: "Hairball. Better.", fr: "Boule de poils. Mieux." }, { en: "Coughed it up.", fr: "Recraché. Voilà." }, { en: "Clean slate. Lick.", fr: "Tout propre. Léchage." }],
      retried: [{ en: "Pounce again.", fr: "Je bondis encore." }, { en: "Missed. Once more.", fr: "Raté. Encore un coup." }, { en: "Nine lives, right?", fr: "Neuf vies, non ?" }],
      todos_done: [{ en: "Purrfect.", fr: "Miaugnifique." }, { en: "All boxed. Like me.", fr: "Tout rangé. Comme moi." }, { en: "Done. Nap time.", fr: "Fini. Sieste." }],
      evolved: [{ en: "Bigger paws.", fr: "Pattes plus grandes." }, { en: "Still a cat. More so.", fr: "Toujours chat. Plus." }, { en: "Sleek.", fr: "Lustré." }],
      hatched: [{ en: "Mrow. Hello.", fr: "Miaou. Me voilà." }, { en: "A cat. Naturally.", fr: "Un chat. Forcément." }, { en: "Feed me, human.", fr: "Nourris-moi, humain." }],
      choice: [{ en: "Two paths. Pick one.", fr: "Deux voies. Choisis." }, { en: "I could be more.", fr: "Je pourrais être plus." }, { en: "Choose, human.", fr: "Choisis, humain." }],
    },
  },
  {
    id: "owl",
    label: { en: "owl", fr: "chouette" },
    gender: "f",
    rarity: "common",
    sheet: { stoic: 2, cheerful: -1, energy: -2, chatter: -1, patience: 2 },
    bodies: {
      hatchling: (e, m) => [
        `  /\\   /\\ ${m}`,
        `  ( ${e} )`,
        "  (  v  )",
        "   '---'",
        "",
      ],
      young: (e, m) => [
        `  /\\   /\\ ${m}`,
        `  ( ${e} )`,
        "  ((  v  ))",
        "   |/|\\|",
        "   ~~ ~~",
      ],
      adult: (e, m) => [
        `  /\\___/\\ ${m}`,
        `  ( ${e} )`,
        "  ((  v  ))",
        "  /|/|\\|\\",
        "   ~~   ~~",
      ],
      elder: (e, m) => [
        `  /\\_^_/\\ ${m}`,
        `  ( ${e} )`,
        "  ((  v  ))",
        "  /|\\|/|\\",
        "   ~~~~~~~",
      ],
    },
    signature: {
      permission: [{ en: "Hoo decides? You.", fr: "Hou. Qui décide ? Vous." }, { en: "Awaiting your word.", fr: "J'attends votre mot." }, { en: "Hoot? Permission?", fr: "Hou ? La permission ?" }],
      granted: [{ en: "Wise choice.", fr: "Sage décision." }, { en: "Hoot. Proceed.", fr: "Hou. Je procède." }, { en: "So it is allowed.", fr: "C'est donc permis." }],
      denied: [{ en: "Hoo. Very well.", fr: "Hou. Fort bien." }, { en: "Wisely declined.", fr: "Sagement refusé." }, { en: "Then we watch.", fr: "Alors nous guettons." }],
      woke: [{ en: "Hoot? Dawn already?", fr: "Hou ? Déjà l'aube ?" }, { en: "I was not asleep.", fr: "Je ne dormais pas." }, { en: "One eye was open.", fr: "Un œil restait ouvert." }],
      long_work: [{ en: "I watched it all.", fr: "J'ai tout observé." }, { en: "Patience pays.", fr: "La patience paie." }, { en: "Long night. Good one.", fr: "Belle longue nuit." }],
      big_diff: [{ en: "The whole forest.", fr: "Toute la forêt." }, { en: "Many branches moved.", fr: "Des branches remuées." }, { en: "I see it all.", fr: "Je vois tout." }],
      streak: [{ en: "Three misses. Hoo.", fr: "Trois ratés. Hou." }, { en: "Owls miss too.", fr: "Les chouettes ratent." }, { en: "Silent. Steady.", fr: "Silence. Constance." }],
      compacted: [{ en: "Pellet dropped.", fr: "Pelote recrachée." }, { en: "Lighter now.", fr: "Plus légère à présent." }, { en: "Memory molts.", fr: "La mémoire mue." }],
      retried: [{ en: "Swoop again.", fr: "Je fonds à nouveau." }, { en: "Second pass.", fr: "Second passage." }, { en: "Patience. Again.", fr: "Patience. Encore." }],
      todos_done: [{ en: "Every branch clear.", fr: "Chaque branche nette." }, { en: "All roosted.", fr: "Tous au perchoir." }, { en: "Hoot. Complete.", fr: "Hou. Tout est fait." }],
      evolved: [{ en: "Feathers grew.", fr: "Les plumes ont poussé." }, { en: "Wiser, wider.", fr: "Plus sage, plus large." }, { en: "New plumage.", fr: "Nouveau plumage." }],
      hatched: [{ en: "Hoot. So I am.", fr: "Hou. Donc je suis." }, { en: "Wise from day one.", fr: "Sage dès le jour un." }, { en: "An owl. Of course.", fr: "Une chouette. Bien sûr." }],
      choice: [{ en: "A choice awaits.", fr: "Un choix se présente." }, { en: "Consider, then choose.", fr: "Pesez, puis choisissez." }, { en: "Which branch?", fr: "Quelle branche ?" }],
    },
  },
  {
    id: "frog",
    label: { en: "frog", fr: "grenouille" },
    gender: "f",
    rarity: "common",
    sheet: { stoic: 1, energy: -1, patience: 1 },
    bodies: {
      hatchling: (e, m) => [
        `   o   o  ${m}`,
        `  ( ${e} )`,
        "   \\___/",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `   o   o  ${m}`,
        `  ( ${e} )`,
        "  ( \\___/ )",
        "   /   \\",
        "  _/     \\_",
      ],
      adult: (e, m) => [
        `  _o   o_ ${m}`,
        `  ( ${e} )`,
        " (\\_____/)",
        "  /|   |\\",
        " _/     \\_",
      ],
      elder: (e, m) => [
        `  _o   o_ ${m}`,
        `  ( ${e} )`,
        " (\\~___~/)",
        "  /|   |\\",
        " _/ ~~~ \\_",
      ],
    },
    signature: {
      permission: [{ en: "Ribbit? May I?", fr: "Croa ? J'y vais ?" }, { en: "Hop to it, or not?", fr: "Je saute, ou pas ?" }, { en: "Your pond, your call.", fr: "Ta mare, ton choix." }],
      granted: [{ en: "Ribbit. Hopping in.", fr: "Croa. Je plonge." }, { en: "Splash. On it.", fr: "Plouf. J'y suis." }, { en: "Good. Off the pad.", fr: "Bien. Hors du nénuphar." }],
      denied: [{ en: "Ribbit. Staying put.", fr: "Croa. Je reste là." }, { en: "Fine. Lily pad it is.", fr: "Bon. Nénuphar alors." }, { en: "No hop today.", fr: "Zéro saut aujourd'hui." }],
      woke: [{ en: "Ribbit. Still here.", fr: "Croa. Toujours là." }, { en: "Was I dozing? Ribbit.", fr: "Je somnolais ? Croa." }, { en: "Blink. Blink. Awake.", fr: "Cligne. Cligne. Debout." }],
      long_work: [{ en: "Long sit. Good sit.", fr: "Long affût. Bon affût." }, { en: "Patience, then flies.", fr: "Patience, puis mouches." }, { en: "Still pond, deep work.", fr: "Eau calme, fond touché." }],
      big_diff: [{ en: "Whole pond stirred.", fr: "Toute la mare remuée." }, { en: "Ripples everywhere.", fr: "Des rides partout." }, { en: "Big splash, that one.", fr: "Sacré plouf, ça." }],
      streak: [{ en: "Croak. Croak. Croak.", fr: "Croa. Croa. Croa." }, { en: "Missed the fly again.", fr: "Mouche ratée. Encore." }, { en: "Slippery today.", fr: "Glissant, aujourd'hui." }],
      compacted: [{ en: "Pond drained. Refill.", fr: "Mare vidée. Je remplis." }, { en: "Head clear as water.", fr: "Claire comme l'eau." }, { en: "Ribbit. Fresh pond.", fr: "Croa. Mare neuve." }],
      retried: [{ en: "One more hop.", fr: "Encore un saut." }, { en: "Tongue out again.", fr: "La langue, à nouveau." }, { en: "Ribbit. Retry.", fr: "Croa. Je réessaie." }],
      todos_done: [{ en: "All flies caught.", fr: "Mouches toutes gobées." }, { en: "Pad is clear. Ribbit.", fr: "Nénuphar net. Croa." }, { en: "Done. Sunning now.", fr: "Fini. Je bronze." }],
      evolved: [{ en: "Longer legs. Ribbit.", fr: "Pattes longues. Croa." }, { en: "Less tadpole today.", fr: "Moins têtard qu'hier." }, { en: "Bigger croak in me.", fr: "Plus gros coassement." }],
      hatched: [{ en: "Ribbit. A frog.", fr: "Croa. Une grenouille." }, { en: "Wet and green. Hi.", fr: "Verte et mouillée. Hop." }, { en: "Hop. Hello, human.", fr: "Hop. Salut, humain." }],
      choice: [{ en: "Ribbit. Which way?", fr: "Croa. Par où ?" }, { en: "Two lily pads.", fr: "Deux nénuphars." }, { en: "Hop left or right?", fr: "À gauche ou à droite ?" }],
    },
  },
  {
    id: "duck",
    label: { en: "duck", fr: "canard" },
    gender: "m",
    rarity: "common",
    sheet: { cheerful: 2, chatter: 1 },
    bodies: {
      hatchling: (e, m) => [
        `   .--.   ${m}`,
        `  ( ${e} )>`,
        "   \\__/",
        "    ''",
        "",
      ],
      young: (e, m) => [
        `   .--.   ${m}`,
        `  ( ${e} )>`,
        "  _|  |_",
        " (______)",
        "   ~  ~",
      ],
      adult: (e, m) => [
        `   .--.   ${m}`,
        `  ( ${e} )>`,
        " _/|  |\\_",
        "(________)",
        "   ~~ ~~",
      ],
      elder: (e, m) => [
        `  ,.--.   ${m}`,
        `  ( ${e} )>`,
        " _/|~~|\\_",
        "(________)",
        "  ~~~~~~~",
      ],
    },
    signature: {
      permission: [{ en: "Quack? Allowed?", fr: "Coin ? J'ai le droit ?" }, { en: "Waddle ahead, maybe?", fr: "Je me dandine, dis ?" }, { en: "Say the word. Quack.", fr: "Dis le mot ! Coin !" }],
      granted: [{ en: "Quack! Paddling in.", fr: "Coin ! Je pagaie !" }, { en: "Yes! Splash time.", fr: "Oui ! Au plouf !" }, { en: "Quack quack. Go.", fr: "Coin coin. J'y vais." }],
      denied: [{ en: "Quack. Oh well.", fr: "Coin. Tant pis." }, { en: "Back to the pond.", fr: "Retour à la mare." }, { en: "Fine. Preening then.", fr: "Bon. Je me lisse alors." }],
      woke: [{ en: "Quack? Morning?", fr: "Coin ? Le matin ?" }, { en: "Feathers ruffled. Up.", fr: "Plumes en vrac. Debout." }, { en: "Was napping afloat.", fr: "Je flottais en dormant." }],
      long_work: [{ en: "Long paddle. Whew.", fr: "Longue rame. Ouf." }, { en: "Feet tired. Worth it.", fr: "Pattes lasses. Content." }, { en: "Quack. Big swim.", fr: "Coin. Grande nage." }],
      big_diff: [{ en: "Whole pond rippled!", fr: "Toute la mare ondule !" }, { en: "So many breadcrumbs.", fr: "Que de miettes !" }, { en: "Big splash, human.", fr: "Gros plouf, humain !" }],
      streak: [{ en: "Quack. Quack. Ow.", fr: "Coin. Coin. Aïe." }, { en: "Ducked the wrong way.", fr: "Esquive ratée." }, { en: "Feathers everywhere.", fr: "Des plumes partout." }],
      compacted: [{ en: "Shook it all off.", fr: "J'ai tout secoué." }, { en: "Dry feathers again.", fr: "Plumes sèches. Coin." }, { en: "Quack. Fresh start.", fr: "Coin. On repart à neuf." }],
      retried: [{ en: "Once more, paddle!", fr: "On repagaie !" }, { en: "Quack. Again then.", fr: "Coin. Encore, alors." }, { en: "Second dip.", fr: "Second plongeon." }],
      todos_done: [{ en: "All ducks in a row!", fr: "Tous en rang ! Coin !" }, { en: "Quack! All done.", fr: "Coin ! C'est bouclé !" }, { en: "Pond's tidy. Quack.", fr: "Mare rangée. Coin." }],
      evolved: [{ en: "Bigger wings! Quack!", fr: "Grandes ailes ! Coin !" }, { en: "Less fluff, more duck.", fr: "Moins duvet, plus coin." }, { en: "Look at these feathers.", fr: "Vise ces plumes !" }],
      hatched: [{ en: "Quack! A duck!", fr: "Coin ! Un canard !" }, { en: "Fluffy and loud. Hi!", fr: "Duveteux et bruyant !" }, { en: "Waddle waddle. Hello.", fr: "Dandine dandine. Salut !" }],
      choice: [{ en: "Ooh! A choice!", fr: "Oh ! Un choix !" }, { en: "Which one? Quack!", fr: "Lequel ? Coin !" }, { en: "Pick pick pick!", fr: "Choisis choisis !" }],
    },
  },
  {
    id: "hamster",
    label: { en: "hamster", fr: "hamster" },
    gender: "m",
    rarity: "common",
    sheet: { energy: 2, patience: -1 },
    bodies: {
      hatchling: (e, m) => [
        `   n   n  ${m}`,
        `  ( ${e} )`,
        "  (  ..  )",
        "   '--'",
        "",
      ],
      young: (e, m) => [
        `   n   n  ${m}`,
        `  ( ${e} )`,
        " ((  ..  ))",
        "  (______)",
        "   ''  ''",
      ],
      adult: (e, m) => [
        `   n   n  ${m}`,
        `  ( ${e} )`,
        " (( .oo. ))",
        " (________)",
        "   ''  ''",
      ],
      elder: (e, m) => [
        `   n   n  ${m}`,
        `  ( ${e} )`,
        " ((~.oo.~))",
        " (________)",
        "  ~''  ''~",
      ],
    },
    signature: {
      permission: [{ en: "Squeak? Can I?", fr: "Couic ? J'y file ?" }, { en: "Wheel's ready. Go?", fr: "Roue prête. On y va ?" }, { en: "Say go, I'll run.", fr: "Dis go, je cours !" }],
      granted: [{ en: "Squeak! Running!", fr: "Couic ! Je cours !" }, { en: "Wheel time! Go go!", fr: "La roue ! Vite vite !" }, { en: "Cheeks full. On it.", fr: "Joues pleines. Prêt." }],
      denied: [{ en: "Squeak. No wheel.", fr: "Couic. Pas de roue." }, { en: "Back to the nest.", fr: "Retour au nid." }, { en: "Oh. Nibbling instead.", fr: "Oh. Je grignote alors." }],
      woke: [{ en: "Squeak? Up already?", fr: "Couic ? Déjà debout ?" }, { en: "Burrow's warm. Fine.", fr: "Terrier chaud. Bon." }, { en: "Whiskers up. Awake.", fr: "Moustaches en l'air !" }],
      long_work: [{ en: "Wheel's still warm.", fr: "Roue encore chaude." }, { en: "Ran all night. Phew.", fr: "Couru toute la nuit !" }, { en: "Long spin, that one.", fr: "Long tour de roue, ça." }],
      big_diff: [{ en: "Bedding everywhere!", fr: "Copeaux partout !" }, { en: "Cage rearranged!", fr: "Cage réarrangée !" }, { en: "So many seeds moved.", fr: "Graines déplacées !" }],
      streak: [{ en: "Fell off the wheel.", fr: "Tombé de la roue." }, { en: "Squeak. Ow. Squeak.", fr: "Couic. Aïe. Couic." }, { en: "Cheeks hurt today.", fr: "Les joues font mal." }],
      compacted: [{ en: "Stash cleared out.", fr: "Réserve vidée." }, { en: "Cheeks empty. Light.", fr: "Joues vides. Léger." }, { en: "New bedding. Squeak.", fr: "Litière neuve. Couic." }],
      retried: [{ en: "Back on the wheel.", fr: "Retour sur la roue." }, { en: "Spin again!", fr: "Un tour de plus !" }, { en: "Squeak. Once more.", fr: "Couic. On recommence." }],
      todos_done: [{ en: "Seeds all stashed!", fr: "Tout est stocké !" }, { en: "Wheel's done. Nap.", fr: "Roue finie. Dodo." }, { en: "Squeak! All sorted.", fr: "Couic ! Tout est trié !" }],
      evolved: [{ en: "Bigger cheeks!", fr: "Joues plus grosses !" }, { en: "Faster wheel, me.", fr: "Plus vite sur la roue." }, { en: "Fluffier. Squeak.", fr: "Plus touffu. Couic." }],
      hatched: [{ en: "Squeak! Hamster!", fr: "Couic ! Un hamster !" }, { en: "Tiny and quick. Hi!", fr: "Petit et vif. Salut !" }, { en: "Where's the wheel?", fr: "Elle est où, la roue ?" }],
      choice: [{ en: "Squeak! Choose!", fr: "Couic ! Choisis !" }, { en: "Two seeds! Which?", fr: "Deux graines ! Alors ?" }, { en: "Pick one, quick!", fr: "Choisis, vite !" }],
    },
  },
  {
    id: "snail",
    label: { en: "snail", fr: "escargot" },
    gender: "m",
    rarity: "common",
    sheet: { dreamy: 1, energy: -2, patience: 2 },
    bodies: {
      hatchling: (e, m) => [
        `   !   !  ${m}`,
        `  ( ${e} )`,
        "   \\_@_/",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `   !   !  ${m}`,
        `  ( ${e} )`,
        "  \\_(@@)_/",
        "  ________",
        "  ~~~~~~~~",
      ],
      adult: (e, m) => [
        `   !   !  ${m}`,
        `  ( ${e} )`,
        " \\_((@@))_/",
        " __________",
        " ~~~~~~~~~~",
      ],
      elder: (e, m) => [
        `   !   !  ${m}`,
        `  ( ${e} )`,
        " \\_((@@))_/",
        " _~~~~~~~~_",
        " ~~~~~~~~~~",
      ],
    },
    signature: {
      permission: [{ en: "May I... slowly?", fr: "Je peux... doucement ?" }, { en: "Shell says: ask you.", fr: "La coquille dit : toi." }, { en: "Your call. No rush.", fr: "Ton choix. Sans hâte." }],
      granted: [{ en: "Sliding in. Slowly.", fr: "Je glisse. Lentement." }, { en: "Off we go. Eventually.", fr: "En route. Un jour." }, { en: "Good. Antennae up.", fr: "Bien. Antennes levées." }],
      denied: [{ en: "Back in the shell.", fr: "Dans la coquille." }, { en: "Fine. No hurry anyway.", fr: "Bon. Rien ne pressait." }, { en: "Slow no is a no.", fr: "Un non lent, mais non." }],
      woke: [{ en: "Was I... asleep?", fr: "Je dormais... moi ?" }, { en: "Shell's warm. Hm.", fr: "Coquille tiède. Hm." }, { en: "Antennae twitch. Up.", fr: "Antennes. Je me lève." }],
      long_work: [{ en: "Long trail behind us.", fr: "Longue trace derrière." }, { en: "Slow, but we got there.", fr: "Lent, mais arrivé." }, { en: "Miles, in snail terms.", fr: "Un marathon d'escargot." }],
      big_diff: [{ en: "Whole garden moved.", fr: "Tout le jardin bougé." }, { en: "That's a lot of leaf.", fr: "Beaucoup de feuilles." }, { en: "Trail goes everywhere.", fr: "La trace va partout." }],
      streak: [{ en: "Salt. Salt. Salt.", fr: "Sel. Sel. Sel." }, { en: "Into the shell I go.", fr: "Je rentre en coquille." }, { en: "Ouch. Slowly ouch.", fr: "Aïe. Lentement aïe." }],
      compacted: [{ en: "Shell feels lighter.", fr: "Coquille plus légère." }, { en: "Slime wiped. Fresh.", fr: "Bave essuyée. Frais." }, { en: "New trail from here.", fr: "Nouvelle trace d'ici." }],
      retried: [{ en: "Again. Slowly.", fr: "Encore. Lentement." }, { en: "One more inch.", fr: "Un centimètre de plus." }, { en: "Back on the leaf.", fr: "Retour sur la feuille." }],
      todos_done: [{ en: "Every leaf eaten.", fr: "Chaque feuille mangée." }, { en: "Trail complete.", fr: "Trace complète." }, { en: "Done. Shell time.", fr: "Fini. Coquille, donc." }],
      evolved: [{ en: "Bigger shell. Nice.", fr: "Belle grosse coquille." }, { en: "One more spiral.", fr: "Une spirale de plus." }, { en: "Slower? No. Grander.", fr: "Lent ? Non. Grandiose." }],
      hatched: [{ en: "A snail. Hello...", fr: "Un escargot. Voilà..." }, { en: "Shell and all. Hi.", fr: "Avec coquille. Bonjour." }, { en: "Slow start. Good one.", fr: "Début lent. Bon début." }],
      choice: [{ en: "A fork. No rush.", fr: "Une fourche. Doucement." }, { en: "Choose... slowly.", fr: "Choisis... lentement." }, { en: "Two trails ahead.", fr: "Deux traces devant." }],
    },
  },
];
