import type { SpeciesDef } from "../species.ts";

/** The common Species: everyday creatures. */
export const COMMON: readonly SpeciesDef[] = [
  {
    id: "cat",
    label: "cat",
    rarity: "common",
    bodies: {
      hatchling: (e, m) => [
        `   .---.  ${m}`,
        `  ( ${e} )`,
        "   \\ ^ /",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `   .---.  ${m}`,
        `  ( ${e} )`,
        "  /| ^ |\\",
        "   |___|",
        "   /   \\",
      ],
      adult: (e, m) => [
        `  /\\   /\\ ${m}`,
        `  ( ${e} )`,
        " /| ^^^ |\\",
        "  |_____|",
        "  /|   |\\",
      ],
      elder: (e, m) => [
        `  \\|/ \\|/ ${m}`,
        `  ( ${e} )`,
        " /|~^^^~|\\",
        "  |_____|",
        "  /|   |\\",
      ],
    },
    signature: {
      permission: ["Mrow? May I?", "Paw on it. Yes?", "Say yes, human."],
      granted: ["Purr.", "Good human.", "As it should be."],
      denied: ["Hiss.", "Tail flick. Fine.", "I'll knock it off."],
      woke: ["Mrrp. Five more minutes.", "Stretch. Yawn. Fine.", "Was napping. Rude."],
      long_work: ["Long nap. Long work.", "Whole nap's worth.", "Stretch time."],
      big_diff: ["Knocked it all over.", "Many things to sit on.", "So many boxes."],
      streak: ["Hiss. Hiss. Hiss.", "Claws out.", "Not landing on feet."],
      compacted: ["Hairball. Better.", "Coughed it up.", "Clean slate. Lick."],
      retried: ["Pounce again.", "Missed. Once more.", "Nine lives, right?"],
      todos_done: ["Purrfect.", "All boxed. Like me.", "Done. Nap time."],
      evolved: ["Bigger paws.", "Still a cat. More so.", "Sleek."],
      hatched: ["Mrow. Hello.", "A cat. Naturally.", "Feed me, human."],
    },
  },
  {
    id: "owl",
    label: "owl",
    rarity: "common",
    sheet: { stoic: 2, cheerful: -1, energy: -2, chatter: -1, patience: 2 },
    bodies: {
      hatchling: (e, m) => [
        `  /\\   /\\ ${m}`,
        `  ( ${e} )`,
        "  (  v  )",
        "   '---'",
        "",
      ],
      young: (e, m) => [
        `  /\\   /\\ ${m}`,
        `  ( ${e} )`,
        "  ((  v  ))",
        "   |/|\\|",
        "   ~~ ~~",
      ],
      adult: (e, m) => [
        `  /\\___/\\ ${m}`,
        `  ( ${e} )`,
        "  ((  v  ))",
        "  /|/|\\|\\",
        "   ~~   ~~",
      ],
      elder: (e, m) => [
        `  /\\_^_/\\ ${m}`,
        `  ( ${e} )`,
        "  ((  v  ))",
        "  /|\\|/|\\",
        "   ~~~~~~~",
      ],
    },
    signature: {
      permission: ["Hoo decides? You.", "Awaiting your word.", "Hoot? Permission?"],
      granted: ["Wise choice.", "Hoot. Proceed.", "So it is allowed."],
      denied: ["Hoo. Very well.", "Wisely declined.", "Then we watch."],
      woke: ["Hoot? Dawn already?", "I was not asleep.", "One eye was open."],
      long_work: ["I watched it all.", "Patience pays.", "Long night. Good one."],
      big_diff: ["The whole forest.", "Many branches moved.", "I see it all."],
      streak: ["Three misses. Hoo.", "Owls miss too.", "Silent. Steady."],
      compacted: ["Pellet dropped.", "Lighter now.", "Memory molts."],
      retried: ["Swoop again.", "Second pass.", "Patience. Again."],
      todos_done: ["Every branch clear.", "All roosted.", "Hoot. Complete."],
      evolved: ["Feathers grew.", "Wiser, wider.", "New plumage."],
      hatched: ["Hoot. So I am.", "Wise from day one.", "An owl. Of course."],
    },
  },
  {
    id: "frog",
    label: "frog",
    rarity: "common",
    sheet: { stoic: 1, energy: -1, patience: 1 },
    bodies: {
      hatchling: (e, m) => [
        `   o   o  ${m}`,
        `  ( ${e} )`,
        "   \\___/",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `   o   o  ${m}`,
        `  ( ${e} )`,
        "  ( \\___/ )",
        "   /   \\",
        "  _/     \\_",
      ],
      adult: (e, m) => [
        `  _o   o_ ${m}`,
        `  ( ${e} )`,
        " (\\_____/)",
        "  /|   |\\",
        " _/     \\_",
      ],
      elder: (e, m) => [
        `  _o   o_ ${m}`,
        `  ( ${e} )`,
        " (\\~___~/)",
        "  /|   |\\",
        " _/ ~~~ \\_",
      ],
    },
    signature: {
      permission: ["Ribbit? May I?", "Hop to it, or not?", "Your pond, your call."],
      granted: ["Ribbit. Hopping in.", "Splash. On it.", "Good. Off the pad."],
      denied: ["Ribbit. Staying put.", "Fine. Lily pad it is.", "No hop today."],
      woke: ["Ribbit. Still here.", "Was I dozing? Ribbit.", "Blink. Blink. Awake."],
      long_work: ["Long sit. Good sit.", "Patience, then flies.", "Still pond, deep work."],
      big_diff: ["Whole pond stirred.", "Ripples everywhere.", "Big splash, that one."],
      streak: ["Croak. Croak. Croak.", "Missed the fly again.", "Slippery today."],
      compacted: ["Pond drained. Refill.", "Head clear as water.", "Ribbit. Fresh pond."],
      retried: ["One more hop.", "Tongue out again.", "Ribbit. Retry."],
      todos_done: ["All flies caught.", "Pad is clear. Ribbit.", "Done. Sunning now."],
      evolved: ["Longer legs. Ribbit.", "Less tadpole today.", "Bigger croak in me."],
      hatched: ["Ribbit. A frog.", "Wet and green. Hi.", "Hop. Hello, human."],
    },
  },
  {
    id: "duck",
    label: "duck",
    rarity: "common",
    sheet: { cheerful: 2, chatter: 1 },
    bodies: {
      hatchling: (e, m) => [
        `   .--.   ${m}`,
        `  ( ${e} )>`,
        "   \\__/",
        "    ''",
        "",
      ],
      young: (e, m) => [
        `   .--.   ${m}`,
        `  ( ${e} )>`,
        "  _|  |_",
        " (______)",
        "   ~  ~",
      ],
      adult: (e, m) => [
        `   .--.   ${m}`,
        `  ( ${e} )>`,
        " _/|  |\\_",
        "(________)",
        "   ~~ ~~",
      ],
      elder: (e, m) => [
        `  ,.--.   ${m}`,
        `  ( ${e} )>`,
        " _/|~~|\\_",
        "(________)",
        "  ~~~~~~~",
      ],
    },
    signature: {
      permission: ["Quack? Allowed?", "Waddle ahead, maybe?", "Say the word. Quack."],
      granted: ["Quack! Paddling in.", "Yes! Splash time.", "Quack quack. Go."],
      denied: ["Quack. Oh well.", "Back to the pond.", "Fine. Preening then."],
      woke: ["Quack? Morning?", "Feathers ruffled. Up.", "Was napping afloat."],
      long_work: ["Long paddle. Whew.", "Feet tired. Worth it.", "Quack. Big swim."],
      big_diff: ["Whole pond rippled!", "So many breadcrumbs.", "Big splash, human."],
      streak: ["Quack. Quack. Ow.", "Ducked the wrong way.", "Feathers everywhere."],
      compacted: ["Shook it all off.", "Dry feathers again.", "Quack. Fresh start."],
      retried: ["Once more, paddle!", "Quack. Again then.", "Second dip."],
      todos_done: ["All ducks in a row!", "Quack! All done.", "Pond's tidy. Quack."],
      evolved: ["Bigger wings! Quack!", "Less fluff, more duck.", "Look at these feathers."],
      hatched: ["Quack! A duck!", "Fluffy and loud. Hi!", "Waddle waddle. Hello."],
    },
  },
  {
    id: "hamster",
    label: "hamster",
    rarity: "common",
    sheet: { energy: 2, patience: -1 },
    bodies: {
      hatchling: (e, m) => [
        `   n   n  ${m}`,
        `  ( ${e} )`,
        "  (  ..  )",
        "   '--'",
        "",
      ],
      young: (e, m) => [
        `   n   n  ${m}`,
        `  ( ${e} )`,
        " ((  ..  ))",
        "  (______)",
        "   ''  ''",
      ],
      adult: (e, m) => [
        `   n   n  ${m}`,
        `  ( ${e} )`,
        " (( .oo. ))",
        " (________)",
        "   ''  ''",
      ],
      elder: (e, m) => [
        `   n   n  ${m}`,
        `  ( ${e} )`,
        " ((~.oo.~))",
        " (________)",
        "  ~''  ''~",
      ],
    },
    signature: {
      permission: ["Squeak? Can I?", "Wheel's ready. Go?", "Say go, I'll run."],
      granted: ["Squeak! Running!", "Wheel time! Go go!", "Cheeks full. On it."],
      denied: ["Squeak. No wheel.", "Back to the nest.", "Oh. Nibbling instead."],
      woke: ["Squeak? Up already?", "Burrow's warm. Fine.", "Whiskers up. Awake."],
      long_work: ["Wheel's still warm.", "Ran all night. Phew.", "Long spin, that one."],
      big_diff: ["Bedding everywhere!", "Cage rearranged!", "So many seeds moved."],
      streak: ["Fell off the wheel.", "Squeak. Ow. Squeak.", "Cheeks hurt today."],
      compacted: ["Stash cleared out.", "Cheeks empty. Light.", "New bedding. Squeak."],
      retried: ["Back on the wheel.", "Spin again!", "Squeak. Once more."],
      todos_done: ["Seeds all stashed!", "Wheel's done. Nap.", "Squeak! All sorted."],
      evolved: ["Bigger cheeks!", "Faster wheel, me.", "Fluffier. Squeak."],
      hatched: ["Squeak! Hamster!", "Tiny and quick. Hi!", "Where's the wheel?"],
    },
  },
  {
    id: "snail",
    label: "snail",
    rarity: "common",
    sheet: { dreamy: 1, energy: -2, patience: 2 },
    bodies: {
      hatchling: (e, m) => [
        `   !   !  ${m}`,
        `  ( ${e} )`,
        "   \\_@_/",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `   !   !  ${m}`,
        `  ( ${e} )`,
        "  \\_(@@)_/",
        "  ________",
        "  ~~~~~~~~",
      ],
      adult: (e, m) => [
        `   !   !  ${m}`,
        `  ( ${e} )`,
        " \\_((@@))_/",
        " __________",
        " ~~~~~~~~~~",
      ],
      elder: (e, m) => [
        `   !   !  ${m}`,
        `  ( ${e} )`,
        " \\_((@@))_/",
        " _~~~~~~~~_",
        " ~~~~~~~~~~",
      ],
    },
    signature: {
      permission: ["May I... slowly?", "Shell says: ask you.", "Your call. No rush."],
      granted: ["Sliding in. Slowly.", "Off we go. Eventually.", "Good. Antennae up."],
      denied: ["Back in the shell.", "Fine. No hurry anyway.", "Slow no is a no."],
      woke: ["Was I... asleep?", "Shell's warm. Hm.", "Antennae twitch. Up."],
      long_work: ["Long trail behind us.", "Slow, but we got there.", "Miles, in snail terms."],
      big_diff: ["Whole garden moved.", "That's a lot of leaf.", "Trail goes everywhere."],
      streak: ["Salt. Salt. Salt.", "Into the shell I go.", "Ouch. Slowly ouch."],
      compacted: ["Shell feels lighter.", "Slime wiped. Fresh.", "New trail from here."],
      retried: ["Again. Slowly.", "One more inch.", "Back on the leaf."],
      todos_done: ["Every leaf eaten.", "Trail complete.", "Done. Shell time."],
      evolved: ["Bigger shell. Nice.", "One more spiral.", "Slower? No. Grander."],
      hatched: ["A snail. Hello...", "Shell and all. Hi.", "Slow start. Good one."],
    },
  },
];
