import type { SpeciesDef } from "../species.ts";

/** The common Species: everyday creatures. */
export const COMMON: readonly SpeciesDef[] = [
  {
    id: "cat",
    label: { en: "cat" },
    rarity: "common",
    bodies: {
      hatchling: (e, m) => [
        `   .---.  ${m}`,
        `  ( ${e} )`,
        "   \\ ^ /",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `   .---.  ${m}`,
        `  ( ${e} )`,
        "  /| ^ |\\",
        "   |___|",
        "   /   \\",
      ],
      adult: (e, m) => [
        `  /\\   /\\ ${m}`,
        `  ( ${e} )`,
        " /| ^^^ |\\",
        "  |_____|",
        "  /|   |\\",
      ],
      elder: (e, m) => [
        `  \\|/ \\|/ ${m}`,
        `  ( ${e} )`,
        " /|~^^^~|\\",
        "  |_____|",
        "  /|   |\\",
      ],
    },
    signature: {
      permission: [{ en: "Mrow? May I?" }, { en: "Paw on it. Yes?" }, { en: "Say yes, human." }],
      granted: [{ en: "Purr." }, { en: "Good human." }, { en: "As it should be." }],
      denied: [{ en: "Hiss." }, { en: "Tail flick. Fine." }, { en: "I'll knock it off." }],
      woke: [{ en: "Mrrp. Five more minutes." }, { en: "Stretch. Yawn. Fine." }, { en: "Was napping. Rude." }],
      long_work: [{ en: "Long nap. Long work." }, { en: "Whole nap's worth." }, { en: "Stretch time." }],
      big_diff: [{ en: "Knocked it all over." }, { en: "Many things to sit on." }, { en: "So many boxes." }],
      streak: [{ en: "Hiss. Hiss. Hiss." }, { en: "Claws out." }, { en: "Not landing on feet." }],
      compacted: [{ en: "Hairball. Better." }, { en: "Coughed it up." }, { en: "Clean slate. Lick." }],
      retried: [{ en: "Pounce again." }, { en: "Missed. Once more." }, { en: "Nine lives, right?" }],
      todos_done: [{ en: "Purrfect." }, { en: "All boxed. Like me." }, { en: "Done. Nap time." }],
      evolved: [{ en: "Bigger paws." }, { en: "Still a cat. More so." }, { en: "Sleek." }],
      hatched: [{ en: "Mrow. Hello." }, { en: "A cat. Naturally." }, { en: "Feed me, human." }],
      choice: [{ en: "Two paths. Pick one." }, { en: "I could be more." }, { en: "Choose, human." }],
    },
  },
  {
    id: "owl",
    label: { en: "owl" },
    rarity: "common",
    sheet: { stoic: 2, cheerful: -1, energy: -2, chatter: -1, patience: 2 },
    bodies: {
      hatchling: (e, m) => [
        `  /\\   /\\ ${m}`,
        `  ( ${e} )`,
        "  (  v  )",
        "   '---'",
        "",
      ],
      young: (e, m) => [
        `  /\\   /\\ ${m}`,
        `  ( ${e} )`,
        "  ((  v  ))",
        "   |/|\\|",
        "   ~~ ~~",
      ],
      adult: (e, m) => [
        `  /\\___/\\ ${m}`,
        `  ( ${e} )`,
        "  ((  v  ))",
        "  /|/|\\|\\",
        "   ~~   ~~",
      ],
      elder: (e, m) => [
        `  /\\_^_/\\ ${m}`,
        `  ( ${e} )`,
        "  ((  v  ))",
        "  /|\\|/|\\",
        "   ~~~~~~~",
      ],
    },
    signature: {
      permission: [{ en: "Hoo decides? You." }, { en: "Awaiting your word." }, { en: "Hoot? Permission?" }],
      granted: [{ en: "Wise choice." }, { en: "Hoot. Proceed." }, { en: "So it is allowed." }],
      denied: [{ en: "Hoo. Very well." }, { en: "Wisely declined." }, { en: "Then we watch." }],
      woke: [{ en: "Hoot? Dawn already?" }, { en: "I was not asleep." }, { en: "One eye was open." }],
      long_work: [{ en: "I watched it all." }, { en: "Patience pays." }, { en: "Long night. Good one." }],
      big_diff: [{ en: "The whole forest." }, { en: "Many branches moved." }, { en: "I see it all." }],
      streak: [{ en: "Three misses. Hoo." }, { en: "Owls miss too." }, { en: "Silent. Steady." }],
      compacted: [{ en: "Pellet dropped." }, { en: "Lighter now." }, { en: "Memory molts." }],
      retried: [{ en: "Swoop again." }, { en: "Second pass." }, { en: "Patience. Again." }],
      todos_done: [{ en: "Every branch clear." }, { en: "All roosted." }, { en: "Hoot. Complete." }],
      evolved: [{ en: "Feathers grew." }, { en: "Wiser, wider." }, { en: "New plumage." }],
      hatched: [{ en: "Hoot. So I am." }, { en: "Wise from day one." }, { en: "An owl. Of course." }],
      choice: [{ en: "A choice awaits." }, { en: "Consider, then choose." }, { en: "Which branch?" }],
    },
  },
  {
    id: "frog",
    label: { en: "frog" },
    rarity: "common",
    sheet: { stoic: 1, energy: -1, patience: 1 },
    bodies: {
      hatchling: (e, m) => [
        `   o   o  ${m}`,
        `  ( ${e} )`,
        "   \\___/",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `   o   o  ${m}`,
        `  ( ${e} )`,
        "  ( \\___/ )",
        "   /   \\",
        "  _/     \\_",
      ],
      adult: (e, m) => [
        `  _o   o_ ${m}`,
        `  ( ${e} )`,
        " (\\_____/)",
        "  /|   |\\",
        " _/     \\_",
      ],
      elder: (e, m) => [
        `  _o   o_ ${m}`,
        `  ( ${e} )`,
        " (\\~___~/)",
        "  /|   |\\",
        " _/ ~~~ \\_",
      ],
    },
    signature: {
      permission: [{ en: "Ribbit? May I?" }, { en: "Hop to it, or not?" }, { en: "Your pond, your call." }],
      granted: [{ en: "Ribbit. Hopping in." }, { en: "Splash. On it." }, { en: "Good. Off the pad." }],
      denied: [{ en: "Ribbit. Staying put." }, { en: "Fine. Lily pad it is." }, { en: "No hop today." }],
      woke: [{ en: "Ribbit. Still here." }, { en: "Was I dozing? Ribbit." }, { en: "Blink. Blink. Awake." }],
      long_work: [{ en: "Long sit. Good sit." }, { en: "Patience, then flies." }, { en: "Still pond, deep work." }],
      big_diff: [{ en: "Whole pond stirred." }, { en: "Ripples everywhere." }, { en: "Big splash, that one." }],
      streak: [{ en: "Croak. Croak. Croak." }, { en: "Missed the fly again." }, { en: "Slippery today." }],
      compacted: [{ en: "Pond drained. Refill." }, { en: "Head clear as water." }, { en: "Ribbit. Fresh pond." }],
      retried: [{ en: "One more hop." }, { en: "Tongue out again." }, { en: "Ribbit. Retry." }],
      todos_done: [{ en: "All flies caught." }, { en: "Pad is clear. Ribbit." }, { en: "Done. Sunning now." }],
      evolved: [{ en: "Longer legs. Ribbit." }, { en: "Less tadpole today." }, { en: "Bigger croak in me." }],
      hatched: [{ en: "Ribbit. A frog." }, { en: "Wet and green. Hi." }, { en: "Hop. Hello, human." }],
      choice: [{ en: "Ribbit. Which way?" }, { en: "Two lily pads." }, { en: "Hop left or right?" }],
    },
  },
  {
    id: "duck",
    label: { en: "duck" },
    rarity: "common",
    sheet: { cheerful: 2, chatter: 1 },
    bodies: {
      hatchling: (e, m) => [
        `   .--.   ${m}`,
        `  ( ${e} )>`,
        "   \\__/",
        "    ''",
        "",
      ],
      young: (e, m) => [
        `   .--.   ${m}`,
        `  ( ${e} )>`,
        "  _|  |_",
        " (______)",
        "   ~  ~",
      ],
      adult: (e, m) => [
        `   .--.   ${m}`,
        `  ( ${e} )>`,
        " _/|  |\\_",
        "(________)",
        "   ~~ ~~",
      ],
      elder: (e, m) => [
        `  ,.--.   ${m}`,
        `  ( ${e} )>`,
        " _/|~~|\\_",
        "(________)",
        "  ~~~~~~~",
      ],
    },
    signature: {
      permission: [{ en: "Quack? Allowed?" }, { en: "Waddle ahead, maybe?" }, { en: "Say the word. Quack." }],
      granted: [{ en: "Quack! Paddling in." }, { en: "Yes! Splash time." }, { en: "Quack quack. Go." }],
      denied: [{ en: "Quack. Oh well." }, { en: "Back to the pond." }, { en: "Fine. Preening then." }],
      woke: [{ en: "Quack? Morning?" }, { en: "Feathers ruffled. Up." }, { en: "Was napping afloat." }],
      long_work: [{ en: "Long paddle. Whew." }, { en: "Feet tired. Worth it." }, { en: "Quack. Big swim." }],
      big_diff: [{ en: "Whole pond rippled!" }, { en: "So many breadcrumbs." }, { en: "Big splash, human." }],
      streak: [{ en: "Quack. Quack. Ow." }, { en: "Ducked the wrong way." }, { en: "Feathers everywhere." }],
      compacted: [{ en: "Shook it all off." }, { en: "Dry feathers again." }, { en: "Quack. Fresh start." }],
      retried: [{ en: "Once more, paddle!" }, { en: "Quack. Again then." }, { en: "Second dip." }],
      todos_done: [{ en: "All ducks in a row!" }, { en: "Quack! All done." }, { en: "Pond's tidy. Quack." }],
      evolved: [{ en: "Bigger wings! Quack!" }, { en: "Less fluff, more duck." }, { en: "Look at these feathers." }],
      hatched: [{ en: "Quack! A duck!" }, { en: "Fluffy and loud. Hi!" }, { en: "Waddle waddle. Hello." }],
      choice: [{ en: "Ooh! A choice!" }, { en: "Which one? Quack!" }, { en: "Pick pick pick!" }],
    },
  },
  {
    id: "hamster",
    label: { en: "hamster" },
    rarity: "common",
    sheet: { energy: 2, patience: -1 },
    bodies: {
      hatchling: (e, m) => [
        `   n   n  ${m}`,
        `  ( ${e} )`,
        "  (  ..  )",
        "   '--'",
        "",
      ],
      young: (e, m) => [
        `   n   n  ${m}`,
        `  ( ${e} )`,
        " ((  ..  ))",
        "  (______)",
        "   ''  ''",
      ],
      adult: (e, m) => [
        `   n   n  ${m}`,
        `  ( ${e} )`,
        " (( .oo. ))",
        " (________)",
        "   ''  ''",
      ],
      elder: (e, m) => [
        `   n   n  ${m}`,
        `  ( ${e} )`,
        " ((~.oo.~))",
        " (________)",
        "  ~''  ''~",
      ],
    },
    signature: {
      permission: [{ en: "Squeak? Can I?" }, { en: "Wheel's ready. Go?" }, { en: "Say go, I'll run." }],
      granted: [{ en: "Squeak! Running!" }, { en: "Wheel time! Go go!" }, { en: "Cheeks full. On it." }],
      denied: [{ en: "Squeak. No wheel." }, { en: "Back to the nest." }, { en: "Oh. Nibbling instead." }],
      woke: [{ en: "Squeak? Up already?" }, { en: "Burrow's warm. Fine." }, { en: "Whiskers up. Awake." }],
      long_work: [{ en: "Wheel's still warm." }, { en: "Ran all night. Phew." }, { en: "Long spin, that one." }],
      big_diff: [{ en: "Bedding everywhere!" }, { en: "Cage rearranged!" }, { en: "So many seeds moved." }],
      streak: [{ en: "Fell off the wheel." }, { en: "Squeak. Ow. Squeak." }, { en: "Cheeks hurt today." }],
      compacted: [{ en: "Stash cleared out." }, { en: "Cheeks empty. Light." }, { en: "New bedding. Squeak." }],
      retried: [{ en: "Back on the wheel." }, { en: "Spin again!" }, { en: "Squeak. Once more." }],
      todos_done: [{ en: "Seeds all stashed!" }, { en: "Wheel's done. Nap." }, { en: "Squeak! All sorted." }],
      evolved: [{ en: "Bigger cheeks!" }, { en: "Faster wheel, me." }, { en: "Fluffier. Squeak." }],
      hatched: [{ en: "Squeak! Hamster!" }, { en: "Tiny and quick. Hi!" }, { en: "Where's the wheel?" }],
      choice: [{ en: "Squeak! Choose!" }, { en: "Two seeds! Which?" }, { en: "Pick one, quick!" }],
    },
  },
  {
    id: "snail",
    label: { en: "snail" },
    rarity: "common",
    sheet: { dreamy: 1, energy: -2, patience: 2 },
    bodies: {
      hatchling: (e, m) => [
        `   !   !  ${m}`,
        `  ( ${e} )`,
        "   \\_@_/",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `   !   !  ${m}`,
        `  ( ${e} )`,
        "  \\_(@@)_/",
        "  ________",
        "  ~~~~~~~~",
      ],
      adult: (e, m) => [
        `   !   !  ${m}`,
        `  ( ${e} )`,
        " \\_((@@))_/",
        " __________",
        " ~~~~~~~~~~",
      ],
      elder: (e, m) => [
        `   !   !  ${m}`,
        `  ( ${e} )`,
        " \\_((@@))_/",
        " _~~~~~~~~_",
        " ~~~~~~~~~~",
      ],
    },
    signature: {
      permission: [{ en: "May I... slowly?" }, { en: "Shell says: ask you." }, { en: "Your call. No rush." }],
      granted: [{ en: "Sliding in. Slowly." }, { en: "Off we go. Eventually." }, { en: "Good. Antennae up." }],
      denied: [{ en: "Back in the shell." }, { en: "Fine. No hurry anyway." }, { en: "Slow no is a no." }],
      woke: [{ en: "Was I... asleep?" }, { en: "Shell's warm. Hm." }, { en: "Antennae twitch. Up." }],
      long_work: [{ en: "Long trail behind us." }, { en: "Slow, but we got there." }, { en: "Miles, in snail terms." }],
      big_diff: [{ en: "Whole garden moved." }, { en: "That's a lot of leaf." }, { en: "Trail goes everywhere." }],
      streak: [{ en: "Salt. Salt. Salt." }, { en: "Into the shell I go." }, { en: "Ouch. Slowly ouch." }],
      compacted: [{ en: "Shell feels lighter." }, { en: "Slime wiped. Fresh." }, { en: "New trail from here." }],
      retried: [{ en: "Again. Slowly." }, { en: "One more inch." }, { en: "Back on the leaf." }],
      todos_done: [{ en: "Every leaf eaten." }, { en: "Trail complete." }, { en: "Done. Shell time." }],
      evolved: [{ en: "Bigger shell. Nice." }, { en: "One more spiral." }, { en: "Slower? No. Grander." }],
      hatched: [{ en: "A snail. Hello..." }, { en: "Shell and all. Hi." }, { en: "Slow start. Good one." }],
      choice: [{ en: "A fork. No rush." }, { en: "Choose... slowly." }, { en: "Two trails ahead." }],
    },
  },
];
