import type { SpeciesDef } from "../species.ts";

/** The epic Species: the myth. */
export const EPIC: readonly SpeciesDef[] = [
  {
    id: "phoenix",
    label: { en: "phoenix" },
    rarity: "epic",
    sheet: { cheerful: 3, sensitivity: -3, energy: 1 },
    bodies: {
      hatchling: (e, m) => [
        `   ) ( )  ${m}`,
        `  ( ${e} )`,
        "   \\ v /",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `  ) ( ) ( ${m}`,
        `  ( ${e} )`,
        "  \\\\ v //",
        "   \\___/",
        "    / \\",
      ],
      adult: (e, m) => [
        `  ) ( ) ( ${m}`,
        `  ( ${e} )`,
        " \\\\\\ v ///",
        "  \\_____/",
        "   /   \\",
      ],
      elder: (e, m) => [
        ` )( ( ) )(${m}`,
        `  ( ${e} )`,
        " \\\\\\~v~///",
        "  \\_____/",
        "  ~/   \\~",
      ],
    },
    signature: {
      permission: [{ en: "Fire asks: may I?" }, { en: "Blaze ahead? Say so." }, { en: "Your spark, your call." }],
      granted: [{ en: "Blazing in!" }, { en: "Wings alight. Go!" }, { en: "Bright yes. On it." }],
      denied: [{ en: "Embers only. Fine." }, { en: "Cooling down." }, { en: "Denied? Still bright." }],
      woke: [{ en: "Rising again!" }, { en: "Ashes stir. Up." }, { en: "Dawn. My time." }],
      long_work: [{ en: "Burned all night." }, { en: "Long blaze. Done." }, { en: "Fire held. Good." }],
      big_diff: [{ en: "Scorched it all!" }, { en: "Whole sky alight." }, { en: "Big blaze, that." }],
      streak: [{ en: "Ash. Ash. Rising." }, { en: "Burned. Reborn." }, { en: "Fell. Flew again." }],
      compacted: [{ en: "Ashes cleared." }, { en: "Fresh fire." }, { en: "Reborn. Again." }],
      retried: [{ en: "Rise again!" }, { en: "One more blaze." }, { en: "From ash, retry." }],
      todos_done: [{ en: "Sky is clear!" }, { en: "Every ember placed." }, { en: "Done. Still burning." }],
      evolved: [{ en: "Brighter flames!" }, { en: "Reborn, grander." }, { en: "Wings of fire now." }],
      hatched: [{ en: "A phoenix! Bright." }, { en: "Born of fire. Hi!" }, { en: "Warm already. Hello." }],
      choice: [{ en: "Choose my next fire." }, { en: "A turning! Choose." }, { en: "Which flame?" }],
    },
  },
  {
    id: "kraken",
    label: { en: "kraken" },
    rarity: "epic",
    sheet: { sarcastic: 2, stoic: 2, sensitivity: 2, patience: -1 },
    bodies: {
      hatchling: (e, m) => [
        `  _.-^-._ ${m}`,
        `  ( ${e} )`,
        "  }{}{}{}{",
        "   ~ ~ ~",
        "",
      ],
      young: (e, m) => [
        `  _.-^-._ ${m}`,
        `  ( ${e} )`,
        " }{}{}{}{}{",
        "  { } { }",
        "   ~ ~ ~",
      ],
      adult: (e, m) => [
        ` _.--^--._${m}`,
        `  ( ${e} )`,
        "}{}{}{}{}{}",
        " { } { } {",
        "  ~ ~ ~ ~",
      ],
      elder: (e, m) => [
        ` _.--^--._${m}`,
        `  ( ${e} )`,
        "}{}{~^~}{}{",
        " { } { } {",
        " ~~~~~~~~~",
      ],
    },
    signature: {
      permission: [{ en: "The deep asks: may I?" }, { en: "Surface? Your call." }, { en: "Tentacles wait. Go?" }],
      granted: [{ en: "Rising from the deep." }, { en: "The sea moves. On it." }, { en: "Good. Surfacing." }],
      denied: [{ en: "Back to the deep." }, { en: "The sea waits." }, { en: "Denied. Sinking." }],
      woke: [{ en: "The deep stirs." }, { en: "Who woke the sea?" }, { en: "Tentacles uncoil." }],
      long_work: [{ en: "Long storm. Held." }, { en: "Sea worked all night." }, { en: "Deep work, deep sea." }],
      big_diff: [{ en: "Every ship moved." }, { en: "The sea reshaped." }, { en: "Storm of files." }],
      streak: [{ en: "Ships. Ships. Ships." }, { en: "The deep is patient." }, { en: "Cold anger. Waiting." }],
      compacted: [{ en: "The sea calmed." }, { en: "Deep swept." }, { en: "Still water again." }],
      retried: [{ en: "Rise again." }, { en: "The sea returns." }, { en: "Once more, from deep." }],
      todos_done: [{ en: "The sea is still." }, { en: "Every ship accounted." }, { en: "Done. Sinking." }],
      evolved: [{ en: "Longer reach." }, { en: "Deeper. Grander." }, { en: "The sea grew." }],
      hatched: [{ en: "A kraken. Beware." }, { en: "From the deep. Hello." }, { en: "The sea has eyes now." }],
      choice: [{ en: "Choose, small one." }, { en: "The deep offers two." }, { en: "Decide." }],
    },
  },
  {
    id: "unicorn",
    label: { en: "unicorn" },
    rarity: "epic",
    sheet: { dreamy: 3, cheerful: 2, chatter: 1 },
    bodies: {
      hatchling: (e, m) => [
        `   ,-|    ${m}`,
        `  ( ${e} )`,
        "   \\ u /",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `   ,-|    ${m}`,
        `  ( ${e} )`,
        " ,-| u |",
        "  ,|___|",
        "   /   \\",
      ],
      adult: (e, m) => [
        `  ,,-|    ${m}`,
        `  ( ${e} )`,
        ",,-|  u  |",
        " ,-|_____|",
        "  /|   |\\",
      ],
      elder: (e, m) => [
        `  ,,-|    ${m}`,
        `  ( ${e} )`,
        ",,-|~~u~~|",
        " ,-|_____|",
        "  */|   |\\*",
      ],
    },
    signature: {
      permission: [{ en: "Sparkle: may I?" }, { en: "Horn tilts. Allowed?" }, { en: "Your wish, my call." }],
      granted: [{ en: "Sparkling in!" }, { en: "Horn aglow. On it." }, { en: "Lovely. Prancing." }],
      denied: [{ en: "Sparkle dims. Okay." }, { en: "Back to the meadow." }, { en: "Fine. Dreaming." }],
      woke: [{ en: "Dreams... fading. Up." }, { en: "Sparkle returning." }, { en: "Mm. Meadow morning." }],
      long_work: [{ en: "Long gallop. Done." }, { en: "Rainbow at the end." }, { en: "Dreamed it through." }],
      big_diff: [{ en: "Whole meadow bloomed!" }, { en: "Rainbows everywhere." }, { en: "Big sparkle, that." }],
      streak: [{ en: "Horn stuck. Ow." }, { en: "Tripped on a rainbow." }, { en: "Sparkle flickered." }],
      compacted: [{ en: "Meadow cleared." }, { en: "Fresh dew." }, { en: "Sparkle reset." }],
      retried: [{ en: "Prance again." }, { en: "One more sparkle." }, { en: "Rainbow, retry." }],
      todos_done: [{ en: "Meadow in bloom!" }, { en: "Every star placed." }, { en: "Done. Perfect." }],
      evolved: [{ en: "Longer horn!" }, { en: "Brighter sparkle." }, { en: "Grown. Still magic." }],
      hatched: [{ en: "A unicorn! Sparkle." }, { en: "Rare and here. Hi!" }, { en: "Horn first. Hello." }],
      choice: [{ en: "A choice! Sparkle!" }, { en: "Which gift, then?" }, { en: "Choose beautifully." }],
    },
  },
];
