import type { SpeciesDef } from "../species.ts";

/** The epic Species: the myth. */
export const EPIC: readonly SpeciesDef[] = [
  {
    id: "phoenix",
    label: { en: "phoenix", fr: "phénix" },
    gender: "m",
    rarity: "epic",
    sheet: { cheerful: 3, sensitivity: -3, energy: 1 },
    maps: {
      hatchling: {
        pixels: [
          ".....................",
          ".....................",
          "..........c..........",
          "........c.o.c........",
          "........o...o........",
          ".......ooooooo.......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          ".......bbbbbbb.......",
          "........ooooo........",
          ".........c.c.........",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 7, y: 6, w: 3, h: 3 }, { x: 11, y: 6, w: 3, h: 3 }],
      },
      young: {
        pixels: [
          ".....................",
          ".........c.c.........",
          ".......c.o.o.c.......",
          ".......o.....o.......",
          "......ooooooooo......",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaao.....",
          "....oooooooooooo.....",
          "bccccaaaaaaaaaaaccccb",
          "....oaaaaaaaaaao.....",
          "......ooooooooo......",
          "........bbbbb........",
          ".........c.c.........",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 5, w: 3, h: 3 }, { x: 11, y: 5, w: 3, h: 3 }],
      },
      adult: {
        pixels: [
          "........c.c.c........",
          "......c.o.o.o.c......",
          "......o.......o......",
          ".....ooooooooooo.....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....ooooooooooooo....",
          "bccccaaaaaaaaaaaccccb",
          "...ooooooooooooooo...",
          "....oaaaaaaaaaaao....",
          "......ooooooooo......",
          "......bbbbbbbbb......",
          "........c....c.......",
          "........c....c.......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 4, w: 3, h: 3 }, { x: 11, y: 4, w: 3, h: 3 }],
        motion: { ears: [{ x: 8, y: 13, w: 2, h: 2 }, { x: 13, y: 13, w: 2, h: 2 }] },
      },
      elder: {
        pixels: [
          "........c.c.c........",
          "......c.o.o.o.c......",
          "......o.......o......",
          ".....ooooooooooo.....",
          "....oaaaaaaaaaaao....",
          "....oacaaaaaaaaao....",
          "....oaaaaaaaaacao....",
          "....ooooooooooooo....",
          "bccccaaaaaaaaaaaccccb",
          "bccccaaaaaaaaaaaccccb",
          "...ooooooooooooooo...",
          "....oaaaaaaaaaaao....",
          "......ooooooooo......",
          ".....bbbbbbbbbbb.....",
          ".......c..c..c.......",
          ".......c..c..c.......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 4, w: 3, h: 3 }, { x: 11, y: 4, w: 3, h: 3 }],
        motion: { ears: [{ x: 7, y: 14, w: 2, h: 2 }, { x: 10, y: 14, w: 2, h: 2 }, { x: 13, y: 14, w: 2, h: 2 }] },
      },
    },
    palettes: {
      dark: { outline: "#3d0f0a", primary: "#e8481f", secondary: "#ffcf4a", accent: "#8a1a1a", eye: "#1a0a08" },
      light: { outline: "#2b0a06", primary: "#c73815", secondary: "#e8b52e", accent: "#6b1212", eye: "#140705" },
    },
    signature: {
      permission: [{ en: "Fire asks: may I?", fr: "Ce feu peut partir ?" }, { en: "Blaze ahead? Say so.", fr: "Ça flambe ? Dis-le." }, { en: "Your spark, your call.", fr: "L'étincelle attend." }],
      granted: [{ en: "Blazing in!", fr: "Me voilà en flammes !" }, { en: "Wings alight. Go!", fr: "Plumes en feu. Partons !" }, { en: "Bright yes. On it.", fr: "Un oui clair. Je fonce." }],
      denied: [{ en: "Embers only. Fine.", fr: "Des braises, au mieux." }, { en: "Cooling down.", fr: "Feu couvert. Compris." }, { en: "Denied? Still bright.", fr: "Éteint ? Pas vraiment." }],
      woke: [{ en: "Rising again!", fr: "Rallumé. Ça repart." }, { en: "Ashes stir. Up.", fr: "Cendres qui remuent." }, { en: "Dawn. My time.", fr: "L'aube. Mon heure." }],
      long_work: [{ en: "Burned all night.", fr: "Toute la nuit, à brûler." }, { en: "Long blaze. Done.", fr: "Des heures de flammes." }, { en: "Fire held. Good.", fr: "Feu tenu jusqu'au bout." }],
      big_diff: [{ en: "Scorched it all!", fr: "Incendie général !" }, { en: "Whole sky alight.", fr: "Ciel entier en feu." }, { en: "Big blaze, that.", fr: "Quel brasier, dis donc." }],
      streak: [{ en: "Ash. Ash. Rising.", fr: "Cendre. Cendre. Envol." }, { en: "Burned. Reborn.", fr: "Brûlé. Renaissance." }, { en: "Fell. Flew again.", fr: "À terre, puis au ciel." }],
      compacted: [{ en: "Ashes cleared.", fr: "Cendres dispersées." }, { en: "Fresh fire.", fr: "Braises neuves." }, { en: "Reborn. Again.", fr: "Reparti de rien." }],
      retried: [{ en: "Rise again!", fr: "Flambée numéro deux." }, { en: "One more blaze.", fr: "Le feu repart." }, { en: "From ash, retry.", fr: "Des cendres, et je vole." }],
      todos_done: [{ en: "Sky is clear!", fr: "Le ciel est dégagé !" }, { en: "Every ember placed.", fr: "Ni fumée ni braise." }, { en: "Done. Still burning.", fr: "Achevé. Toujours chaud." }],
      evolved: [{ en: "Brighter flames!", fr: "Flammes plus hautes !" }, { en: "Reborn, grander.", fr: "Le feu a monté d'un ton." }, { en: "Wings of fire now.", fr: "Mon envergure a doublé." }],
      hatched: [{ en: "A phoenix! Bright.", fr: "Né dans les flammes." }, { en: "Born of fire. Hi!", fr: "Phénix. Approche-toi." }, { en: "Warm already. Hello.", fr: "Ça chauffe déjà, non ?" }],
      choice: [{ en: "Choose my next fire.", fr: "Quel feu, à présent ?" }, { en: "A turning! Choose.", fr: "Brûler autrement ? Oui." }, { en: "Which flame?", fr: "Souffle. Je m'embrase." }],
    },
  },
  {
    id: "kraken",
    label: { en: "kraken", fr: "kraken" },
    gender: "m",
    rarity: "epic",
    sheet: { sarcastic: 2, stoic: 2, sensitivity: 2, patience: -1 },
    maps: {
      hatchling: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          "..........o..........",
          "........o...o........",
          ".......oaaaaao.......",
          "......obbbabbbo......",
          "......obbbabbbo......",
          "......obbbabbbo......",
          ".......ooooooo.......",
          "........aa.aa........",
          "........b...b........",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 7, y: 6, w: 3, h: 3 }, { x: 11, y: 6, w: 3, h: 3 }],
      },
      young: {
        pixels: [
          ".....................",
          ".....................",
          ".........o.o.........",
          ".......o.....o.......",
          "......oaaaaaaao......",
          ".....obbbaabbbao.....",
          ".....obbbaabbbao.....",
          ".....obbbaabbbao.....",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaao.....",
          ".....ooooooooooo.....",
          ".....aa.aa.aa.aa.....",
          "......a...a...a......",
          "......b...b...b......",
          "......c.......c......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 5, w: 3, h: 3 }, { x: 11, y: 5, w: 3, h: 3 }],
      },
      adult: {
        pixels: [
          "........o.o.o........",
          "......o.......o......",
          ".....oaaaaaaaaao.....",
          "....oaaaaaaaaaaao....",
          "...oabbbaaaabbbaao...",
          "...oabbbaaaabbbaao...",
          "...oabbbaaaabbbaao...",
          "...oaaaaaaaaaacaao...",
          "...oaaaaaaaaaaaaao...",
          "...oaaaaaaaaaaaaao...",
          "...ooooooooooooooo...",
          "...aa.aa.aa.aa.aa....",
          "....a..a.b...a..a....",
          "....b..b.a...ba.b....",
          "....c...........c....",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 5, y: 4, w: 3, h: 3 }, { x: 12, y: 4, w: 3, h: 3 }],
        motion: { ears: [{ x: 9, y: 13, w: 2, h: 1 }, { x: 14, y: 13, w: 2, h: 1 }] },
      },
      elder: {
        pixels: [
          "........c.o.c........",
          "......o.......o......",
          ".....oaaaaaaaaao.....",
          "....oaaaaaaaaaaao....",
          "..oabbbabaaaabbbaao..",
          "..oabbbaaaaaabbbaao..",
          "..oabbbaaaaaabbbaao..",
          "..oaaaaaaaaaaaacaao..",
          "..oaaaaaaaaabaaaaao..",
          "..oaaaaaaaaaaaaaaao..",
          "..ooooooooooooooooo..",
          ".aa.aa.aa.aa.aa.aa.a.",
          "..a..a..b..a..a..a...",
          "..b..b.a...ba.ba.b...",
          "..c..............c...",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 4, y: 4, w: 3, h: 3 }, { x: 13, y: 4, w: 3, h: 3 }],
        motion: { ears: [{ x: 7, y: 13, w: 2, h: 1 }, { x: 12, y: 13, w: 2, h: 1 }, { x: 15, y: 13, w: 2, h: 1 }] },
      },
    },
    palettes: {
      dark: { outline: "#050c0d", primary: "#123138", secondary: "#5fa89c", accent: "#4de8c4", eye: "#050505" },
      light: { outline: "#03080a", primary: "#0c262b", secondary: "#4a8f84", accent: "#2fae95", eye: "#050505" },
    },
    signature: {
      permission: [{ en: "The deep asks: may I?", fr: "D'en bas : un signe ?" }, { en: "Surface? Your call.", fr: "Remonter ? Tu décides." }, { en: "Tentacles wait. Go?", fr: "Tentacules suspendus." }],
      granted: [{ en: "Rising from the deep.", fr: "Ça remonte du fond." }, { en: "The sea moves. On it.", fr: "Remous. Je m'exécute." }, { en: "Good. Surfacing.", fr: "Vers la surface, donc." }],
      denied: [{ en: "Back to the deep.", fr: "Les abysses, voilà tout." }, { en: "The sea waits.", fr: "L'eau sait attendre." }, { en: "Denied. Sinking.", fr: "Soit. Je sombre." }],
      woke: [{ en: "The deep stirs.", fr: "Le fond s'agite." }, { en: "Who woke the sea?", fr: "Qui réveille la mer ?" }, { en: "Tentacles uncoil.", fr: "Tentacules déroulés." }],
      long_work: [{ en: "Long storm. Held.", fr: "Tempête traversée." }, { en: "Sea worked all night.", fr: "Nuit entière sous l'eau." }, { en: "Deep work, deep sea.", fr: "Du travail de fond." }],
      big_diff: [{ en: "Every ship moved.", fr: "Chaque navire déplacé." }, { en: "The sea reshaped.", fr: "Fonds remodelés." }, { en: "Storm of files.", fr: "Mer démontée. Voilà." }],
      streak: [{ en: "Ships. Ships. Ships.", fr: "Navire. Navire. Navire." }, { en: "The deep is patient.", fr: "Rien ne presse, en bas." }, { en: "Cold anger. Waiting.", fr: "Colère froide. Patience." }],
      compacted: [{ en: "The sea calmed.", fr: "Houle tombée." }, { en: "Deep swept.", fr: "Abysses dégagés." }, { en: "Still water again.", fr: "Surface lisse, enfin." }],
      retried: [{ en: "Rise again.", fr: "Nouvelle remontée." }, { en: "The sea returns.", fr: "Les eaux reviennent." }, { en: "Once more, from deep.", fr: "Troisième vague." }],
      todos_done: [{ en: "The sea is still.", fr: "Calme plat." }, { en: "Every ship accounted.", fr: "Navires tous comptés." }, { en: "Done. Sinking.", fr: "Je coule, satisfait." }],
      evolved: [{ en: "Longer reach.", fr: "Tout est à portée." }, { en: "Deeper. Grander.", fr: "Deux nouveaux bras." }, { en: "The sea grew.", fr: "L'océan a grandi." }],
      hatched: [{ en: "A kraken. Beware.", fr: "Kraken. Ne crie pas." }, { en: "From the deep. Hello.", fr: "Venu des abysses." }, { en: "The sea has eyes now.", fr: "La mer a des yeux." }],
      choice: [{ en: "Choose, small one.", fr: "Alors, petite chose ?" }, { en: "The deep offers two.", fr: "D'en bas, deux routes." }, { en: "Decide.", fr: "Tranche, maintenant." }],
    },
  },
  {
    id: "unicorn",
    label: { en: "unicorn", fr: "licorne" },
    gender: "f",
    rarity: "epic",
    sheet: { dreamy: 3, cheerful: 2, chatter: 1 },
    maps: {
      hatchling: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          "..........c..........",
          "..........o..........",
          ".......ooooooo.......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          ".......ooooooo.......",
          "........bbbbb........",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 7, y: 6, w: 3, h: 3 }, { x: 11, y: 6, w: 3, h: 3 }],
      },
      young: {
        pixels: [
          ".....................",
          ".........c...........",
          ".........c...........",
          "........oco..........",
          "......ooooooooo......",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaab.....",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaab.....",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaao.....",
          "......ooooooooo......",
          ".......bbbbbbb.......",
          ".......bbbbbbb.bb....",
          ".........c.c.........",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 5, w: 3, h: 3 }, { x: 11, y: 5, w: 3, h: 3 }],
      },
      adult: {
        pixels: [
          ".........c...........",
          ".........c...........",
          "........oco..........",
          ".........c...........",
          ".....ooooooooooo.....",
          "....oaaaaaaaaaaao....",
          "...oaaaaaaaaaaaaaob..",
          "...oaaaaaaaaaaaaaob..",
          "...oaaaaaaaaaaaaaob..",
          "...oaaaaaaaaaaaaaob..",
          "...oaaaaaaaaaaaaao...",
          ".b.booooooooooooobb..",
          ".b.b..bbbbbbbbb......",
          "......bbbbbbbbb......",
          "........c...c........",
          "......oo....oo.......",
          "......co....oc.......",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 5, y: 4, w: 3, h: 3 }, { x: 12, y: 4, w: 3, h: 3 }],
        motion: { tail: { x: 0, y: 11, w: 3, h: 2 }, ears: [{ x: 18, y: 6, w: 2, h: 4 }] },
      },
      elder: {
        pixels: [
          ".........c...........",
          ".........c...........",
          ".........c...........",
          "........oco..........",
          ".....ooooooooooo.....",
          "....oaaaaaaaaaaao....",
          "...oaaaaaaaaaaaaaob..",
          "...oaaaaaaaaaaaaaob..",
          "...oaaaaaaaaaaaaaob..",
          "...oaaaaaaaaaaaaaob..",
          "...oaaaaaaaaaaaaaob..",
          ".b.booooooooooooobb..",
          ".b.b.bbbbbbbbbbb.b...",
          ".b.b.bbbbbbbbbbb.....",
          ".......c..c..c.......",
          ".....oo.....oo.......",
          ".....co.....oc.......",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 5, y: 4, w: 3, h: 3 }, { x: 12, y: 4, w: 3, h: 3 }],
        motion: { tail: { x: 0, y: 11, w: 3, h: 3 }, ears: [{ x: 18, y: 6, w: 2, h: 5 }] },
      },
    },
    palettes: {
      dark: { outline: "#8a76a0", primary: "#f0e6f5", secondary: "#f5b8d0", accent: "#e8c34a", eye: "#4a3a5c" },
      light: { outline: "#6b5a80", primary: "#dcc9e8", secondary: "#e89dc0", accent: "#c9992e", eye: "#3a2d48" },
    },
    signature: {
      permission: [{ en: "Sparkle: may I?", fr: "Corne baissée. J'ose ?" }, { en: "Horn tilts. Allowed?", fr: "Tu me laisses briller ?" }, { en: "Your wish, my call.", fr: "Fais un vœu. J'écoute." }],
      granted: [{ en: "Sparkling in!", fr: "Paillettes en avant !" }, { en: "Horn aglow. On it.", fr: "Corne allumée. Hop !" }, { en: "Lovely. Prancing.", fr: "Charmant. Je caracole." }],
      denied: [{ en: "Sparkle dims. Okay.", fr: "L'éclat retombe un peu." }, { en: "Back to the meadow.", fr: "Direction le pré." }, { en: "Fine. Dreaming.", fr: "Rêvons plutôt." }],
      woke: [{ en: "Dreams... fading. Up.", fr: "Mes rêves s'effilochent." }, { en: "Sparkle returning.", fr: "Paillettes, me revoilà." }, { en: "Mm. Meadow morning.", fr: "Rosée. Le pré s'éveille." }],
      long_work: [{ en: "Long gallop. Done.", fr: "Quel galop ! Et voilà." }, { en: "Rainbow at the end.", fr: "L'arc-en-ciel arrive." }, { en: "Dreamed it through.", fr: "Tout ça en rêvant." }],
      big_diff: [{ en: "Whole meadow bloomed!", fr: "Fleurs sur tout le pré !" }, { en: "Rainbows everywhere.", fr: "Arc-en-ciel intégral !" }, { en: "Big sparkle, that.", fr: "Paillettes à la pelle !" }],
      streak: [{ en: "Horn stuck. Ow.", fr: "Corne coincée. Ouille." }, { en: "Tripped on a rainbow.", fr: "L'arc-en-ciel m'a eue." }, { en: "Sparkle flickered.", fr: "Plus beaucoup d'éclat." }],
      compacted: [{ en: "Meadow cleared.", fr: "Pré tondu. Ça respire." }, { en: "Fresh dew.", fr: "Un peu de rosée." }, { en: "Sparkle reset.", fr: "Paillettes rechargées." }],
      retried: [{ en: "Prance again.", fr: "Au galop ! Allez !" }, { en: "One more sparkle.", fr: "Rebelote, en brillant." }, { en: "Rainbow, retry.", fr: "Sous l'arc-en-ciel, hop." }],
      todos_done: [{ en: "Meadow in bloom!", fr: "Pré tout en fleurs !" }, { en: "Every star placed.", fr: "Les étoiles sont posées." }, { en: "Done. Perfect.", fr: "C'est parfait, non ?" }],
      evolved: [{ en: "Longer horn!", fr: "Corne rallongée !" }, { en: "Brighter sparkle.", fr: "Ça brille davantage !" }, { en: "Grown. Still magic.", fr: "Magie intacte. Voilà." }],
      hatched: [{ en: "A unicorn! Sparkle.", fr: "Licorne. Oui, vraiment." }, { en: "Rare and here. Hi!", fr: "Corne en premier. Tada !" }, { en: "Horn first. Hello.", fr: "J'ai rêvé de ce jour." }],
      choice: [{ en: "A choice! Sparkle!", fr: "Regarde ! Ça bifurque !" }, { en: "Which gift, then?", fr: "Tu préfères lequel ?" }, { en: "Choose beautifully.", fr: "Prends le plus beau." }],
    },
  },
];
