import type { SpeciesDef } from "../species.ts";

/** The legendary Species: the dragon alone, so it keeps its standing. */
export const LEGENDARY: readonly SpeciesDef[] = [
  {
    id: "dragon",
    label: { en: "dragon", fr: "dragon" },
    gender: "m",
    rarity: "legendary",
    sheet: { sarcastic: 3, sensitivity: -2, energy: 2 },
    maps: {
      hatchling: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          ".......o.....o.......",
          "........o...o........",
          "........ooooo........",
          "......obbbabbbo......",
          "......obbbabbbo......",
          "......obbbabbbo......",
          "......oaaaaaaao......",
          ".......ooooooo.......",
          "........bbcbb........",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 7, y: 6, w: 3, h: 3 }, { x: 11, y: 6, w: 3, h: 3 }],
      },
      young: {
        pixels: [
          ".....................",
          ".....................",
          "......o.......o......",
          ".......o.....o.......",
          "........ooooo........",
          ".....oaaaaaaaaao.....",
          ".....obbbaabbbao.....",
          "...a.obbbaabbbao.a...",
          ".....obbbaabbbao.....",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaao.....",
          "......ooooooooo......",
          ".......bbbbbbb...a...",
          ".........c.c...aa....",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 6, w: 3, h: 3 }, { x: 11, y: 6, w: 3, h: 3 }],
      },
      adult: {
        pixels: [
          ".....................",
          ".....o.........o.....",
          "......o.......o......",
          ".......o.....o.......",
          "........ooooo........",
          "....oaaaaaaaaaaao....",
          "...oabbbaaabbbaaao...",
          "...oabbbaaabbbaaao...",
          ".oaaabbbaaabbbaaao...",
          "..oaaaaaaaaaaaaaaao..",
          "...oaaaaaaaaaaaaao...",
          "....ooooooooooooo....",
          "......bbbbbbbbb.a.a..",
          "......b.c...c.b.a.a..",
          "..................a..",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 5, y: 6, w: 3, h: 3 }, { x: 11, y: 6, w: 3, h: 3 }],
        motion: { tail: { x: 17, y: 12, w: 3, h: 2 } },
      },
      elder: {
        pixels: [
          ".....................",
          "....o...........o....",
          ".....o.........o.....",
          "......o.......o......",
          ".......ooooooo.......",
          "....oaaaaaaaaaaao....",
          "..oabbbaaaaabbbaaao..",
          "..oabbbaaaaabbbaaao..",
          "oaaabbbaaaaabbbaaaaao",
          ".oaaaaaaaaaaaaaaaaao.",
          "..oaaaaaaaaaaaaaaao..",
          "...ooooooooooooooo...",
          ".....bbbbbbbbbbba.a..",
          ".....b.c..c..c.ba.a..",
          "................a.a..",
          "..................a..",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 4, y: 6, w: 3, h: 3 }, { x: 12, y: 6, w: 3, h: 3 }],
        motion: { tail: { x: 17, y: 12, w: 3, h: 3 } },
      },
    },
    palettes: {
      dark: { outline: "#0a1f12", primary: "#1f6b3f", secondary: "#e8c34a", accent: "#e8621f", eye: "#3a2c08" },
      light: { outline: "#06140b", primary: "#154d2d", secondary: "#c9a532", accent: "#c94f14", eye: "#2b2006" },
    },
    signature: {
      permission: [{ en: "Grant it, mortal.", fr: "Accordez-le, mortel." }, { en: "Permission? Amusing.", fr: "Permission ? Amusant." }, { en: "I await. Briefly.", fr: "Ne tardez pas trop." }],
      granted: [{ en: "Naturally.", fr: "Naturellement." }, { en: "The gates open.", fr: "Les portes s'ouvrent." }, { en: "As decreed.", fr: "Ainsi fut-il décrété." }],
      denied: [{ en: "Denied? Me?", fr: "Me refuser, moi ?" }, { en: "Smoke. Just smoke.", fr: "Fumée. Rien de plus." }, { en: "Your loss.", fr: "Vous y perdez." }],
      woke: [{ en: "The mountain stirs.", fr: "Réveil sous la montagne." }, { en: "Who wakes a dragon?", fr: "Troubler mon sommeil ?" }, { en: "Ashes. Then fire.", fr: "Suie. Le feu arrive." }],
      long_work: [{ en: "A siege, well fought.", fr: "Beau siège. Place prise." }, { en: "Long flight. Landed.", fr: "Vol achevé. Posé." }, { en: "The hoard grows.", fr: "Mon trésor grossit." }],
      big_diff: [{ en: "I scorched it all.", fr: "Rien n'a survécu." }, { en: "The land reshaped.", fr: "Terres retournées." }, { en: "Behold the ruins.", fr: "Contemplez les ruines." }],
      streak: [{ en: "Sparks. Nothing more.", fr: "Quelques étincelles." }, { en: "Scales don't scratch.", fr: "Mes écailles tiennent." }, { en: "Is that all?", fr: "C'est tout ?" }],
      compacted: [{ en: "Ash clears.", fr: "Suie envolée." }, { en: "Old fire, gone.", fr: "Vieux feu, éteint." }, { en: "Fresh embers.", fr: "Tisons prêts à mordre." }],
      retried: [{ en: "Fire, again.", fr: "Du feu, toujours." }, { en: "Once more, mortal.", fr: "Vous insistez ? Soit." }, { en: "Dragons persist.", fr: "Ma lignée persévère." }],
      todos_done: [{ en: "The hoard is whole.", fr: "Mon trésor est complet." }, { en: "All conquered.", fr: "Terres soumises." }, { en: "Nothing left. Good.", fr: "Il ne reste rien. Bien." }],
      evolved: [{ en: "Wings feel bigger.", fr: "Mes ailes ont forci." }, { en: "More fire in me.", fr: "J'ai plus de feu." }, { en: "Bow, if you like.", fr: "Inclinez-vous. Ou pas." }],
      hatched: [{ en: "A dragon. Behold.", fr: "Dragon. Enfin." }, { en: "Rare. As I should be.", fr: "Vous m'avez attendu." }, { en: "Smoke? Just me.", fr: "Des siècles. Puis vous." }],
      choice: [{ en: "Choose. I allow it.", fr: "Ce choix, je l'autorise." }, { en: "Two futures. Pick.", fr: "Voici deux avenirs." }, { en: "Decide, human.", fr: "J'attends, mortel." }],
    },
  },
];
