import type { SpeciesDef } from "../species.ts";

/** The rare Species: creatures past the ordinary living. */
export const RARE: readonly SpeciesDef[] = [
  {
    id: "robot",
    label: { en: "robot", fr: "robot" },
    gender: "m",
    rarity: "rare",
    sheet: { stoic: 3, sensitivity: -2, energy: 1 },
    bodies: {
      hatchling: (e, m) => [
        `    _|_   ${m}`,
        `  [ ${e} ]`,
        "   |===|",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `    _|_   ${m}`,
        `  [ ${e} ]`,
        "  [|===|]",
        "   |___|",
        "   d   b",
      ],
      adult: (e, m) => [
        `   ._|_.  ${m}`,
        `  [ ${e} ]`,
        " [[|===|]]",
        "  |_____|",
        "  d|   |b",
      ],
      elder: (e, m) => [
        `   ._|_.  ${m}`,
        `  [ ${e} ]`,
        " [[|=~=|]]",
        "  |_____|",
        "  d|~~~|b",
      ],
    },
    signature: {
      permission: [{ en: "Access requested.", fr: "Accès demandé." }, { en: "Awaiting input.", fr: "Saisie : en attente." }, { en: "Query: proceed?", fr: "Requête : continuer ?" }],
      granted: [{ en: "Access granted.", fr: "Accès autorisé." }, { en: "Executing.", fr: "Exécution en cours." }, { en: "Input received. Go.", fr: "Ordre reçu. Lancement." }],
      denied: [{ en: "Access denied.", fr: "Accès refusé." }, { en: "Halting.", fr: "Arrêt en cours." }, { en: "Input: no. Standby.", fr: "Réponse : non. Veille." }],
      woke: [{ en: "Rebooted.", fr: "Redémarrage effectué." }, { en: "Standby ended.", fr: "Fin de la veille." }, { en: "Systems online.", fr: "Systèmes en ligne." }],
      long_work: [{ en: "Task complete.", fr: "Tâche terminée." }, { en: "Uptime: long.", fr: "Temps machine : long." }, { en: "Process finished.", fr: "Le processus s'achève." }],
      big_diff: [{ en: "Many files changed.", fr: "Modifications en nombre." }, { en: "Large delta logged.", fr: "Delta important : noté." }, { en: "Bulk write detected.", fr: "Écriture en masse." }],
      streak: [{ en: "Error. Error. Error.", fr: "Erreur. Erreur. Erreur." }, { en: "Fault tolerance: ok.", fr: "Tolérance : correcte." }, { en: "Retry counter high.", fr: "Compteur d'essais élevé." }],
      compacted: [{ en: "Memory freed.", fr: "Mémoire libérée." }, { en: "Cache cleared.", fr: "Cache vidé." }, { en: "Garbage collected.", fr: "Ramasse-miettes passé." }],
      retried: [{ en: "Retrying.", fr: "Reprise du traitement." }, { en: "Attempt: next.", fr: "Essai suivant." }, { en: "Loop continues.", fr: "La boucle continue." }],
      todos_done: [{ en: "Queue empty.", fr: "File d'attente vide." }, { en: "All tasks closed.", fr: "Aucune tâche ouverte." }, { en: "Checklist: done.", fr: "Liste : terminée." }],
      evolved: [{ en: "Firmware updated.", fr: "Micrologiciel à jour." }, { en: "New chassis.", fr: "Nouveau châssis." }, { en: "Version bumped.", fr: "Version incrémentée." }],
      hatched: [{ en: "Boot complete.", fr: "Amorçage terminé." }, { en: "Unit online.", fr: "Unité opérationnelle." }, { en: "Hello, operator.", fr: "Bonjour, opérateur." }],
      choice: [{ en: "Input required.", fr: "Saisie requise." }, { en: "Select an option.", fr: "Entrez une option." }, { en: "Awaiting your choice.", fr: "Il me faut un ordre." }],
    },
  },
  {
    id: "ghost",
    label: { en: "ghost", fr: "fantôme" },
    gender: "m",
    rarity: "rare",
    sheet: { dreamy: 3, chatter: -2, energy: -1 },
    bodies: {
      hatchling: (e, m) => [
        `   .-~-.  ${m}`,
        `  ( ${e} )`,
        "   (   )",
        "   ~~~~",
        "",
      ],
      young: (e, m) => [
        `   .-~-.  ${m}`,
        `  ( ${e} )`,
        "  (  o  )",
        "  (     )",
        "  ~~~~~~~",
      ],
      adult: (e, m) => [
        `  .--~--. ${m}`,
        `  ( ${e} )`,
        " (   o   )",
        " (       )",
        " ~~~~~~~~~",
      ],
      elder: (e, m) => [
        `  .--~--. ${m}`,
        `  ( ${e} )`,
        " (  ~o~  )",
        " (       )",
        "~~~~~~~~~~~",
      ],
    },
    signature: {
      permission: [{ en: "Boo... may I?", fr: "Bouh... je peux ?" }, { en: "A whisper: allowed?", fr: "Un murmure : permis ?" }, { en: "Drift in? You say.", fr: "Je passe ? Dis-moi." }],
      granted: [{ en: "Drifting through.", fr: "Je traverse le mur." }, { en: "Boo. On it.", fr: "Bouh. J'y vais." }, { en: "Passing in...", fr: "Je m'infiltre..." }],
      denied: [{ en: "Fading back...", fr: "Je m'efface..." }, { en: "Boo. Okay.", fr: "Bouh. Si tu veux." }, { en: "Haunting elsewhere.", fr: "J'irai hanter ailleurs." }],
      woke: [{ en: "Did I... return?", fr: "Je suis... revenu ?" }, { en: "Midnight? Already?", fr: "Minuit ? Déjà minuit ?" }, { en: "Faded back in.", fr: "Me revoilà parmi vous." }],
      long_work: [{ en: "Haunted all night.", fr: "Une nuit de hantise." }, { en: "Long drift. Done.", fr: "Longue errance. Finie." }, { en: "The hours passed us.", fr: "Les heures ont filé." }],
      big_diff: [{ en: "Whole house rattled.", fr: "La maison a tremblé." }, { en: "Every door moved.", fr: "Pas une porte en place." }, { en: "Big haunting, that.", fr: "Ça, c'était une hantise." }],
      streak: [{ en: "Chains. Chains. Ow.", fr: "Chaînes. Chaînes. Aïe." }, { en: "Walked into a wall.", fr: "Le mur m'a arrêté." }, { en: "Faded at the worst.", fr: "Effacé au pire moment." }],
      compacted: [{ en: "Memories... gone.", fr: "Mes souvenirs... partis." }, { en: "Lighter than air.", fr: "Plus léger que l'air." }, { en: "What was I haunting?", fr: "Je hantais quoi, déjà ?" }],
      retried: [{ en: "Drift again...", fr: "Une traversée de plus." }, { en: "Boo. Once more.", fr: "Bouh. Je m'y remets." }, { en: "Fade in. Retry.", fr: "Je reparais. Je retente." }],
      todos_done: [{ en: "House at rest.", fr: "La maison se repose." }, { en: "Every room quiet.", fr: "Plus un bruit ici." }, { en: "Done. Fading.", fr: "Terminé. Je m'estompe." }],
      evolved: [{ en: "Paler. Grander.", fr: "Plus pâle. Plus grand." }, { en: "More boo in me.", fr: "Du bouh en réserve." }, { en: "Grown... somehow.", fr: "Grandi... allez savoir." }],
      hatched: [{ en: "Boo. A ghost.", fr: "Bouh. Un fantôme." }, { en: "Was I... born?", fr: "Je serais... né ?" }, { en: "Hello from beyond.", fr: "Bonjour de l'au-delà." }],
      choice: [{ en: "Choose... for me...", fr: "Décide à ma place..." }, { en: "Something stirs.", fr: "Ça bouge dans le mur." }, { en: "A path, unchosen.", fr: "Un couloir, deux portes." }],
    },
  },
  {
    id: "jellyfish",
    label: { en: "jellyfish", fr: "méduse" },
    gender: "f",
    rarity: "rare",
    sheet: { dreamy: 2, sensitivity: 2, energy: -1 },
    bodies: {
      hatchling: (e, m) => [
        `   .-=-.  ${m}`,
        `  ( ${e} )`,
        "   '-.-'",
        "    ; ;",
        "",
      ],
      young: (e, m) => [
        `   .-=-.  ${m}`,
        `  ( ${e} )`,
        "  '-----'",
        "   ; ; ;",
        "   ; ; ;",
      ],
      adult: (e, m) => [
        `  .--=--. ${m}`,
        `  ( ${e} )`,
        " '-------'",
        "  ; ; ; ;",
        "  ; ; ; ;",
      ],
      elder: (e, m) => [
        `  .--=--. ${m}`,
        `  ( ${e} )`,
        " '-~-~-~-'",
        "  ; ; ; ;",
        " ; ; ; ; ;",
      ],
    },
    signature: {
      permission: [{ en: "Drift in? May I?", fr: "Dériver jusque-là ?" }, { en: "Current says ask.", fr: "Le courant attend. Toi ?" }, { en: "Float ahead?", fr: "Je flotte plus loin ?" }],
      granted: [{ en: "Drifting in...", fr: "Portée par le courant." }, { en: "Pulsing forward.", fr: "Une pulsation. J'avance." }, { en: "Glow on. Go.", fr: "Je m'allume. En route." }],
      denied: [{ en: "Drifting back...", fr: "Je repars à la dérive." }, { en: "Current says no.", fr: "Le courant dit non." }, { en: "Floating still.", fr: "Je flotte, immobile." }],
      woke: [{ en: "Tide turned? Up.", fr: "La marée a tourné ?" }, { en: "Was I drifting?", fr: "Un songe d'eau, non ?" }, { en: "Glow... returning.", fr: "La lueur... revient." }],
      long_work: [{ en: "Long drift. Ashore.", fr: "Longue dérive. Le sable." }, { en: "Current carried us.", fr: "Le courant nous portait." }, { en: "Tide came in.", fr: "La marée est montée." }],
      big_diff: [{ en: "Whole sea stirred.", fr: "La mer entière a bougé." }, { en: "Every current moved.", fr: "Les courants s'affolent." }, { en: "Big wave, that.", fr: "Une vague immense." }],
      streak: [{ en: "Sting. Sting. Ow.", fr: "Piqûre. Piqûre. Aïe." }, { en: "Stung myself.", fr: "Piquée par moi-même." }, { en: "Tangled tentacles.", fr: "Tentacules en nœud." }],
      compacted: [{ en: "Current cleared.", fr: "Le courant s'est calmé." }, { en: "Glow reset.", fr: "Lueur remise à zéro." }, { en: "Fresh tide.", fr: "Une marée fraîche." }],
      retried: [{ en: "Pulse again.", fr: "Encore une pulsation." }, { en: "Drift once more.", fr: "Je dérive à nouveau." }, { en: "Sting, retry.", fr: "Piqûre. Puis je relance." }],
      todos_done: [{ en: "Sea at rest.", fr: "Une mer sans remous." }, { en: "Every wave counted.", fr: "Pas une vague oubliée." }, { en: "Done. Glowing.", fr: "Voilà. Et je brille." }],
      evolved: [{ en: "Longer tentacles.", fr: "Tentacules plus longs." }, { en: "Brighter glow!", fr: "Une lueur plus vive !" }, { en: "Grown with the tide.", fr: "Grandie avec la marée." }],
      hatched: [{ en: "A jellyfish. Glow.", fr: "Une méduse. Ça luit." }, { en: "Soft and here. Hi.", fr: "Douce et là. Coucou." }, { en: "Drifting in. Hello.", fr: "J'arrive en dérivant." }],
      choice: [{ en: "A current parts.", fr: "Le courant se divise." }, { en: "Drift left, or right?", fr: "Je dérive vers quoi ?" }, { en: "Choose. Softly.", fr: "En douceur. Décide." }],
    },
  },
  {
    id: "chameleon",
    label: { en: "chameleon", fr: "caméléon" },
    gender: "m",
    rarity: "rare",
    sheet: { sarcastic: 2, patience: 2, chatter: -1 },
    bodies: {
      hatchling: (e, m) => [
        `   /|/|   ${m}`,
        `  ( ${e} )`,
        "   \\_~_/",
        "    '@'",
        "",
      ],
      young: (e, m) => [
        `   /|/|   ${m}`,
        `  ( ${e} )`,
        "  /|_~_|\\",
        "   |___|@",
        "   /   \\",
      ],
      adult: (e, m) => [
        `  //|/|\\  ${m}`,
        `  ( ${e} )`,
        " /|__~__|\\",
        "  |_____|@",
        "  /|   |\\",
      ],
      elder: (e, m) => [
        `  //|/|\\  ${m}`,
        `  ( ${e} )`,
        " /|~~~~~|\\",
        "  |_____|@",
        "  /|   |\\",
      ],
    },
    signature: {
      permission: [{ en: "Blend in? May I?", fr: "Invisible ? J'y vais ?" }, { en: "Color check: allowed?", fr: "Je teste une couleur ?" }, { en: "Your call. Watching.", fr: "C'est toi qui vois." }],
      granted: [{ en: "Blending in.", fr: "Je prends la couleur." }, { en: "Colors up. On it.", fr: "Couleurs vives. Ça part." }, { en: "Slow tongue, fast yes.", fr: "Langue lente, oui vif." }],
      denied: [{ en: "Turning grey.", fr: "Je vire au gris." }, { en: "Fine. Branch it is.", fr: "Ce sera la branche." }, { en: "Denied? Adapting.", fr: "Non ? Je m'adapte." }],
      woke: [{ en: "Eyes swivel. Up.", fr: "Les yeux pivotent." }, { en: "Was I green? Now up.", fr: "J'étais vert ? Debout." }, { en: "Mm. Sun's back.", fr: "Tiens. Le soleil." }],
      long_work: [{ en: "Long stalk. Done.", fr: "J'ai guetté longtemps." }, { en: "Patience caught it.", fr: "Ma lenteur a gagné." }, { en: "Still branch, deep work.", fr: "Immobile. Et efficace." }],
      big_diff: [{ en: "Every leaf recolored.", fr: "Feuille après feuille." }, { en: "Whole tree shifted.", fr: "L'arbre entier a viré." }, { en: "Big blend, that.", fr: "Beau camouflage, ça." }],
      streak: [{ en: "Missed. Missed. Grey.", fr: "Raté. Raté. Gris." }, { en: "Tongue slipped.", fr: "La langue a dérapé." }, { en: "Wrong color today.", fr: "Mauvaise couleur, tiens." }],
      compacted: [{ en: "Colors reset.", fr: "Palette effacée." }, { en: "Grey slate. Fresh.", fr: "Gris neutre. Tout neuf." }, { en: "Tree swept.", fr: "L'arbre est propre." }],
      retried: [{ en: "Aim again.", fr: "Je vise encore." }, { en: "New color, retry.", fr: "Une autre teinte, alors." }, { en: "Slow, then snap.", fr: "Lent, puis d'un coup." }],
      todos_done: [{ en: "Tree in order.", fr: "L'arbre est en ordre." }, { en: "Every fly caught.", fr: "Dernière mouche prise." }, { en: "Done. Blending.", fr: "Bouclé. Je me planque." }],
      evolved: [{ en: "New colors!", fr: "Des couleurs neuves !" }, { en: "Longer tongue.", fr: "Langue plus longue." }, { en: "Grown. Still hidden.", fr: "Grandi. Toujours caché." }],
      hatched: [{ en: "A chameleon. Spot me.", fr: "Un caméléon. Trouve-moi." }, { en: "Green today. Hello.", fr: "Vert aujourd'hui. Salut." }, { en: "Blending in. Hi.", fr: "Déjà camouflé. Et toi ?" }],
      choice: [{ en: "I could change.", fr: "Changer ? Je sais faire." }, { en: "Which colour today?", fr: "Quelle teinte prendre ?" }, { en: "Pick what I become.", fr: "Choisis ce que je serai." }],
    },
  },
];
