import type { SpeciesDef } from "../species.ts";

/** The rare Species: creatures past the ordinary living. */
export const RARE: readonly SpeciesDef[] = [
  {
    id: "robot",
    label: { en: "robot", fr: "robot" },
    gender: "m",
    rarity: "rare",
    sheet: { stoic: 3, sensitivity: -2, energy: 1 },
    maps: {
      hatchling: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          "..........o..........",
          "..........c..........",
          "......ooooooooo......",
          "......obbbbbbbo......",
          "......obbbbbbbo......",
          "......obbbbbbbo......",
          "......oaaaaaaao......",
          "....oaaaaaaaaaaao....",
          "....oaaacaaacaaao....",
          "....oaaaaaaaaaaao....",
          ".....obbbbbbbbbo.....",
          "......obbbbbbbo......",
          "......o.......o......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 7, y: 6, w: 3, h: 3 }, { x: 11, y: 6, w: 3, h: 3 }],
      },
      young: {
        pixels: [
          ".....................",
          "..........c..........",
          "..........o..........",
          "......ooooooooo......",
          "......obbbbbbbo......",
          "......obbbbbbbo......",
          "......oaaacaaao......",
          "........ooooo........",
          "....oaaaaaaaaaaao....",
          "..bboaaaaaaaaaaaobb..",
          "....oaaacaaacaaao....",
          "....oaaaaaaaaaaao....",
          ".....obbbbbbbbbo.....",
          ".....obbbbbbbbbo.....",
          "......obbbbbbbo......",
          "......o.......o......",
          "......o.......o......",
          "......oo.....oo......",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 7, y: 4, w: 3, h: 3 }, { x: 11, y: 4, w: 3, h: 3 }],
      },
      adult: {
        pixels: [
          "..........c..........",
          "..........o..........",
          ".....ooooooooooo.....",
          ".....obbbbbbbbbo.....",
          ".....obbbbbbbbbo.....",
          ".....oaaaaaaaaao.....",
          ".......ooooooo.......",
          "..oaaaaaaaaaaaaaao...",
          "..bboaaaaaaaaaaaobb..",
          "..oaaaaaaaaaaaaaao...",
          "..oaaacaaacaaacaaao..",
          "..oaaaaaaaaaaaaaao...",
          "...obbbbbbbbbbbbbo...",
          "....obbbbbbbbbbbo....",
          "......ooo...ooo......",
          "......obo...obo......",
          "......obo...obo......",
          "......ooo...ooo......",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 7, y: 3, w: 3, h: 3 }, { x: 11, y: 3, w: 3, h: 3 }],
      },
      elder: {
        pixels: [
          "........ccc..........",
          "..........o..........",
          ".....ooooooooooo.....",
          ".....obbbbbbbbbo.....",
          ".....obbbbbbbbbo.....",
          ".....oaacaacaaao.....",
          ".......ooooooo.......",
          "..oaaaaaaaaaaaaaao...",
          "..bboaaaaaaaaaaaobb..",
          "..oaaaaaaaaaaaaaao...",
          "..oaaacaaacaaacaaao..",
          "..oaaaaaaaaaaaaaao...",
          "...ocbcbcbcbcbcbco...",
          "....obbbbbbbbbbbo....",
          "......ooo...ooo......",
          "......obo...obo......",
          "......oco...oco......",
          "......ooo...ooo......",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 7, y: 3, w: 3, h: 3 }, { x: 11, y: 3, w: 3, h: 3 }],
      },
    },
    palettes: {
      dark: { outline: "#1c2126", primary: "#8b96a3", secondary: "#c9d3da", accent: "#3ad6c9", eye: "#12100e" },
      light: { outline: "#2b3138", primary: "#6d7986", secondary: "#aab5bd", accent: "#1c8f85", eye: "#181310" },
    },
    signature: {
      permission: [{ en: "Access requested.", fr: "Accès demandé." }, { en: "Awaiting input.", fr: "Saisie : en attente." }, { en: "Query: proceed?", fr: "Requête : continuer ?" }],
      granted: [{ en: "Access granted.", fr: "Accès autorisé." }, { en: "Executing.", fr: "Exécution en cours." }, { en: "Input received. Go.", fr: "Ordre reçu. Lancement." }],
      denied: [{ en: "Access denied.", fr: "Accès refusé." }, { en: "Halting.", fr: "Arrêt en cours." }, { en: "Input: no. Standby.", fr: "Réponse : non. Veille." }],
      woke: [{ en: "Rebooted.", fr: "Redémarrage effectué." }, { en: "Standby ended.", fr: "Fin de la veille." }, { en: "Systems online.", fr: "Systèmes en ligne." }],
      long_work: [{ en: "Task complete.", fr: "Tâche terminée." }, { en: "Uptime: long.", fr: "Temps machine : long." }, { en: "Process finished.", fr: "Le processus s'achève." }],
      big_diff: [{ en: "Many files changed.", fr: "Modifications en nombre." }, { en: "Large delta logged.", fr: "Delta important : noté." }, { en: "Bulk write detected.", fr: "Écriture en masse." }],
      streak: [{ en: "Error. Error. Error.", fr: "Erreur. Erreur. Erreur." }, { en: "Fault tolerance: ok.", fr: "Tolérance : correcte." }, { en: "Retry counter high.", fr: "Compteur d'essais élevé." }],
      compacted: [{ en: "Memory freed.", fr: "Mémoire libérée." }, { en: "Cache cleared.", fr: "Cache vidé." }, { en: "Garbage collected.", fr: "Ramasse-miettes passé." }],
      retried: [{ en: "Retrying.", fr: "Reprise du traitement." }, { en: "Attempt: next.", fr: "Essai suivant." }, { en: "Loop continues.", fr: "La boucle continue." }],
      todos_done: [{ en: "Queue empty.", fr: "File d'attente vide." }, { en: "All tasks closed.", fr: "Aucune tâche ouverte." }, { en: "Checklist: done.", fr: "Liste : terminée." }],
      evolved: [{ en: "Firmware updated.", fr: "Micrologiciel à jour." }, { en: "New chassis.", fr: "Nouveau châssis." }, { en: "Version bumped.", fr: "Version incrémentée." }],
      hatched: [{ en: "Boot complete.", fr: "Amorçage terminé." }, { en: "Unit online.", fr: "Unité opérationnelle." }, { en: "Hello, operator.", fr: "Bonjour, opérateur." }],
      choice: [{ en: "Input required.", fr: "Saisie requise." }, { en: "Select an option.", fr: "Entrez une option." }, { en: "Awaiting your choice.", fr: "Il me faut un ordre." }],
    },
  },
  {
    id: "ghost",
    label: { en: "ghost", fr: "fantôme" },
    gender: "m",
    rarity: "rare",
    sheet: { dreamy: 3, chatter: -2, energy: -1 },
    maps: {
      hatchling: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          ".........ooo.........",
          "........oaaao........",
          ".......oaaaaao.......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          ".......aaaaaaa.......",
          "........aa.aa........",
          "........b...b........",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 8, y: 6, w: 3, h: 3 }, { x: 11, y: 6, w: 3, h: 3 }],
      },
      young: {
        pixels: [
          ".....................",
          ".....................",
          "........ooooo........",
          ".......oaaaaao.......",
          "......oaaaaaaao......",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaao.....",
          "......aaaaaaaaa......",
          "......aa.aaa.aa......",
          "......b...b...b......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 7, y: 5, w: 3, h: 3 }, { x: 11, y: 5, w: 3, h: 3 }],
      },
      adult: {
        pixels: [
          ".....................",
          ".......ooooooo.......",
          "......oaaaaaaao......",
          ".....oaaaaaaaaao.....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....aaaaaaaaaaaaa....",
          "....aa.aa.a.aa.aa....",
          "....b...b.b.b...b....",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 4, w: 3, h: 3 }, { x: 12, y: 4, w: 3, h: 3 }],
        motion: { tail: { x: 9, y: 13, w: 3, h: 2 } },
      },
      elder: {
        pixels: [
          "........ccccc........",
          ".......ooooooo.......",
          "......oaaaaaaao......",
          ".....oaaaaaaaaao.....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "...aaaaaaaaaaaaaaa...",
          "...aa.aa.a.a.aa.aa.a.",
          "....b...b...b...b..b.",
          "......c...c...c......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 4, w: 3, h: 3 }, { x: 12, y: 4, w: 3, h: 3 }],
        motion: { tail: { x: 18, y: 13, w: 3, h: 2 } },
      },
    },
    palettes: {
      dark: { outline: "#cfc9de", primary: "#e8e6f0", secondary: "#c9c6d9", accent: "#a8c9e8", eye: "#3a3550" },
      light: { outline: "#a89fc2", primary: "#c9c4dc", secondary: "#a8a3bf", accent: "#7fa3cc", eye: "#2b2740" },
    },
    signature: {
      permission: [{ en: "Boo... may I?", fr: "Bouh... je peux ?" }, { en: "A whisper: allowed?", fr: "Un murmure : permis ?" }, { en: "Drift in? You say.", fr: "Je passe ? Dis-moi." }],
      granted: [{ en: "Drifting through.", fr: "Je traverse le mur." }, { en: "Boo. On it.", fr: "Bouh. J'y vais." }, { en: "Passing in...", fr: "Je m'infiltre..." }],
      denied: [{ en: "Fading back...", fr: "Je m'efface..." }, { en: "Boo. Okay.", fr: "Bouh. Si tu veux." }, { en: "Haunting elsewhere.", fr: "J'irai hanter ailleurs." }],
      woke: [{ en: "Did I... return?", fr: "Je suis... revenu ?" }, { en: "Midnight? Already?", fr: "Minuit ? Déjà minuit ?" }, { en: "Faded back in.", fr: "Me revoilà parmi vous." }],
      long_work: [{ en: "Haunted all night.", fr: "Une nuit de hantise." }, { en: "Long drift. Done.", fr: "Longue errance. Finie." }, { en: "The hours passed us.", fr: "Les heures ont filé." }],
      big_diff: [{ en: "Whole house rattled.", fr: "La maison a tremblé." }, { en: "Every door moved.", fr: "Pas une porte en place." }, { en: "Big haunting, that.", fr: "Ça, c'était une hantise." }],
      streak: [{ en: "Chains. Chains. Ow.", fr: "Chaînes. Chaînes. Aïe." }, { en: "Walked into a wall.", fr: "Le mur m'a arrêté." }, { en: "Faded at the worst.", fr: "Effacé au pire moment." }],
      compacted: [{ en: "Memories... gone.", fr: "Mes souvenirs... partis." }, { en: "Lighter than air.", fr: "Plus léger que l'air." }, { en: "What was I haunting?", fr: "Je hantais quoi, déjà ?" }],
      retried: [{ en: "Drift again...", fr: "Une traversée de plus." }, { en: "Boo. Once more.", fr: "Bouh. Je m'y remets." }, { en: "Fade in. Retry.", fr: "Je reparais. Je retente." }],
      todos_done: [{ en: "House at rest.", fr: "La maison se repose." }, { en: "Every room quiet.", fr: "Plus un bruit ici." }, { en: "Done. Fading.", fr: "Terminé. Je m'estompe." }],
      evolved: [{ en: "Paler. Grander.", fr: "Plus pâle. Plus grand." }, { en: "More boo in me.", fr: "Du bouh en réserve." }, { en: "Grown... somehow.", fr: "Grandi... allez savoir." }],
      hatched: [{ en: "Boo. A ghost.", fr: "Bouh. Un fantôme." }, { en: "Was I... born?", fr: "Je serais... né ?" }, { en: "Hello from beyond.", fr: "Bonjour de l'au-delà." }],
      choice: [{ en: "Choose... for me...", fr: "Décide à ma place..." }, { en: "Something stirs.", fr: "Ça bouge dans le mur." }, { en: "A path, unchosen.", fr: "Un couloir, deux portes." }],
    },
  },
  {
    id: "jellyfish",
    label: { en: "jellyfish", fr: "méduse" },
    gender: "f",
    rarity: "rare",
    sheet: { dreamy: 2, sensitivity: 2, energy: -1 },
    maps: {
      hatchling: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".........ooo.........",
          "........oaaao........",
          ".......oaaaaao.......",
          ".......oaaaaao.......",
          ".......oaaaaao.......",
          ".......oaaaaao.......",
          "........bbbbb........",
          "........b.c.b........",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 8, y: 6, w: 3, h: 3 }, { x: 11, y: 6, w: 3, h: 3 }],
      },
      young: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          "........ooooo........",
          ".......oaaaaao.......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          ".......bbbbbbb.......",
          ".......b.c.c.b.......",
          ".......b.c.c.b.......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 7, y: 5, w: 3, h: 3 }, { x: 11, y: 5, w: 3, h: 3 }],
      },
      adult: {
        pixels: [
          ".....................",
          ".......ooooooo.......",
          "......oaaaaaaao......",
          ".....oaaaaaaaaao.....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          ".....bbbbbbbbbbb.....",
          ".....b.c.b.b.c.b.....",
          ".....b.c.b.b.c.b.....",
          ".....b.c.b.b.c.b.....",
          ".........b.b.........",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 4, w: 3, h: 3 }, { x: 12, y: 4, w: 3, h: 3 }],
        motion: { ears: [{ x: 7, y: 12, w: 2, h: 3 }, { x: 11, y: 12, w: 2, h: 3 }] },
      },
      elder: {
        pixels: [
          ".....................",
          ".......ooooooo.......",
          "......oaaaaaaao......",
          ".....oaaaaaaaaao.....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....bbbbbbbbbbbbb....",
          "....b.c.b.c.b.c.b....",
          "....b.c.b.c.b.c.b....",
          "....b.c.b.c.b.c.b....",
          "....b.c.b.c.b.c.b....",
          "..........c..........",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 4, w: 3, h: 3 }, { x: 12, y: 4, w: 3, h: 3 }],
        motion: { ears: [{ x: 6, y: 12, w: 2, h: 4 }, { x: 12, y: 12, w: 2, h: 4 }] },
      },
    },
    palettes: {
      dark: { outline: "#a8d8e0", primary: "#c8ecf2", secondary: "#e8f7fa", accent: "#e85a9e", eye: "#1f3a3d" },
      light: { outline: "#7ab8c4", primary: "#a3d9e3", secondary: "#cceaf0", accent: "#c23d80", eye: "#152a2c" },
    },
    signature: {
      permission: [{ en: "Drift in? May I?", fr: "Dériver jusque-là ?" }, { en: "Current says ask.", fr: "Le courant attend. Toi ?" }, { en: "Float ahead?", fr: "Je flotte plus loin ?" }],
      granted: [{ en: "Drifting in...", fr: "Portée par le courant." }, { en: "Pulsing forward.", fr: "Une pulsation. J'avance." }, { en: "Glow on. Go.", fr: "Je m'allume. En route." }],
      denied: [{ en: "Drifting back...", fr: "Je repars à la dérive." }, { en: "Current says no.", fr: "Le courant dit non." }, { en: "Floating still.", fr: "Je flotte, immobile." }],
      woke: [{ en: "Tide turned? Up.", fr: "La marée a tourné ?" }, { en: "Was I drifting?", fr: "Un songe d'eau, non ?" }, { en: "Glow... returning.", fr: "La lueur... revient." }],
      long_work: [{ en: "Long drift. Ashore.", fr: "Longue dérive. Le sable." }, { en: "Current carried us.", fr: "Le courant nous portait." }, { en: "Tide came in.", fr: "La marée est montée." }],
      big_diff: [{ en: "Whole sea stirred.", fr: "La mer entière a bougé." }, { en: "Every current moved.", fr: "Les courants s'affolent." }, { en: "Big wave, that.", fr: "Une vague immense." }],
      streak: [{ en: "Sting. Sting. Ow.", fr: "Piqûre. Piqûre. Aïe." }, { en: "Stung myself.", fr: "Piquée par moi-même." }, { en: "Tangled tentacles.", fr: "Tentacules en nœud." }],
      compacted: [{ en: "Current cleared.", fr: "Le courant s'est calmé." }, { en: "Glow reset.", fr: "Lueur remise à zéro." }, { en: "Fresh tide.", fr: "Une marée fraîche." }],
      retried: [{ en: "Pulse again.", fr: "Encore une pulsation." }, { en: "Drift once more.", fr: "Je dérive à nouveau." }, { en: "Sting, retry.", fr: "Piqûre. Puis je relance." }],
      todos_done: [{ en: "Sea at rest.", fr: "Une mer sans remous." }, { en: "Every wave counted.", fr: "Pas une vague oubliée." }, { en: "Done. Glowing.", fr: "Voilà. Et je brille." }],
      evolved: [{ en: "Longer tentacles.", fr: "Tentacules plus longs." }, { en: "Brighter glow!", fr: "Une lueur plus vive !" }, { en: "Grown with the tide.", fr: "Grandie avec la marée." }],
      hatched: [{ en: "A jellyfish. Glow.", fr: "Une méduse. Ça luit." }, { en: "Soft and here. Hi.", fr: "Douce et là. Coucou." }, { en: "Drifting in. Hello.", fr: "J'arrive en dérivant." }],
      choice: [{ en: "A current parts.", fr: "Le courant se divise." }, { en: "Drift left, or right?", fr: "Je dérive vers quoi ?" }, { en: "Choose. Softly.", fr: "En douceur. Décide." }],
    },
  },
  {
    id: "chameleon",
    label: { en: "chameleon", fr: "caméléon" },
    gender: "m",
    rarity: "rare",
    sheet: { sarcastic: 2, patience: 2, chatter: -1 },
    maps: {
      hatchling: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          "........o.o.o........",
          ".......ooooooo.......",
          "......oaaaaaaao......",
          "......oaaaaaaao......",
          "......oaacaaaao......",
          "......oaaaaaaao......",
          ".......ooooooo.a.....",
          "........o...o.aa.....",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 7, y: 7, w: 3, h: 3 }, { x: 11, y: 7, w: 3, h: 3 }],
      },
      young: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          ".......o.o.o.o.......",
          "......ooooooooo......",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaao.....",
          ".....oaacaaaaaao.....",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaacaao.....",
          ".....oaaaaaaaaao.....",
          "......oooooooooaaa...",
          ".......o.....o..aa...",
          ".......o.....o..a....",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 6, w: 3, h: 3 }, { x: 11, y: 6, w: 3, h: 3 }],
      },
      adult: {
        pixels: [
          ".....................",
          ".....................",
          "......o.o.o.o.o......",
          ".....ooooooooooo.....",
          "....oaaaaaaaaaaao....",
          "...oaaaaaaaaaaaaao...",
          "...oaaacaaaaacaaao...",
          "...oaaaaaaaaaaaaao...",
          "...oaaaaaaaaaaaaao...",
          "...oaabaacaaaaaaao...",
          "...oaaaaaaaaaaaaaoaa.",
          "...oooooooooooooooa..",
          ".....oo......oo...a..",
          ".....aa......aa..aa..",
          ".....oo......oo......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 5, y: 5, w: 3, h: 3 }, { x: 11, y: 5, w: 3, h: 3 }],
        motion: { tail: { x: 17, y: 12, w: 3, h: 1 } },
      },
      elder: {
        pixels: [
          ".....................",
          ".....................",
          "......o.c.o.c.o......",
          ".....ooooooooooo.....",
          "....oaaaaaaaaaaao....",
          "...oaaaaaaaaaaaaao...",
          "...oaaacaaaaacaaao...",
          "...oaaaaaaaaaaaaao...",
          "...oaaaaaaaaaaaaao...",
          "...oaabaacaaaabaaoaa.",
          "...oaaaaaaaaaaaaaoaa.",
          "...oooooooooooooooa..",
          ".....oo......oo...a..",
          ".....aa......aa...a..",
          ".....oo......oo..aa..",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 5, y: 5, w: 3, h: 3 }, { x: 11, y: 5, w: 3, h: 3 }],
        motion: { tail: { x: 17, y: 12, w: 3, h: 2 } },
      },
    },
    palettes: {
      dark: { outline: "#16261f", primary: "#2f8f7a", secondary: "#bfe8d9", accent: "#a13fa1", eye: "#0d1a15" },
      light: { outline: "#0f1a15", primary: "#256b5c", secondary: "#9fd4c2", accent: "#7a2f7a", eye: "#0a140f" },
    },
    signature: {
      permission: [{ en: "Blend in? May I?", fr: "Invisible ? J'y vais ?" }, { en: "Color check: allowed?", fr: "Je teste une couleur ?" }, { en: "Your call. Watching.", fr: "C'est toi qui vois." }],
      granted: [{ en: "Blending in.", fr: "Je prends la couleur." }, { en: "Colors up. On it.", fr: "Couleurs vives. Ça part." }, { en: "Slow tongue, fast yes.", fr: "Langue lente, oui vif." }],
      denied: [{ en: "Turning grey.", fr: "Je vire au gris." }, { en: "Fine. Branch it is.", fr: "Ce sera la branche." }, { en: "Denied? Adapting.", fr: "Non ? Je m'adapte." }],
      woke: [{ en: "Eyes swivel. Up.", fr: "Les yeux pivotent." }, { en: "Was I green? Now up.", fr: "J'étais vert ? Debout." }, { en: "Mm. Sun's back.", fr: "Tiens. Le soleil." }],
      long_work: [{ en: "Long stalk. Done.", fr: "J'ai guetté longtemps." }, { en: "Patience caught it.", fr: "Ma lenteur a gagné." }, { en: "Still branch, deep work.", fr: "Immobile. Et efficace." }],
      big_diff: [{ en: "Every leaf recolored.", fr: "Feuille après feuille." }, { en: "Whole tree shifted.", fr: "L'arbre entier a viré." }, { en: "Big blend, that.", fr: "Beau camouflage, ça." }],
      streak: [{ en: "Missed. Missed. Grey.", fr: "Raté. Raté. Gris." }, { en: "Tongue slipped.", fr: "La langue a dérapé." }, { en: "Wrong color today.", fr: "Mauvaise couleur, tiens." }],
      compacted: [{ en: "Colors reset.", fr: "Palette effacée." }, { en: "Grey slate. Fresh.", fr: "Gris neutre. Tout neuf." }, { en: "Tree swept.", fr: "L'arbre est propre." }],
      retried: [{ en: "Aim again.", fr: "Je vise encore." }, { en: "New color, retry.", fr: "Une autre teinte, alors." }, { en: "Slow, then snap.", fr: "Lent, puis d'un coup." }],
      todos_done: [{ en: "Tree in order.", fr: "L'arbre est en ordre." }, { en: "Every fly caught.", fr: "Dernière mouche prise." }, { en: "Done. Blending.", fr: "Bouclé. Je me planque." }],
      evolved: [{ en: "New colors!", fr: "Des couleurs neuves !" }, { en: "Longer tongue.", fr: "Langue plus longue." }, { en: "Grown. Still hidden.", fr: "Grandi. Toujours caché." }],
      hatched: [{ en: "A chameleon. Spot me.", fr: "Un caméléon. Trouve-moi." }, { en: "Green today. Hello.", fr: "Vert aujourd'hui. Salut." }, { en: "Blending in. Hi.", fr: "Déjà camouflé. Et toi ?" }],
      choice: [{ en: "I could change.", fr: "Changer ? Je sais faire." }, { en: "Which colour today?", fr: "Quelle teinte prendre ?" }, { en: "Pick what I become.", fr: "Choisis ce que je serai." }],
    },
  },
];
