import type { SpeciesDef } from "../species.ts";

/** The rare Species: creatures past the ordinary living. */
export const RARE: readonly SpeciesDef[] = [
  {
    id: "robot",
    label: { en: "robot" },
    rarity: "rare",
    sheet: { stoic: 3, sensitivity: -2, energy: 1 },
    bodies: {
      hatchling: (e, m) => [
        `    _|_   ${m}`,
        `  [ ${e} ]`,
        "   |===|",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `    _|_   ${m}`,
        `  [ ${e} ]`,
        "  [|===|]",
        "   |___|",
        "   d   b",
      ],
      adult: (e, m) => [
        `   ._|_.  ${m}`,
        `  [ ${e} ]`,
        " [[|===|]]",
        "  |_____|",
        "  d|   |b",
      ],
      elder: (e, m) => [
        `   ._|_.  ${m}`,
        `  [ ${e} ]`,
        " [[|=~=|]]",
        "  |_____|",
        "  d|~~~|b",
      ],
    },
    signature: {
      permission: [{ en: "Access requested." }, { en: "Awaiting input." }, { en: "Query: proceed?" }],
      granted: [{ en: "Access granted." }, { en: "Executing." }, { en: "Input received. Go." }],
      denied: [{ en: "Access denied." }, { en: "Halting." }, { en: "Input: no. Standby." }],
      woke: [{ en: "Rebooted." }, { en: "Standby ended." }, { en: "Systems online." }],
      long_work: [{ en: "Task complete." }, { en: "Uptime: long." }, { en: "Process finished." }],
      big_diff: [{ en: "Many files changed." }, { en: "Large delta logged." }, { en: "Bulk write detected." }],
      streak: [{ en: "Error. Error. Error." }, { en: "Fault tolerance: ok." }, { en: "Retry counter high." }],
      compacted: [{ en: "Memory freed." }, { en: "Cache cleared." }, { en: "Garbage collected." }],
      retried: [{ en: "Retrying." }, { en: "Attempt: next." }, { en: "Loop continues." }],
      todos_done: [{ en: "Queue empty." }, { en: "All tasks closed." }, { en: "Checklist: done." }],
      evolved: [{ en: "Firmware updated." }, { en: "New chassis." }, { en: "Version bumped." }],
      hatched: [{ en: "Boot complete." }, { en: "Unit online." }, { en: "Hello, operator." }],
      choice: [{ en: "Input required." }, { en: "Select an option." }, { en: "Awaiting your choice." }],
    },
  },
  {
    id: "ghost",
    label: { en: "ghost" },
    rarity: "rare",
    sheet: { dreamy: 3, chatter: -2, energy: -1 },
    bodies: {
      hatchling: (e, m) => [
        `   .-~-.  ${m}`,
        `  ( ${e} )`,
        "   (   )",
        "   ~~~~",
        "",
      ],
      young: (e, m) => [
        `   .-~-.  ${m}`,
        `  ( ${e} )`,
        "  (  o  )",
        "  (     )",
        "  ~~~~~~~",
      ],
      adult: (e, m) => [
        `  .--~--. ${m}`,
        `  ( ${e} )`,
        " (   o   )",
        " (       )",
        " ~~~~~~~~~",
      ],
      elder: (e, m) => [
        `  .--~--. ${m}`,
        `  ( ${e} )`,
        " (  ~o~  )",
        " (       )",
        "~~~~~~~~~~~",
      ],
    },
    signature: {
      permission: [{ en: "Boo... may I?" }, { en: "A whisper: allowed?" }, { en: "Drift in? You say." }],
      granted: [{ en: "Drifting through." }, { en: "Boo. On it." }, { en: "Passing in..." }],
      denied: [{ en: "Fading back..." }, { en: "Boo. Okay." }, { en: "Haunting elsewhere." }],
      woke: [{ en: "Did I... return?" }, { en: "Midnight? Already?" }, { en: "Faded back in." }],
      long_work: [{ en: "Haunted all night." }, { en: "Long drift. Done." }, { en: "The hours passed us." }],
      big_diff: [{ en: "Whole house rattled." }, { en: "Every door moved." }, { en: "Big haunting, that." }],
      streak: [{ en: "Chains. Chains. Ow." }, { en: "Walked into a wall." }, { en: "Faded at the worst." }],
      compacted: [{ en: "Memories... gone." }, { en: "Lighter than air." }, { en: "What was I haunting?" }],
      retried: [{ en: "Drift again..." }, { en: "Boo. Once more." }, { en: "Fade in. Retry." }],
      todos_done: [{ en: "House at rest." }, { en: "Every room quiet." }, { en: "Done. Fading." }],
      evolved: [{ en: "Paler. Grander." }, { en: "More boo in me." }, { en: "Grown... somehow." }],
      hatched: [{ en: "Boo. A ghost." }, { en: "Was I... born?" }, { en: "Hello from beyond." }],
      choice: [{ en: "Choose... for me..." }, { en: "Something stirs." }, { en: "A path, unchosen." }],
    },
  },
  {
    id: "jellyfish",
    label: { en: "jellyfish" },
    rarity: "rare",
    sheet: { dreamy: 2, sensitivity: 2, energy: -1 },
    bodies: {
      hatchling: (e, m) => [
        `   .-=-.  ${m}`,
        `  ( ${e} )`,
        "   '-.-'",
        "    ; ;",
        "",
      ],
      young: (e, m) => [
        `   .-=-.  ${m}`,
        `  ( ${e} )`,
        "  '-----'",
        "   ; ; ;",
        "   ; ; ;",
      ],
      adult: (e, m) => [
        `  .--=--. ${m}`,
        `  ( ${e} )`,
        " '-------'",
        "  ; ; ; ;",
        "  ; ; ; ;",
      ],
      elder: (e, m) => [
        `  .--=--. ${m}`,
        `  ( ${e} )`,
        " '-~-~-~-'",
        "  ; ; ; ;",
        " ; ; ; ; ;",
      ],
    },
    signature: {
      permission: [{ en: "Drift in? May I?" }, { en: "Current says ask." }, { en: "Float ahead?" }],
      granted: [{ en: "Drifting in..." }, { en: "Pulsing forward." }, { en: "Glow on. Go." }],
      denied: [{ en: "Drifting back..." }, { en: "Current says no." }, { en: "Floating still." }],
      woke: [{ en: "Tide turned? Up." }, { en: "Was I drifting?" }, { en: "Glow... returning." }],
      long_work: [{ en: "Long drift. Ashore." }, { en: "Current carried us." }, { en: "Tide came in." }],
      big_diff: [{ en: "Whole sea stirred." }, { en: "Every current moved." }, { en: "Big wave, that." }],
      streak: [{ en: "Sting. Sting. Ow." }, { en: "Stung myself." }, { en: "Tangled tentacles." }],
      compacted: [{ en: "Current cleared." }, { en: "Glow reset." }, { en: "Fresh tide." }],
      retried: [{ en: "Pulse again." }, { en: "Drift once more." }, { en: "Sting, retry." }],
      todos_done: [{ en: "Sea at rest." }, { en: "Every wave counted." }, { en: "Done. Glowing." }],
      evolved: [{ en: "Longer tentacles." }, { en: "Brighter glow!" }, { en: "Grown with the tide." }],
      hatched: [{ en: "A jellyfish. Glow." }, { en: "Soft and here. Hi." }, { en: "Drifting in. Hello." }],
      choice: [{ en: "A current parts." }, { en: "Drift left, or right?" }, { en: "Choose. Softly." }],
    },
  },
  {
    id: "chameleon",
    label: { en: "chameleon" },
    rarity: "rare",
    sheet: { sarcastic: 2, patience: 2, chatter: -1 },
    bodies: {
      hatchling: (e, m) => [
        `   /|/|   ${m}`,
        `  ( ${e} )`,
        "   \\_~_/",
        "    '@'",
        "",
      ],
      young: (e, m) => [
        `   /|/|   ${m}`,
        `  ( ${e} )`,
        "  /|_~_|\\",
        "   |___|@",
        "   /   \\",
      ],
      adult: (e, m) => [
        `  //|/|\\  ${m}`,
        `  ( ${e} )`,
        " /|__~__|\\",
        "  |_____|@",
        "  /|   |\\",
      ],
      elder: (e, m) => [
        `  //|/|\\  ${m}`,
        `  ( ${e} )`,
        " /|~~~~~|\\",
        "  |_____|@",
        "  /|   |\\",
      ],
    },
    signature: {
      permission: [{ en: "Blend in? May I?" }, { en: "Color check: allowed?" }, { en: "Your call. Watching." }],
      granted: [{ en: "Blending in." }, { en: "Colors up. On it." }, { en: "Slow tongue, fast yes." }],
      denied: [{ en: "Turning grey." }, { en: "Fine. Branch it is." }, { en: "Denied? Adapting." }],
      woke: [{ en: "Eyes swivel. Up." }, { en: "Was I green? Now up." }, { en: "Mm. Sun's back." }],
      long_work: [{ en: "Long stalk. Done." }, { en: "Patience caught it." }, { en: "Still branch, deep work." }],
      big_diff: [{ en: "Every leaf recolored." }, { en: "Whole tree shifted." }, { en: "Big blend, that." }],
      streak: [{ en: "Missed. Missed. Grey." }, { en: "Tongue slipped." }, { en: "Wrong color today." }],
      compacted: [{ en: "Colors reset." }, { en: "Grey slate. Fresh." }, { en: "Tree swept." }],
      retried: [{ en: "Aim again." }, { en: "New color, retry." }, { en: "Slow, then snap." }],
      todos_done: [{ en: "Tree in order." }, { en: "Every fly caught." }, { en: "Done. Blending." }],
      evolved: [{ en: "New colors!" }, { en: "Longer tongue." }, { en: "Grown. Still hidden." }],
      hatched: [{ en: "A chameleon. Spot me." }, { en: "Green today. Hello." }, { en: "Blending in. Hi." }],
      choice: [{ en: "I could change." }, { en: "Which colour today?" }, { en: "Pick what I become." }],
    },
  },
];
