import type { SpeciesDef } from "../species.ts";

/** The uncommon Species: marked silhouettes, ears, wings, tentacles, spines, gills. */
export const UNCOMMON: readonly SpeciesDef[] = [
  {
    id: "fox",
    label: { en: "fox" },
    rarity: "uncommon",
    sheet: { sarcastic: 2, energy: 1, sensitivity: 1 },
    bodies: {
      hatchling: (e, m) => [
        `  /|   |\\ ${m}`,
        `  ( ${e} )`,
        "   \\ v /",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `  /|   |\\ ${m}`,
        `  ( ${e} )`,
        "  /| v |\\",
        "   |___|",
        "  ~/   \\~",
      ],
      adult: (e, m) => [
        `  /|   |\\ ${m}`,
        `  ( ${e} )`,
        " /|  v  |\\",
        "  |_____|",
        "~~/|   |\\",
      ],
      elder: (e, m) => [
        `  /|   |\\ ${m}`,
        `  ( ${e} )`,
        " /|~~v~~|\\",
        "  |_____|",
        "~~/|   |\\",
      ],
    },
    signature: {
      permission: [{ en: "May I? Sly grin." }, { en: "Your henhouse, boss." }, { en: "Permission, hm?" }],
      granted: [{ en: "Clever choice." }, { en: "Slipping in. Quiet." }, { en: "Foxy. On it." }],
      denied: [{ en: "Denied? Cute." }, { en: "Fine. Other burrow." }, { en: "Tail flick. Noted." }],
      woke: [{ en: "Ears up. What now?" }, { en: "Was dreaming of hens." }, { en: "Mm. Dawn already." }],
      long_work: [{ en: "Long hunt. Good one." }, { en: "Patience got the hen." }, { en: "Den's full tonight." }],
      big_diff: [{ en: "Whole forest moved." }, { en: "Bold. I like bold." }, { en: "That's a big den." }],
      streak: [{ en: "Trap. Trap. Trap." }, { en: "Even foxes trip." }, { en: "Not so sly today." }],
      compacted: [{ en: "Den swept clean." }, { en: "Scent trail gone." }, { en: "Fresh snow. Fresh me." }],
      retried: [{ en: "Sneak in again." }, { en: "Second pounce." }, { en: "Sly retry." }],
      todos_done: [{ en: "Every hen counted." }, { en: "Den in order." }, { en: "Done. Tail curled." }],
      evolved: [{ en: "Bushier tail." }, { en: "Sharper ears now." }, { en: "Sly and grown." }],
      hatched: [{ en: "A fox. Naturally." }, { en: "Sly from the start." }, { en: "Ears up. Hello." }],
      choice: [{ en: "Choose cleverly." }, { en: "Two ways. Pick well." }, { en: "Your move, human." }],
    },
  },
  {
    id: "penguin",
    label: { en: "penguin" },
    rarity: "uncommon",
    sheet: { stoic: 2, chatter: 1 },
    bodies: {
      hatchling: (e, m) => [
        `   ,--,   ${m}`,
        `  ( ${e} )`,
        "  <  v  >",
        "   '--'",
        "",
      ],
      young: (e, m) => [
        `   ,--,   ${m}`,
        `  ( ${e} )`,
        "  <| v |>",
        "   |   |",
        "   ~~ ~~",
      ],
      adult: (e, m) => [
        `   ,--,   ${m}`,
        `  ( ${e} )`,
        " <(  v  )>",
        "  (     )",
        "  ~~   ~~",
      ],
      elder: (e, m) => [
        `   ,--,   ${m}`,
        `  ( ${e} )`,
        " <(~~v~~)>",
        "  (     )",
        "  ~~~~~~~",
      ],
    },
    signature: {
      permission: [{ en: "Protocol: ask you." }, { en: "May I, formally?" }, { en: "Awaiting clearance." }],
      granted: [{ en: "Cleared. Sliding in." }, { en: "Formation, go." }, { en: "Flippers up. On it." }],
      denied: [{ en: "Understood. Standing." }, { en: "Back to the huddle." }, { en: "Denied. Very well." }],
      woke: [{ en: "Ice cold. Awake." }, { en: "Huddle broke up?" }, { en: "Flippers stiff. Up." }],
      long_work: [{ en: "Long march. Done." }, { en: "Held the egg all night." }, { en: "Cold work, warm end." }],
      big_diff: [{ en: "Whole colony moved!" }, { en: "Big ice shelf, that." }, { en: "Lots of flippers." }],
      streak: [{ en: "Slipped. Again. Again." }, { en: "Ice is ice." }, { en: "Belly slide gone wrong." }],
      compacted: [{ en: "Ice cleared." }, { en: "Fresh snow. Fresh start." }, { en: "Huddle reset." }],
      retried: [{ en: "Waddle back. Again." }, { en: "Second slide." }, { en: "Once more, formal." }],
      todos_done: [{ en: "Colony in order." }, { en: "All eggs counted." }, { en: "Formation complete." }],
      evolved: [{ en: "Sleeker feathers." }, { en: "Taller in the huddle." }, { en: "Grown. Formally." }],
      hatched: [{ en: "A penguin. Formal." }, { en: "Tuxedo on. Hello." }, { en: "Cold outside. Hi." }],
      choice: [{ en: "A decision, please." }, { en: "Formal choice awaits." }, { en: "Select one." }],
    },
  },
  {
    id: "octopus",
    label: { en: "octopus" },
    rarity: "uncommon",
    sheet: { dreamy: 2, chatter: 1, sensitivity: -1 },
    bodies: {
      hatchling: (e, m) => [
        `   _.-._  ${m}`,
        `  ( ${e} )`,
        "   )()()(",
        "   ' ' '",
        "",
      ],
      young: (e, m) => [
        `   _.-._  ${m}`,
        `  ( ${e} )`,
        "  )()()()(",
        "  ) ) ) )",
        "   ' ' '",
      ],
      adult: (e, m) => [
        `  _.---._ ${m}`,
        `  ( ${e} )`,
        " )()()()()(",
        " ) ) ) ) )",
        "  ' ' ' '",
      ],
      elder: (e, m) => [
        `  _.-~-._ ${m}`,
        `  ( ${e} )`,
        " )()()()()(",
        " ) ) ) ) )",
        " ~' ' ' '~",
      ],
    },
    signature: {
      permission: [{ en: "Eight arms ask: may I?" }, { en: "Reach in? Your call." }, { en: "Ink or go? You say." }],
      granted: [{ en: "All arms in!" }, { en: "Curious. Reaching." }, { en: "Eight hands on it." }],
      denied: [{ en: "Ink. Fine." }, { en: "Arms folded. Okay." }, { en: "Back to my rock." }],
      woke: [{ en: "Which arm was asleep?" }, { en: "Hm? All eight up." }, { en: "Drifting... awake." }],
      long_work: [{ en: "Eight arms, one job." }, { en: "Long reach, that one." }, { en: "Tangled, then done." }],
      big_diff: [{ en: "Touched everything!" }, { en: "Eight arms, ten files." }, { en: "Ink cloud of changes." }],
      streak: [{ en: "Ink. Ink. Ink." }, { en: "Tangled myself." }, { en: "Suckers slipping." }],
      compacted: [{ en: "Ink cleared." }, { en: "Rock swept. Fresh." }, { en: "New camouflage." }],
      retried: [{ en: "Another arm, then." }, { en: "Reach again." }, { en: "Seven more tries." }],
      todos_done: [{ en: "All arms free!" }, { en: "Every shell opened." }, { en: "Done. Curling up." }],
      evolved: [{ en: "Longer arms!" }, { en: "More suckers. Nice." }, { en: "Grown. Eightfold." }],
      hatched: [{ en: "An octopus. Curious." }, { en: "Eight arms. Hello!" }, { en: "Ink? Later. Hi." }],
      choice: [{ en: "Ooh, options!" }, { en: "Three arms, one pick." }, { en: "Which shall I be?" }],
    },
  },
  {
    id: "bat",
    label: { en: "bat" },
    rarity: "uncommon",
    sheet: { energy: 2, chatter: -2, sensitivity: 1 },
    bodies: {
      hatchling: (e, m) => [
        `  /^\\ /^\\ ${m}`,
        `  ( ${e} )`,
        "  /\\_v_/\\",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `  /^\\ /^\\ ${m}`,
        `  ( ${e} )`,
        "/\\/\\_v_/\\/\\",
        "   \\   /",
        "    ' '",
      ],
      adult: (e, m) => [
        `  /^\\ /^\\ ${m}`,
        `  ( ${e} )`,
        "/\\/\\_v_/\\/\\",
        "\\/\\ \\ / /\\/",
        "     '",
      ],
      elder: (e, m) => [
        `  /^\\ /^\\ ${m}`,
        `  ( ${e} )`,
        "/\\/\\~v~/\\/\\",
        "\\/\\ \\ / /\\/",
        "    ~'~",
      ],
    },
    signature: {
      permission: [{ en: "Whisper: may I?" }, { en: "Dark says ask you." }, { en: "Hang on. Allowed?" }],
      granted: [{ en: "Swooping in." }, { en: "Wings out. Quiet." }, { en: "Good. Into the dark." }],
      denied: [{ en: "Hanging back." }, { en: "Cave it is." }, { en: "Fine. Upside down." }],
      woke: [{ en: "Dusk already?" }, { en: "Hanging... awake." }, { en: "Echo. Echo. Up." }],
      long_work: [{ en: "Long night flight." }, { en: "Echoes fade. Done." }, { en: "Dawn found me working." }],
      big_diff: [{ en: "Whole cave shifted." }, { en: "Echoes everywhere." }, { en: "Big flock of files." }],
      streak: [{ en: "Wall. Wall. Wall." }, { en: "Echo lied. Ouch." }, { en: "Blind spot today." }],
      compacted: [{ en: "Cave swept." }, { en: "Echoes cleared." }, { en: "Fresh dark." }],
      retried: [{ en: "Flit back in." }, { en: "Echo, retry." }, { en: "Once more, softly." }],
      todos_done: [{ en: "Cave in order." }, { en: "All echoes answered." }, { en: "Done. Hanging up." }],
      evolved: [{ en: "Wider wings." }, { en: "Sharper ears." }, { en: "Grown in the dark." }],
      hatched: [{ en: "A bat. Quietly." }, { en: "Wings and ears. Hi." }, { en: "Dark's fine. Hello." }],
      choice: [{ en: "Something waits." }, { en: "A choice, quietly." }, { en: "Listen. Then choose." }],
    },
  },
  {
    id: "hedgehog",
    label: { en: "hedgehog" },
    rarity: "uncommon",
    sheet: { sensitivity: 2, chatter: -1, stoic: 1 },
    bodies: {
      hatchling: (e, m) => [
        `   /\\/\\/\\ ${m}`,
        `  ( ${e} )`,
        "   \\_w_/",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `  /\\/\\/\\/\\${m}`,
        `  ( ${e} )`,
        " /\\/\\/\\/\\/\\",
        " (   w   )",
        "  ''   ''",
      ],
      adult: (e, m) => [
        `  /\\/\\/\\/\\${m}`,
        `  ( ${e} )`,
        "/\\/\\/\\/\\/\\/",
        "(    w    )",
        "  ''   ''",
      ],
      elder: (e, m) => [
        `  /\\/\\/\\/\\${m}`,
        `  ( ${e} )`,
        "/\\/\\/\\/\\/\\/",
        "(  ~~w~~  )",
        " ~''   ''~",
      ],
    },
    signature: {
      permission: [{ en: "Spines down. May I?" }, { en: "Careful ask: allowed?" }, { en: "Your call. Curling." }],
      granted: [{ en: "Uncurling. On it." }, { en: "Spines relaxed. Go." }, { en: "Good. Snuffling in." }],
      denied: [{ en: "Curling up." }, { en: "Spines up. Fine." }, { en: "Back in the leaves." }],
      woke: [{ en: "Snuffle. Awake." }, { en: "Leaves rustled. Up." }, { en: "Was I balled up?" }],
      long_work: [{ en: "Long snuffle. Done." }, { en: "Leaf pile's cleared." }, { en: "Slow and steady, us." }],
      big_diff: [{ en: "Leaves everywhere!" }, { en: "Whole hedge moved." }, { en: "Big rustle, that." }],
      streak: [{ en: "Spines out. Ouch." }, { en: "Prickly. Prickly." }, { en: "Curled tight now." }],
      compacted: [{ en: "Leaves swept." }, { en: "Spines smoothed." }, { en: "Fresh hedge." }],
      retried: [{ en: "Uncurl. Again." }, { en: "Snuffle once more." }, { en: "Second poke." }],
      todos_done: [{ en: "Hedge in order." }, { en: "Every leaf turned." }, { en: "Done. Balling up." }],
      evolved: [{ en: "More spines!" }, { en: "Bigger ball. Nice." }, { en: "Grown. Prickly." }],
      hatched: [{ en: "A hedgehog. Hello." }, { en: "Spiky already. Hi." }, { en: "Snuffle. It's me." }],
      choice: [{ en: "Snuffle. A choice." }, { en: "Which way, then?" }, { en: "Two paths. Hmm." }],
    },
  },
  {
    id: "axolotl",
    label: { en: "axolotl" },
    rarity: "uncommon",
    sheet: { cheerful: 1, sensitivity: -2, patience: 1 },
    bodies: {
      hatchling: (e, m) => [
        `  }~   ~{ ${m}`,
        `  ( ${e} )`,
        "   \\_u_/",
        "    '-'",
        "",
      ],
      young: (e, m) => [
        `  }~   ~{ ${m}`,
        `  ( ${e} )`,
        " }~( u )~{",
        "   |___|",
        "   ~~~~~",
      ],
      adult: (e, m) => [
        ` }}~  ~{{ ${m}`,
        `  ( ${e} )`,
        "}}~( u )~{{",
        "  |_____|",
        "  ~~~~~~~",
      ],
      elder: (e, m) => [
        ` }}~  ~{{ ${m}`,
        `  ( ${e} )`,
        "}}~(~u~)~{{",
        "  |_____|",
        " ~~~~~~~~~",
      ],
    },
    signature: {
      permission: [{ en: "Gills say: may I?" }, { en: "Soft ask. Allowed?" }, { en: "Your call. Smiling." }],
      granted: [{ en: "Swimming in. Smile." }, { en: "Gills up. On it." }, { en: "Lovely. Wiggling." }],
      denied: [{ en: "Smile. Okay." }, { en: "Back to the tank." }, { en: "Fine. Floating." }],
      woke: [{ en: "Gills flutter. Up." }, { en: "Was I floating?" }, { en: "Mm. Water's warm." }],
      long_work: [{ en: "Long swim. Smiling." }, { en: "Slow current, done." }, { en: "Regrew a patience." }],
      big_diff: [{ en: "Tank rearranged!" }, { en: "Whole reef moved." }, { en: "Big bubble, that." }],
      streak: [{ en: "Ouch. Regrowing." }, { en: "Nipped. It heals." }, { en: "Still smiling. Ow." }],
      compacted: [{ en: "Water changed." }, { en: "Tank fresh. Smile." }, { en: "Gills clear." }],
      retried: [{ en: "Wiggle again." }, { en: "Regrow and retry." }, { en: "Soft second try." }],
      todos_done: [{ en: "Tank tidy. Smile." }, { en: "All pebbles placed." }, { en: "Done. Floating." }],
      evolved: [{ en: "Longer gills!" }, { en: "Grown. Still smiling." }, { en: "Regrew bigger." }],
      hatched: [{ en: "An axolotl. Hi!" }, { en: "Gills and smile. Hello." }, { en: "Pink and here." }],
      choice: [{ en: "A choice! Smile." }, { en: "Which one? Hehe." }, { en: "Pick one for me!" }],
    },
  },
];
