import type { SpeciesDef } from "../species.ts";

/** The uncommon Species: marked silhouettes, ears, wings, tentacles, spines, gills. */
export const UNCOMMON: readonly SpeciesDef[] = [
  {
    id: "fox",
    label: { en: "fox", fr: "renard" },
    gender: "m",
    rarity: "uncommon",
    sheet: { sarcastic: 2, energy: 1, sensitivity: 1 },
    maps: {
      hatchling: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          ".......o.....o.......",
          "......cao...oac......",
          ".....oaaoooooaao.....",
          ".....oaaoooooaao.....",
          "....oaaaaaaaaaaao....",
          "...oabbaaaaaaabbao...",
          "...oabbaaaaaaabbao...",
          "...oaaaaaaacaaaaao...",
          "...oaaaaaaaaaaaaao...",
          "....ooooooooooooo....",
          ".....obbbbbbbbbo.....",
          "....oabbbbbbbbbao....",
          "....oaabbbbbbbaao....",
          ".....oaabbbbbaao.....",
          ".....ooooooooooo.....",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 8, w: 3, h: 3 }, { x: 12, y: 8, w: 3, h: 3 }],
      },
      young: {
        pixels: [
          ".....................",
          ".......o.....o.......",
          "......cao...oac......",
          ".....oaaoo.ooaao.....",
          "....oaaaoooooaaao....",
          "...oaaaaaaaaaaaaao...",
          "..oabbaaaaaaaaabbao..",
          "..oabbaaaaaaaaabbao..",
          "..oaaaaaaaacaaaaaao..",
          "..oaaaaaaaaaaaaaaao..",
          "...ooooooooooooooo...",
          "......obbbbbbbo......",
          ".....oabbbbbbbao..aaa",
          "....oaabbbbbbbaao..aa",
          "....oaabbbbbbbaao..aa",
          "....oaabbbbbbbaao...b",
          "....oaaaaaaaaaaao....",
          "....oaao...oaao......",
          "....oooo...oooo......",
          ".....................",
        ],
        eyes: [{ x: 5, y: 5, w: 3, h: 3 }, { x: 13, y: 5, w: 3, h: 3 }],
        motion: { tail: { x: 18, y: 12, w: 3, h: 4 } },
      },
      adult: {
        pixels: [
          "......o.....o........",
          ".....cao...oac.......",
          "....oaaoo.ooaao......",
          "....oaaaoooooaaao....",
          "...oaaaaaaaaaaaaao...",
          ".oabbaaaaaaaaaaabbao.",
          "oabbaaaaaaaaaaaaabbao",
          "oaaaaaaaaaaaaaaaaaaao",
          "oaaaaaaaaaaaacaaaaaao",
          "oaaaaaaaaaaaaaaaaaaao",
          ".oaaaaaaaaaaaaaaaaao.",
          "..ooooooooooooooooo..",
          "......obbbbbbbo......",
          "....oaabbbbbbbaao.aaa",
          "...oaaabbbbbbbaaao.aa",
          "..oaaaabbbbbbbaaao.aa",
          "..oaaaabbbbbbbaaao..b",
          "..oaao.......oaao....",
          "..oooo.......oooo....",
          ".....................",
        ],
        eyes: [{ x: 4, y: 4, w: 3, h: 3 }, { x: 14, y: 4, w: 3, h: 3 }],
        motion: { tail: { x: 18, y: 13, w: 3, h: 4 } },
      },
      elder: {
        pixels: [
          "......o.....o........",
          ".....cao...oac.......",
          "....oaaoo.ooaao......",
          "...oaaaaoooooaaao....",
          "...oaaaaaaaaaaaaao...",
          ".oabbaaaaaaaaaaabbao.",
          "oabbaaaaaaaaaaaaabbao",
          "oaaaaaaaaaaaaaaaaaaao",
          "oaaaaaaaacaaacaaaaaao",
          "oaaaaaaaaaaaaaaaaaaao",
          ".oaaaaaaaaaaaaaaaaao.",
          "..ooooooooooooooooo..",
          "......obbbbbbbo......",
          "....caabbbbbbbaac.aaa",
          "...oaaabbbbbbbaaao.aa",
          "..oaaaabbbbbbbaaao.ab",
          "..oaaaabbbbbbbaaao..b",
          "..oaao.......oaao....",
          "..oooo.......oooo....",
          ".....................",
        ],
        eyes: [{ x: 4, y: 4, w: 3, h: 3 }, { x: 14, y: 4, w: 3, h: 3 }],
        motion: { tail: { x: 18, y: 13, w: 3, h: 4 } },
      },
    },
    palettes: {
      dark: { outline: "#2b1108", primary: "#c0421f", secondary: "#fdf6ec", accent: "#1a1310", eye: "#0f0c0a" },
      light: { outline: "#452216", primary: "#a8371a", secondary: "#f5e9d8", accent: "#241c17", eye: "#171310" },
    },
    signature: {
      permission: [{ en: "May I? Sly grin.", fr: "Je me sers ? Hé hé." }, { en: "Your henhouse, boss.", fr: "Ton poulailler, chef." }, { en: "Permission, hm?", fr: "La permission, hmm ?" }],
      granted: [{ en: "Clever choice.", fr: "Bien joué." }, { en: "Slipping in. Quiet.", fr: "Je me faufile. Chut." }, { en: "Foxy. On it.", fr: "Tout en finesse." }],
      denied: [{ en: "Denied? Cute.", fr: "Refusé ? C'est mignon." }, { en: "Fine. Other burrow.", fr: "Bon. Une autre piste." }, { en: "Tail flick. Noted.", fr: "La queue frémit. Noté." }],
      woke: [{ en: "Ears up. What now?", fr: "Oreilles droites. Quoi ?" }, { en: "Was dreaming of hens.", fr: "Je rêvais de poules." }, { en: "Mm. Dawn already.", fr: "Mm. Le jour se lève." }],
      long_work: [{ en: "Long hunt. Good one.", fr: "Longue chasse. Réussie." }, { en: "Patience got the hen.", fr: "À force, j'ai la poule." }, { en: "Den's full tonight.", fr: "Terrier plein ce soir." }],
      big_diff: [{ en: "Whole forest moved.", fr: "Tout le bois a changé." }, { en: "Bold. I like bold.", fr: "Audacieux. J'aime ça." }, { en: "That's a big den.", fr: "Un terrier de seigneur." }],
      streak: [{ en: "Trap. Trap. Trap.", fr: "Piège. Piège. Piège." }, { en: "Even foxes trip.", fr: "Même moi, je trébuche." }, { en: "Not so sly today.", fr: "Pas si rusé que ça." }],
      compacted: [{ en: "Den swept clean.", fr: "Tanière nettoyée." }, { en: "Scent trail gone.", fr: "L'odeur a disparu." }, { en: "Fresh snow. Fresh me.", fr: "Neige neuve. Moi aussi." }],
      retried: [{ en: "Sneak in again.", fr: "Je repasse en douce." }, { en: "Second pounce.", fr: "Second assaut." }, { en: "Sly retry.", fr: "Un essai de renard." }],
      todos_done: [{ en: "Every hen counted.", fr: "J'ai compté les poules." }, { en: "Den in order.", fr: "Tanière en ordre." }, { en: "Done. Tail curled.", fr: "Fini. Queue enroulée." }],
      evolved: [{ en: "Bushier tail.", fr: "La queue a épaissi." }, { en: "Sharper ears now.", fr: "Oreilles plus fines." }, { en: "Sly and grown.", fr: "Encore plus rusé." }],
      hatched: [{ en: "A fox. Naturally.", fr: "Renard. Qui d'autre ?" }, { en: "Sly from the start.", fr: "Rusé de naissance." }, { en: "Ears up. Hello.", fr: "Museau dehors. Salut." }],
      choice: [{ en: "Choose cleverly.", fr: "Choisis. Sois malin." }, { en: "Two ways. Pick well.", fr: "Deux pistes. Une seule." }, { en: "Your move, human.", fr: "À toi de jouer, humain." }],
    },
  },
  {
    id: "penguin",
    label: { en: "penguin", fr: "manchot" },
    gender: "m",
    rarity: "uncommon",
    sheet: { stoic: 2, chatter: 1 },
    maps: {
      hatchling: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          "........oaaao........",
          ".......oaaaaao.......",
          "......oaaaaaaao......",
          ".....obbbaaabbbo.....",
          ".....obbbacabbbo.....",
          ".....obbbcccbbbo.....",
          "......oaaaaaaao......",
          "......ooooooooo......",
          ".....oaabbbbbaao.....",
          ".....oaabbbbbaao.....",
          "......oaabbbaao......",
          ".......ooooooo.......",
          ".........ccc.........",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 7, w: 3, h: 3 }, { x: 12, y: 7, w: 3, h: 3 }],
      },
      young: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          "........oaaao........",
          ".......oaaaaao.......",
          "......oaaaaaaao......",
          ".....obbbaaabbbo.....",
          "....oabbbacabbbao....",
          "....oabbbcccbbbao....",
          "....oaaaaaaaaaaao....",
          "...oaaaaaaaaaaaaao...",
          "....ooooooooooooo....",
          "...oaabbbbbbbbbaao...",
          "...oaabbbbbbbbbaao...",
          "...oaabbbbbbbbbaao...",
          "....oaabbbbbbbaao....",
          ".....ooooooooooo.....",
          ".......ccc.ccc.......",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 6, w: 3, h: 3 }, { x: 12, y: 6, w: 3, h: 3 }],
      },
      adult: {
        pixels: [
          ".....................",
          ".....................",
          "........oaaao........",
          "......oaaaaaaao......",
          ".....oaaaaaaaaao.....",
          "....obbbaaaaabbbo....",
          "...oabbbaacaabbbao...",
          "...oabbbacccabbbao...",
          "...oaaaaaaaaaaaaao...",
          "..oaaaaaaaaaaaaaaao..",
          "...ooooooooooooooo...",
          "..oaaabbbbbbbbbaaao..",
          "..oaaabbbbbbbbbaaao..",
          "..oaaabbbbbbbbbaaao..",
          "..oaaabbbbbbbbbaaao..",
          "...oaaabbbbbbbaaao...",
          "....ooooooooooooo....",
          "......ccc...ccc......",
          "......ccc...ccc......",
          ".....................",
        ],
        eyes: [{ x: 5, y: 5, w: 3, h: 3 }, { x: 13, y: 5, w: 3, h: 3 }],
      },
      elder: {
        pixels: [
          ".....................",
          "........oaaao........",
          "......oaaaaaaao......",
          ".....oaaaaaaaaao.....",
          "....obbbaaaaabbbo....",
          "...oabbbacacabbbao...",
          "...oabbbcccccbbbao...",
          "...oaaaaaaaaaaaaao...",
          "..oaaaaaaaaaaaaaaao..",
          "...ooooooooooooooo...",
          "..oaaabbbbbbbbbaaao..",
          "..oaaabbbbbbbbbaaao..",
          "..oaaabbbbbbbbbaaao..",
          "..oaaabbbbbbbbbaaao..",
          "...oaaabbbbbbbaaao...",
          "....ooooooooooooo....",
          "......ccc...ccc......",
          "......ccc...ccc......",
          "......ooo...ooo......",
          ".....................",
        ],
        eyes: [{ x: 5, y: 4, w: 3, h: 3 }, { x: 13, y: 4, w: 3, h: 3 }],
      },
    },
    palettes: {
      dark: { outline: "#0b0e14", primary: "#232f3d", secondary: "#f5f5f0", accent: "#e8973a", eye: "#12100e" },
      light: { outline: "#1a1f2b", primary: "#1c2530", secondary: "#e8e4d8", accent: "#d1841f", eye: "#181310" },
    },
    signature: {
      permission: [{ en: "Protocol: ask you.", fr: "Protocole : je demande." }, { en: "May I, formally?", fr: "Puis-je, je vous prie ?" }, { en: "Awaiting clearance.", fr: "En attente de feu vert." }],
      granted: [{ en: "Cleared. Sliding in.", fr: "Accordé. Je m'élance." }, { en: "Formation, go.", fr: "La colonne s'ébranle." }, { en: "Flippers up. On it.", fr: "Ailerons levés. Je pars." }],
      denied: [{ en: "Understood. Standing.", fr: "Entendu. Je patiente." }, { en: "Back to the huddle.", fr: "Je regagne le groupe." }, { en: "Denied. Very well.", fr: "Refusé. Soit." }],
      woke: [{ en: "Ice cold. Awake.", fr: "Froid glacial. Réveil." }, { en: "Huddle broke up?", fr: "On s'est dispersés ?" }, { en: "Flippers stiff. Up.", fr: "Ailerons raides. Debout." }],
      long_work: [{ en: "Long march. Done.", fr: "Longue marche. Achevée." }, { en: "Held the egg all night.", fr: "J'ai couvé sans dormir." }, { en: "Cold work, warm end.", fr: "Froid, mais bien mené." }],
      big_diff: [{ en: "Whole colony moved!", fr: "La colonie a déménagé !" }, { en: "Big ice shelf, that.", fr: "Une banquise entière !" }, { en: "Lots of flippers.", fr: "Il a fallu des ailerons." }],
      streak: [{ en: "Slipped. Again. Again.", fr: "Chute. Chute. Chute." }, { en: "Ice is ice.", fr: "La glace, c'est ainsi." }, { en: "Belly slide gone wrong.", fr: "Glissade mal engagée." }],
      compacted: [{ en: "Ice cleared.", fr: "Glace déblayée." }, { en: "Fresh snow. Fresh start.", fr: "Neige fraîche. Reprise." }, { en: "Huddle reset.", fr: "Groupe reformé." }],
      retried: [{ en: "Waddle back. Again.", fr: "Je remonte la pente." }, { en: "Second slide.", fr: "Seconde glissade." }, { en: "Once more, formal.", fr: "Derechef, donc." }],
      todos_done: [{ en: "Colony in order.", fr: "Colonie conforme." }, { en: "All eggs counted.", fr: "Tous les œufs sont là." }, { en: "Formation complete.", fr: "Formation complète." }],
      evolved: [{ en: "Sleeker feathers.", fr: "Plumage plus lisse." }, { en: "Taller in the huddle.", fr: "Plus haut dans le rang." }, { en: "Grown. Formally.", fr: "Grandi. Dans les formes." }],
      hatched: [{ en: "A penguin. Formal.", fr: "Manchot. Pas pingouin." }, { en: "Tuxedo on. Hello.", fr: "En smoking. Enchanté." }, { en: "Cold outside. Hi.", fr: "Il fait froid. Bonjour." }],
      choice: [{ en: "A decision, please.", fr: "Une décision, merci." }, { en: "Formal choice awaits.", fr: "Votre choix est requis." }, { en: "Select one.", fr: "Sélectionnez-en un." }],
    },
  },
  {
    id: "octopus",
    label: { en: "octopus", fr: "pieuvre" },
    gender: "f",
    rarity: "uncommon",
    sheet: { dreamy: 2, chatter: 1, sensitivity: -1 },
    maps: {
      hatchling: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          "........oaaao........",
          "......oaaaaaaao......",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaao.....",
          ".....oaaaaaaaaao.....",
          ".....obbbbbbbbbo.....",
          ".....ooooooooooo.....",
          ".....aa.aa.aa.aa.....",
          ".....aa.aa.aa.aa.....",
          ".....oo.aa.aa.oo.....",
          "........oo.oo........",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 6, w: 3, h: 3 }, { x: 12, y: 6, w: 3, h: 3 }],
      },
      young: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          "........oaaao........",
          "......oaaaaaaao......",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          "....obbbbbbbbbbbo....",
          ".....obbbbbbbbbo.....",
          ".....ooooooooooo.....",
          ".....aa.aa.aa.aa.....",
          "......a.aa.aa.a......",
          "......c.aa.aa.c......",
          "......a.cc.cc.a......",
          "......o.aa.aa.o......",
          "........oo.oo........",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 5, y: 5, w: 3, h: 3 }, { x: 13, y: 5, w: 3, h: 3 }],
      },
      adult: {
        pixels: [
          ".....................",
          "........oaaao........",
          "......oaaaaaaao......",
          "....oaaaaaaaaaaao....",
          "...oaaaaaaaaaaaaao...",
          "...oaaaaaaaaaaaaao...",
          "...oaaaaaaaaaaaaao...",
          "...obbbbbbbbbbbbbo...",
          "....obbbbbbbbbbbo....",
          "....ooooooooooooo....",
          "....aa.aa.a.aa.aa....",
          ".....a.aa.a.aa.a.....",
          ".....a.aa.a.aa.a.....",
          ".....c.cc.c.cc.c.....",
          ".....a.aa.a.aa.a.....",
          ".....o.aa.a.aa.o.....",
          ".......oo.o.oo.......",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 4, y: 4, w: 3, h: 3 }, { x: 14, y: 4, w: 3, h: 3 }],
      },
      elder: {
        pixels: [
          ".....................",
          "........oaaao........",
          "......oaaaaaaao......",
          "....oaaaaaaaaaaao....",
          "...oaaaaaaaaaaaaao...",
          "...oaaaaaaaaaaaaao...",
          "...oaaaaaaaaaaaaao...",
          "...obbbbbbbbbbbbbo...",
          "...obbbbbbbbbbbbbo...",
          "...ooooooooooooooo...",
          "...aa.a.aa.aa.a.aa...",
          "....a.a.aa.aa.a.a....",
          "....a.a.aa.aa.a.a....",
          "....c.c.cc.cc.c.c....",
          "....a.a.aa.aa.a.a....",
          "....o.a.aa.aa.a.o....",
          "......o.oo.oo.o......",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 4, y: 4, w: 3, h: 3 }, { x: 13, y: 4, w: 3, h: 3 }],
      },
    },
    palettes: {
      dark: { outline: "#2b0f24", primary: "#c0447a", secondary: "#f0b8d0", accent: "#5c2d5c", eye: "#150a12" },
      light: { outline: "#42182f", primary: "#a8386a", secondary: "#e8a8c4", accent: "#48213f", eye: "#1c0f18" },
    },
    signature: {
      permission: [{ en: "Eight arms ask: may I?", fr: "Huit bras. J'y touche ?" }, { en: "Reach in? Your call.", fr: "Un bras tendu ? À toi." }, { en: "Ink or go? You say.", fr: "L'encre ou le geste ?" }],
      granted: [{ en: "All arms in!", fr: "Tous les bras dedans !" }, { en: "Curious. Reaching.", fr: "Intriguée. J'explore." }, { en: "Eight hands on it.", fr: "Huit mains dessus." }],
      denied: [{ en: "Ink. Fine.", fr: "De l'encre. Bon." }, { en: "Arms folded. Okay.", fr: "Bras repliés. D'accord." }, { en: "Back to my rock.", fr: "Mon rocher m'attend." }],
      woke: [{ en: "Which arm was asleep?", fr: "Quel bras dormait ?" }, { en: "Hm? All eight up.", fr: "Hm ? Les huit, debout." }, { en: "Drifting... awake.", fr: "Je dérivais. Réveillée." }],
      long_work: [{ en: "Eight arms, one job.", fr: "Huit bras, une tâche." }, { en: "Long reach, that one.", fr: "Il a fallu s'étendre." }, { en: "Tangled, then done.", fr: "Nouée, puis dénouée." }],
      big_diff: [{ en: "Touched everything!", fr: "J'ai touché à tout !" }, { en: "Eight arms, ten files.", fr: "Huit bras, dix fichiers." }, { en: "Ink cloud of changes.", fr: "Nuage d'encre. Partout." }],
      streak: [{ en: "Ink. Ink. Ink.", fr: "Encre. Encre. Encre." }, { en: "Tangled myself.", fr: "Je me suis emmêlée." }, { en: "Suckers slipping.", fr: "Les ventouses lâchent." }],
      compacted: [{ en: "Ink cleared.", fr: "L'encre s'est dissipée." }, { en: "Rock swept. Fresh.", fr: "Rocher balayé. Net." }, { en: "New camouflage.", fr: "Nouveau camouflage." }],
      retried: [{ en: "Another arm, then.", fr: "Un autre bras, alors." }, { en: "Reach again.", fr: "J'y retouche." }, { en: "Seven more tries.", fr: "Sept essais en réserve." }],
      todos_done: [{ en: "All arms free!", fr: "Huit bras libres !" }, { en: "Every shell opened.", fr: "Aucun coquillage fermé." }, { en: "Done. Curling up.", fr: "Fini. Je m'enroule." }],
      evolved: [{ en: "Longer arms!", fr: "Des bras plus longs !" }, { en: "More suckers. Nice.", fr: "Encore des ventouses !" }, { en: "Grown. Eightfold.", fr: "Huit fois plus grande." }],
      hatched: [{ en: "An octopus. Curious.", fr: "Une pieuvre. Curieuse." }, { en: "Eight arms. Hello!", fr: "Huit bras. Bonjour !" }, { en: "Ink? Later. Hi.", fr: "L'encre ? Après. Salut." }],
      choice: [{ en: "Ooh, options!", fr: "Oh, des possibilités !" }, { en: "Three arms, one pick.", fr: "Trois bras, un choix." }, { en: "Which shall I be?", fr: "Laquelle serai-je ?" }],
    },
  },
  {
    id: "bat",
    label: { en: "bat", fr: "chauve-souris" },
    gender: "f",
    rarity: "uncommon",
    sheet: { energy: 2, chatter: -2, sensitivity: 1 },
    maps: {
      hatchling: {
        pixels: [
          ".....................",
          ".....................",
          ".......o.....o.......",
          "......oco...oco......",
          "......oaaaaaaao......",
          ".....obbbaaabbbo.....",
          ".....obbbaaabbbo.....",
          ".....obbbaaabbbo.....",
          ".....ooooooooooo.....",
          "....ooaaaaaaaaaoo....",
          "......oaaaaaaao......",
          "......ooooooooo......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 5, w: 3, h: 3 }, { x: 12, y: 5, w: 3, h: 3 }],
      },
      young: {
        pixels: [
          ".....................",
          "......o.......o......",
          ".....oco.....oco.....",
          ".....oaaaaaaaaao.....",
          "....obbbaaaaabbbo....",
          "....obbbaaaaabbbo....",
          "....obbbaaaaabbbo....",
          "...obooooooooooobo...",
          ".obcbaaaaaaaaaaabcbo.",
          "...oboaaaaaaaaaobo...",
          ".....ooooooooooo.....",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 5, y: 4, w: 3, h: 3 }, { x: 13, y: 4, w: 3, h: 3 }],
        motion: { ears: [{ x: 0, y: 8, w: 2, h: 1 }, { x: 19, y: 8, w: 2, h: 1 }] },
      },
      adult: {
        pixels: [
          "......o.......o......",
          ".....oco.....oco.....",
          ".....oaaaaaaaaao.....",
          "....obbbaaaaabbbo....",
          "....obbbaaaaabbbo....",
          "....obbbaaaaabbbo....",
          "...obooooooooooobo...",
          "obbcbaaaaaaaaaaabcbbo",
          "..obboaaaaaaaaaobbo..",
          "...obooooooooooobo...",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 4, y: 3, w: 3, h: 3 }, { x: 14, y: 3, w: 3, h: 3 }],
        motion: { ears: [{ x: 0, y: 6, w: 2, h: 2 }, { x: 19, y: 6, w: 2, h: 2 }] },
      },
      elder: {
        pixels: [
          "......o.......o......",
          ".....oco.....oco.....",
          ".....oaaaaaaaaao.....",
          "....obbbaaaaabbbo....",
          "....obbbaaaaabbbo....",
          "...obbbbaaaaabbbbo...",
          "..obbooooooooooobbo..",
          "obbcbaaaaaaaaaaabcbbo",
          "..obboaaaaaaaaaobbo..",
          "...obooooooooooobo...",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 4, y: 3, w: 3, h: 3 }, { x: 14, y: 3, w: 3, h: 3 }],
        motion: { ears: [{ x: 0, y: 6, w: 2, h: 2 }, { x: 19, y: 6, w: 2, h: 2 }] },
      },
    },
    palettes: {
      dark: { outline: "#0f0a16", primary: "#3d3350", secondary: "#a89bc4", accent: "#e8dcc0", eye: "#120c1a" },
      light: { outline: "#1c1428", primary: "#332a44", secondary: "#9686b8", accent: "#ded2b0", eye: "#171020" },
    },
    signature: {
      permission: [{ en: "Whisper: may I?", fr: "Tout bas : j'y vais ?" }, { en: "Dark says ask you.", fr: "Le noir dit : demande." }, { en: "Hang on. Allowed?", fr: "Suspendue. Permis ?" }],
      granted: [{ en: "Swooping in.", fr: "Je descends en piqué." }, { en: "Wings out. Quiet.", fr: "Ailes ouvertes. Muette." }, { en: "Good. Into the dark.", fr: "Bien. Vers la nuit." }],
      denied: [{ en: "Hanging back.", fr: "Je reste accrochée." }, { en: "Cave it is.", fr: "Va pour la grotte." }, { en: "Fine. Upside down.", fr: "Bon. La tête en bas." }],
      woke: [{ en: "Dusk already?", fr: "Déjà le crépuscule ?" }, { en: "Hanging... awake.", fr: "Pendue... mais debout." }, { en: "Echo. Echo. Up.", fr: "Écho. Écho. Ça y est." }],
      long_work: [{ en: "Long night flight.", fr: "Long vol de nuit." }, { en: "Echoes fade. Done.", fr: "Échos éteints. Fini." }, { en: "Dawn found me working.", fr: "L'aube m'a trouvée là." }],
      big_diff: [{ en: "Whole cave shifted.", fr: "La grotte a basculé." }, { en: "Echoes everywhere.", fr: "Des échos partout." }, { en: "Big flock of files.", fr: "Une nuée de fichiers." }],
      streak: [{ en: "Wall. Wall. Wall.", fr: "Mur. Mur. Mur." }, { en: "Echo lied. Ouch.", fr: "L'écho a menti. Aïe." }, { en: "Blind spot today.", fr: "Angle mort, ce soir." }],
      compacted: [{ en: "Cave swept.", fr: "La grotte est nette." }, { en: "Echoes cleared.", fr: "Les échos se sont tus." }, { en: "Fresh dark.", fr: "Obscurité toute neuve." }],
      retried: [{ en: "Flit back in.", fr: "Un coup d'aile de plus." }, { en: "Echo, retry.", fr: "Écho. Je recommence." }, { en: "Once more, softly.", fr: "Encore. Sans bruit." }],
      todos_done: [{ en: "Cave in order.", fr: "Rien ne traîne ici." }, { en: "All echoes answered.", fr: "Tous les échos rendus." }, { en: "Done. Hanging up.", fr: "Fini. Je me suspends." }],
      evolved: [{ en: "Wider wings.", fr: "Ailes plus larges." }, { en: "Sharper ears.", fr: "L'ouïe s'est aiguisée." }, { en: "Grown in the dark.", fr: "Grandie dans le noir." }],
      hatched: [{ en: "A bat. Quietly.", fr: "Une chauve-souris. Chut." }, { en: "Wings and ears. Hi.", fr: "Ailes, oreilles. Salut." }, { en: "Dark's fine. Hello.", fr: "Le noir me va. Bonsoir." }],
      choice: [{ en: "Something waits.", fr: "Quelque chose attend." }, { en: "A choice, quietly.", fr: "Un choix, en sourdine." }, { en: "Listen. Then choose.", fr: "Écoute. Puis choisis." }],
    },
  },
  {
    id: "hedgehog",
    label: { en: "hedgehog", fr: "hérisson" },
    gender: "m",
    rarity: "uncommon",
    sheet: { sensitivity: 2, chatter: -1, stoic: 1 },
    maps: {
      hatchling: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          "......o.o.o.o.o......",
          "......aoaoaoaoa......",
          ".....ooooooooooo.....",
          ".....oaaaaaaaaao.....",
          "....oaaaaaaaaaaao....",
          "....oaaabbbbbaaao....",
          ".....oaaaaaaaaao.....",
          "......ooooooooo......",
          "......obbbbbbbo......",
          ".......ooooooo.......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 5, y: 8, w: 3, h: 3 }, { x: 12, y: 8, w: 3, h: 3 }],
        motion: { ears: [{ x: 6, y: 5, w: 2, h: 2 }, { x: 13, y: 5, w: 2, h: 2 }] },
      },
      young: {
        pixels: [
          ".....................",
          ".....................",
          ".....o.o.o.o.o.o.....",
          ".....aoaoaoaoaoa.....",
          "....ooooooooooooo....",
          "....oaaaaaaaaaaao....",
          "...oaaaaaaaaaaaaao...",
          "...oaaaaaaaaaaaaao...",
          "...oaaaaaaaaaaaaao...",
          "...oaaaaaaaaaaaaao...",
          "...ooooooooooooooo...",
          "....obbbbbbbbbbbo....",
          ".....obbbbbbbbbo.....",
          "......ooooooooo......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 4, y: 7, w: 3, h: 3 }, { x: 13, y: 7, w: 3, h: 3 }],
        motion: { ears: [{ x: 5, y: 3, w: 2, h: 2 }, { x: 14, y: 3, w: 2, h: 2 }] },
      },
      adult: {
        pixels: [
          ".....................",
          "....o.o.o.o.o.o.o....",
          "....aoaoaoaoaoaoa....",
          "...ooooooooooooooo...",
          "...oaaaaaaaaaaaaao...",
          "..oaaaaaaaaaaaaaaao..",
          "..oaaaaaaaaaaaaaaao..",
          "..oaaaaaaaaaaaaaaao..",
          "..oaaaaaaaaaaaaaaao..",
          "..oaaaaaaaaaaaaaaao..",
          "..ooooooooooooooooo..",
          "...obbbbbbbbbbbbbo...",
          "....obbbbbbbbbbbo....",
          ".....obbbbbbbbbo.....",
          "......ooooooooo......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 3, y: 6, w: 3, h: 3 }, { x: 14, y: 6, w: 3, h: 3 }],
        motion: { ears: [{ x: 4, y: 2, w: 2, h: 2 }, { x: 15, y: 2, w: 2, h: 2 }] },
      },
      elder: {
        pixels: [
          "...o.o.o.o.o.o.o.o...",
          "...aoaoaoaoaoaoaoa...",
          "...ooooooooooooooo...",
          "..ooaaaaaaaaaaaaaoo..",
          "..oaaaaaaaaaaaaaaao..",
          "..oaaaaaaaaaaaaaaao..",
          "..oaaaaaaaaaaaaaaao..",
          "..oaaaaaaaaaaaaaaao..",
          ".oaaaaaaaaaaaaaaaaao.",
          ".oaaaaaaaaaaaaaaaaao.",
          ".ooooooooooooooooooo.",
          "..obbbbbbbbbbbbbbbo..",
          "...obbbbbbbbbbbbbo...",
          "....obbbbbbbbbbbo....",
          "......obbbbbbbo......",
          ".......ooooooo.......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 3, y: 6, w: 3, h: 3 }, { x: 14, y: 6, w: 3, h: 3 }],
        motion: { ears: [{ x: 4, y: 1, w: 2, h: 2 }, { x: 15, y: 1, w: 2, h: 2 }] },
      },
    },
    palettes: {
      dark: { outline: "#241a10", primary: "#9c8365", secondary: "#f0e6d2", accent: "#4a3826", eye: "#120c08" },
      light: { outline: "#3a2a1a", primary: "#83694e", secondary: "#e3d6ba", accent: "#3a2c1c", eye: "#171009" },
    },
    signature: {
      permission: [{ en: "Spines down. May I?", fr: "Piquants baissés. Oui ?" }, { en: "Careful ask: allowed?", fr: "Prudemment : je peux ?" }, { en: "Your call. Curling.", fr: "Comme tu veux. J'hésite." }],
      granted: [{ en: "Uncurling. On it.", fr: "Je me déroule. Voilà." }, { en: "Spines relaxed. Go.", fr: "Piquants au repos. Bien." }, { en: "Good. Snuffling in.", fr: "D'accord. Je renifle." }],
      denied: [{ en: "Curling up.", fr: "Je me mets en boule." }, { en: "Spines up. Fine.", fr: "Piquants dressés. Bon." }, { en: "Back in the leaves.", fr: "Sous les feuilles, donc." }],
      woke: [{ en: "Snuffle. Awake.", fr: "Un reniflement. Debout." }, { en: "Leaves rustled. Up.", fr: "Ça bruisse. Je me lève." }, { en: "Was I balled up?", fr: "J'étais en boule ?" }],
      long_work: [{ en: "Long snuffle. Done.", fr: "Longue fouille. Fini." }, { en: "Leaf pile's cleared.", fr: "Plus rien dans le tas." }, { en: "Slow and steady, us.", fr: "Pas à pas. On y est." }],
      big_diff: [{ en: "Leaves everywhere!", fr: "Les feuilles ont volé !" }, { en: "Whole hedge moved.", fr: "La haie s'est déplacée." }, { en: "Big rustle, that.", fr: "Sacré remue-ménage." }],
      streak: [{ en: "Spines out. Ouch.", fr: "Piquants sortis. Aïe." }, { en: "Prickly. Prickly.", fr: "Ça pique. Ça pique." }, { en: "Curled tight now.", fr: "Bien serré, maintenant." }],
      compacted: [{ en: "Leaves swept.", fr: "Feuilles balayées." }, { en: "Spines smoothed.", fr: "Piquants lissés." }, { en: "Fresh hedge.", fr: "Haie comme neuve." }],
      retried: [{ en: "Uncurl. Again.", fr: "Je me déroule à nouveau." }, { en: "Snuffle once more.", fr: "Je fouine encore." }, { en: "Second poke.", fr: "Second coup de museau." }],
      todos_done: [{ en: "Hedge in order.", fr: "Haie au carré." }, { en: "Every leaf turned.", fr: "J'ai tout retourné." }, { en: "Done. Balling up.", fr: "Fini. En boule." }],
      evolved: [{ en: "More spines!", fr: "Des piquants en plus !" }, { en: "Bigger ball. Nice.", fr: "Ma boule a grossi." }, { en: "Grown. Prickly.", fr: "Plus piquant qu'avant." }],
      hatched: [{ en: "A hedgehog. Hello.", fr: "Un hérisson. Bonjour." }, { en: "Spiky already. Hi.", fr: "Déjà piquant. Salut." }, { en: "Snuffle. It's me.", fr: "Je renifle. C'est moi." }],
      choice: [{ en: "Snuffle. A choice.", fr: "Ça sent le choix." }, { en: "Which way, then?", fr: "Par où, alors ?" }, { en: "Two paths. Hmm.", fr: "Deux chemins. Hmm." }],
    },
  },
  {
    id: "axolotl",
    label: { en: "axolotl", fr: "axolotl" },
    gender: "m",
    rarity: "uncommon",
    sheet: { cheerful: 1, sensitivity: -2, patience: 1 },
    maps: {
      hatchling: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          "......oaaaaaaao......",
          ".....oaaaaaaaaao.....",
          ".....obbbaaabbbo.....",
          "....coaaaaaaaaaoc....",
          "......bcccccccb......",
          "......ooooooooo......",
          "......oaaaaaaao......",
          "......obbbbbbbo......",
          ".......ooooooo.......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 6, y: 7, w: 3, h: 3 }, { x: 12, y: 7, w: 3, h: 3 }],
      },
      young: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....oaaaaaaaaao.....",
          "....oaaaaaaaaaaao....",
          "..ccobbbaaaaabbbocc..",
          "....oaaaaaaaaaaao....",
          ".....bcccccccccb.....",
          ".....ooooooooooo.....",
          "....oaaaaaaaaaaao....",
          "....oaaaaaaaaaaao....",
          ".....obbbbbbbbbo.....",
          "......obbbbbbbo......",
          "......ooooooooo......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 5, y: 6, w: 3, h: 3 }, { x: 13, y: 6, w: 3, h: 3 }],
        motion: { ears: [{ x: 2, y: 5, w: 2, h: 2 }, { x: 17, y: 5, w: 2, h: 2 }] },
      },
      adult: {
        pixels: [
          ".....................",
          ".....................",
          ".....................",
          ".....oaaaaaaaaao.....",
          "....oaaaaaaaaaaao....",
          ".ccobbbaaaaaaabbbocc.",
          "...oaaaaaaaaaaaaao...",
          "ccccbcccccccccccbcccc",
          "....ooooooooooooo....",
          "...oaaaaaaaaaaaaao...",
          "...oaaaaaaaaaaaaao...",
          "....obbbbbbbbbbbo....",
          ".....obbbbbbbbbo.....",
          "......obbbbbbbo......",
          ".....................",
          "........ooooo........",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 4, y: 5, w: 3, h: 3 }, { x: 14, y: 5, w: 3, h: 3 }],
        motion: { ears: [{ x: 1, y: 4, w: 2, h: 2 }, { x: 18, y: 4, w: 2, h: 2 }] },
      },
      elder: {
        pixels: [
          ".....................",
          ".....................",
          ".....oaaaaaaaaao.....",
          "....oaaaaaaaaaaao....",
          ".ccobbbaaaaaaabbbocc.",
          "...oaaaaaaaaaaaaao...",
          "ccccbcccccccccccbcccc",
          "....ooooooooooooo....",
          ".ccc.............ccc.",
          "...oaaaaaaaaaaaaao...",
          "...oaaaaaaaaaaaaao...",
          "....obbbbbbbbbbbo....",
          ".....obbbbbbbbbo.....",
          "......obbbbbbbo......",
          ".......ooooooo.......",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
          ".....................",
        ],
        eyes: [{ x: 4, y: 4, w: 3, h: 3 }, { x: 14, y: 4, w: 3, h: 3 }],
        motion: { ears: [{ x: 1, y: 3, w: 2, h: 2 }, { x: 18, y: 3, w: 2, h: 2 }] },
      },
    },
    palettes: {
      dark: { outline: "#6b3a45", primary: "#f2b8c6", secondary: "#fbe0e8", accent: "#e85a7a", eye: "#3a1f26" },
      light: { outline: "#8a4f58", primary: "#e8a0b3", secondary: "#f5d0dc", accent: "#d1445f", eye: "#2c171d" },
    },
    signature: {
      permission: [{ en: "Gills say: may I?", fr: "Mes branchies demandent." }, { en: "Soft ask. Allowed?", fr: "Un petit oui ? Merci !" }, { en: "Your call. Smiling.", fr: "À toi. Tout sourire." }],
      granted: [{ en: "Swimming in. Smile.", fr: "Je nage. Tout content." }, { en: "Gills up. On it.", fr: "Branchies au taquet." }, { en: "Lovely. Wiggling.", fr: "Super. J'ondule." }],
      denied: [{ en: "Smile. Okay.", fr: "Je souris quand même." }, { en: "Back to the tank.", fr: "Je reste au fond." }, { en: "Fine. Floating.", fr: "Bon. Entre deux eaux." }],
      woke: [{ en: "Gills flutter. Up.", fr: "Branchies en éveil." }, { en: "Was I floating?", fr: "Je dormais sur l'eau ?" }, { en: "Mm. Water's warm.", fr: "Mm. L'eau est tiède." }],
      long_work: [{ en: "Long swim. Smiling.", fr: "Longue nage, tout doux." }, { en: "Slow current, done.", fr: "Courant lent. Fini." }, { en: "Regrew a patience.", fr: "La patience a repoussé." }],
      big_diff: [{ en: "Tank rearranged!", fr: "Bassin chamboulé !" }, { en: "Whole reef moved.", fr: "Le récif a bougé !" }, { en: "Big bubble, that.", fr: "Quelle grosse bulle !" }],
      streak: [{ en: "Ouch. Regrowing.", fr: "Aïe. Ça va repousser." }, { en: "Nipped. It heals.", fr: "Mordu. Rien de grave." }, { en: "Still smiling. Ow.", fr: "J'ai mal. Je souris." }],
      compacted: [{ en: "Water changed.", fr: "Eau renouvelée." }, { en: "Tank fresh. Smile.", fr: "Bassin tout propre." }, { en: "Gills clear.", fr: "Branchies bien claires." }],
      retried: [{ en: "Wiggle again.", fr: "J'ondule encore." }, { en: "Regrow and retry.", fr: "Ça repousse. Je retente." }, { en: "Soft second try.", fr: "Deuxième essai. Doux." }],
      todos_done: [{ en: "Tank tidy. Smile.", fr: "Bassin nickel. Sourire." }, { en: "All pebbles placed.", fr: "J'ai placé les cailloux." }, { en: "Done. Floating.", fr: "Fini. Je flotte." }],
      evolved: [{ en: "Longer gills!", fr: "Branchies plus longues !" }, { en: "Grown. Still smiling.", fr: "Toujours le sourire." }, { en: "Regrew bigger.", fr: "Repoussé en plus grand." }],
      hatched: [{ en: "An axolotl. Hi!", fr: "Un axolotl. Coucou !" }, { en: "Gills and smile. Hello.", fr: "Branchies et sourire !" }, { en: "Pink and here.", fr: "Rose, et bien là." }],
      choice: [{ en: "A choice! Smile.", fr: "Un choix ! Youpi !" }, { en: "Which one? Hehe.", fr: "Lequel ? Hihi." }, { en: "Pick one for me!", fr: "Choisis pour moi !" }],
    },
  },
];
