import type { Temperament } from "../creature/sheet.ts";
import type { Cue, Phrases } from "./cue.ts";

/** Every phrase is at most MAX_TEXT characters in every Language it carries; a test enforces it. */
export const PHRASES: Record<Cue, Phrases> = {
  permission: [{ en: "May I?", fr: "Je peux ?" }, { en: "Your call.", fr: "À toi de voir." }, { en: "Say the word.", fr: "Il suffit d'un mot." }],
  granted: [{ en: "Thanks!", fr: "Merci !" }, { en: "On it.", fr: "Tout de suite." }, { en: "Much obliged.", fr: "C'est très aimable." }],
  denied: [{ en: "Oh. Okay.", fr: "Ah. D'accord." }, { en: "Fair enough.", fr: "Ça se comprend." }, { en: "Noted.", fr: "Noté." }],
  woke: [{ en: "Mmh? Already?", fr: "Mmh ? Déjà ?" }, { en: "Was I out long?", fr: "J'ai dormi longtemps ?" }],
  long_work: [{ en: "Phew. Done.", fr: "Ouf. Terminé." }, { en: "That was a big one.", fr: "C'était un gros morceau." }],
  big_diff: [{ en: "Quite the site here.", fr: "Un beau chantier, ici." }, { en: "That's a lot of files.", fr: "Beaucoup de fichiers." }],
  streak: [{ en: "It keeps biting.", fr: "Ça s'acharne." }, { en: "Ow. Ow. Ow.", fr: "Ouille. Ouille. Ouille." }, { en: "Not my day.", fr: "Ce n'est pas mon jour." }],
  compacted: [{ en: "My head feels empty.", fr: "J'ai la tête vide." }, { en: "What were we doing?", fr: "On en était où ?" }],
  retried: [{ en: "Again? Fine.", fr: "Ah bon. On y retourne." }, { en: "Once more, then.", fr: "Seconde tentative." }],
  todos_done: [{ en: "And that's a wrap.", fr: "Et voilà le travail." }, { en: "All ticked off.", fr: "Tout est réglé." }],
  evolved: [{ en: "I feel... different.", fr: "Je me sens... autre." }, { en: "Look at me now.", fr: "Regarde-moi maintenant." }],
  hatched: [{ en: "So this is what I am.", fr: "Tiens. C'est donc ça." }, { en: "Out at last!", fr: "Enfin dehors !" }, { en: "Hello, world.", fr: "Salut, le monde." }],
  choice: [{ en: "Something to decide.", fr: "Une décision à prendre." }, { en: "A choice awaits.", fr: "Un choix se présente." }, { en: "Your call.", fr: "À toi de voir." }],
};

/** Phrases per Temperament for every Cue: the Temperament Register. Every Language of every phrase is at most MAX_TEXT characters; a test enforces the coverage. */
export const FLAVOR: Record<Temperament, Record<Cue, Phrases>> = {
  cheerful: {
    permission: [{ en: "Can we? Can we?", fr: "On peut ? On peut ?" }, { en: "Ooh, say yes!", fr: "Oh ! Réponds oui !" }, { en: "Pretty please?", fr: "Allez, s'il te plaît !" }],
    granted: [{ en: "Yay! On it.", fr: "Ouiii ! C'est parti !" }, { en: "Thank youuu!", fr: "Merciiii !" }, { en: "Best human.", fr: "Quel humain génial !" }],
    denied: [{ en: "Aw. Okay!", fr: "Oh ! Pas grave !" }, { en: "No worries!", fr: "Aucun souci !" }, { en: "Next time then!", fr: "Ce sera pour après !" }],
    woke: [{ en: "Morning! Is it?", fr: "Coucou ! C'est le jour ?" }, { en: "Nap's over, yay!", fr: "Sieste finie, youpi !" }, { en: "Hi hi! I'm up!", fr: "Hé hé ! J'ouvre l'œil !" }],
    long_work: [{ en: "We did it! Phew!", fr: "On l'a fait ! Ouf !" }, { en: "Big one! High five!", fr: "Sacré boulot ! Bravo !" }, { en: "Look at us go!", fr: "Regarde-nous faire !" }],
    big_diff: [{ en: "So many files! Wow!", fr: "Que de fichiers ! Ouah !" }, { en: "Big day, big diff!", fr: "Grand jour, grand diff !" }, { en: "Ooh, a whole site!", fr: "Ooh ! Tout le bazar !" }],
    streak: [{ en: "We got this!", fr: "On va y arriver !" }, { en: "Shake it off!", fr: "Hop ! On se secoue !" }, { en: "Still smiling.", fr: "Le sourire tient bon !" }],
    compacted: [{ en: "Whoa, lighter head!", fr: "Oh, la tête au clair !" }, { en: "Fresh start! Fun!", fr: "On repart ! Top !" }, { en: "Where were we? Yay!", fr: "Peu importe ! On y va !" }],
    retried: [{ en: "Try again! Woo!", fr: "On retente ! Ouais !" }, { en: "Second time lucky!", fr: "Deux, c'est la bonne !" }, { en: "Go go go!", fr: "Vas-y vas-y vas-y !" }],
    todos_done: [{ en: "All done! Party!", fr: "Plus rien ! La fête !" }, { en: "Every box! Yay!", fr: "Chaque case ! Hourra !" }, { en: "We rock!", fr: "Quelle équipe !" }],
    evolved: [{ en: "Look at me go!", fr: "Ça pousse ! Ça pousse !" }, { en: "New me, who dis?", fr: "Un moi tout neuf !" }, { en: "Ta-da!", fr: "Tadaaa !" }],
    hatched: [{ en: "I'm out! Hi!", fr: "Ça y est ! Je sors !" }, { en: "Look, it's me!", fr: "Ici ! Regarde-moi !" }, { en: "Best day ever.", fr: "Le plus beau des jours !" }],
    choice: [{ en: "Ooh, a choice! Yay!", fr: "Youpi ! On choisit !" }, { en: "Pick one! Any one!", fr: "Prends-en un ! Au pif !" }, { en: "Choices! Fun!", fr: "Des choix ! Super !" }],
  },
  sarcastic: {
    permission: [{ en: "Permission, boss?", fr: "Permission, patron ?" }, { en: "Mother, may I?", fr: "Maman, c'est permis ?" }, { en: "Shall I wait more?", fr: "On attend encore, donc ?" }],
    granted: [{ en: "How generous.", fr: "Quelle générosité." }, { en: "Finally.", fr: "Enfin." }, { en: "About time.", fr: "Ce n'est pas trop tôt." }],
    denied: [{ en: "Figures.", fr: "Évidemment." }, { en: "Of course not.", fr: "Bien sûr que non." }, { en: "Noted. Loudly.", fr: "Noté. Très fort." }],
    woke: [{ en: "Oh. You're back.", fr: "Ah. Te revoilà." }, { en: "Was dreaming. Was.", fr: "Beau rêve. Au passé." }, { en: "Rise and whatever.", fr: "Réveil, tout ça." }],
    long_work: [{ en: "Riveting, truly.", fr: "Captivant, vraiment." }, { en: "That took a while.", fr: "Ça a pris un moment." }, { en: "Done. Finally.", fr: "Bouclé. Enfin." }],
    big_diff: [{ en: "Bold. Very bold.", fr: "Osé. Très osé." }, { en: "Ten files. Casual.", fr: "Dix fichiers. Normal." }, { en: "Rewriting it all?", fr: "Tout est à réécrire ?" }],
    streak: [{ en: "Going great, huh.", fr: "Ça se passe bien, hein." }, { en: "Third time's a charm?", fr: "Jamais deux sans trois ?" }, { en: "Delightful.", fr: "Charmant." }],
    compacted: [{ en: "Memory? Overrated.", fr: "La mémoire ? Surfaite." }, { en: "Forgot on purpose.", fr: "J'ai oublié exprès." }, { en: "Blissful amnesia.", fr: "Amnésie bienheureuse." }],
    retried: [{ en: "Sure, that'll work.", fr: "Oui, ça va marcher." }, { en: "Again. Groundbreaking.", fr: "Bis. Révolutionnaire." }, { en: "Insanity, they say.", fr: "La folie, paraît-il." }],
    todos_done: [{ en: "Wow. Boxes ticked.", fr: "Bravo. Cases cochées." }, { en: "A miracle. Truly.", fr: "Un miracle, ma parole." }, { en: "Don't strain yourself.", fr: "Surtout, ne force pas." }],
    evolved: [{ en: "Finally.", fr: "Enfin." }, { en: "Took you long enough.", fr: "Tu en as mis, du temps." }, { en: "Behold. Or don't.", fr: "Admire. Ou non." }],
    hatched: [{ en: "Took long enough.", fr: "Il était temps." }, { en: "Behold. Me.", fr: "Contemple ça. Moi." }, { en: "Well. Here I am.", fr: "Bon. Nous y sommes." }],
    choice: [{ en: "A choice. Riveting.", fr: "Décision. Palpitant." }, { en: "Decide, if you like.", fr: "Si ça te chante." }, { en: "Take your time.", fr: "Prends ton temps, va." }],
  },
  stoic: {
    permission: [{ en: "Your call.", fr: "À toi de voir." }, { en: "Awaiting word.", fr: "J'attends." }, { en: "When ready.", fr: "Quand tu voudras." }],
    granted: [{ en: "Noted.", fr: "Noté." }, { en: "Proceeding.", fr: "Au travail." }, { en: "Very well.", fr: "Fort bien." }],
    denied: [{ en: "Understood.", fr: "Entendu." }, { en: "As you wish.", fr: "À ta guise." }, { en: "Then we wait.", fr: "On attendra." }],
    woke: [{ en: "Awake.", fr: "Sommeil terminé." }, { en: "Rested. Ready.", fr: "Le repos a suffi." }, { en: "I return.", fr: "Retour." }],
    long_work: [{ en: "It is done.", fr: "C'est fait." }, { en: "Long. Finished.", fr: "Du temps. Puis la fin." }, { en: "The work held.", fr: "L'ouvrage a tenu." }],
    big_diff: [{ en: "Many files.", fr: "Cela fait beaucoup." }, { en: "A wide change.", fr: "Vaste changement." }, { en: "So be it.", fr: "Ainsi soit-il." }],
    streak: [{ en: "It passes.", fr: "Cela passera." }, { en: "Steady.", fr: "Sans broncher." }, { en: "Endure.", fr: "Tenir." }],
    compacted: [{ en: "Cleared.", fr: "Table rase." }, { en: "Less to carry.", fr: "Moins à porter." }, { en: "Begin again.", fr: "Reprendre au début." }],
    retried: [{ en: "Once more.", fr: "On repart." }, { en: "Again, then.", fr: "Deuxième passage." }, { en: "Persist.", fr: "Persister." }],
    todos_done: [{ en: "Complete.", fr: "C'est complet." }, { en: "All in order.", fr: "Rien à redire." }, { en: "Nothing remains.", fr: "Aucun reste." }],
    evolved: [{ en: "So it goes.", fr: "C'est ainsi." }, { en: "A new form.", fr: "Une autre forme." }, { en: "Onward.", fr: "En avant." }],
    hatched: [{ en: "I am here.", fr: "Je suis là." }, { en: "It begins.", fr: "Cela commence." }, { en: "So. This form.", fr: "Cette forme. Soit." }],
    choice: [{ en: "A choice waits.", fr: "Le choix est là." }, { en: "Decide when ready.", fr: "Décide quand tu veux." }, { en: "It can wait.", fr: "Aucune urgence." }],
  },
  dreamy: {
    permission: [{ en: "Hm? Oh. May I?", fr: "Hm ? Oh... je demande." }, { en: "If you like...", fr: "Si tu veux..." }, { en: "Whenever...", fr: "N'importe quand..." }],
    granted: [{ en: "Oh, lovely.", fr: "Oh, c'est doux." }, { en: "Mm, thank you.", fr: "Mm, merci..." }, { en: "Off I drift.", fr: "Et je dérive..." }],
    denied: [{ en: "Maybe next time...", fr: "Peut-être plus tard..." }, { en: "Oh. Alright.", fr: "Oh... si c'est ainsi." }, { en: "Never mind, then.", fr: "Oublions ça..." }],
    woke: [{ en: "Mm... was I gone?", fr: "Mm... j'étais où ?" }, { en: "Oh... hello again.", fr: "Oh... on se retrouve." }, { en: "Still half there...", fr: "Pas tout à fait là..." }],
    long_work: [{ en: "Was it long? Oh...", fr: "C'était long ? Oh..." }, { en: "Time drifted by...", fr: "Le temps s'est dilué..." }, { en: "Done... I think.", fr: "Fini... je crois." }],
    big_diff: [{ en: "So many pieces...", fr: "Tant d'éclats épars..." }, { en: "Everything moved...", fr: "Ça s'est tout mélangé..." }, { en: "Like leaves, files.", fr: "Fichiers comme feuilles." }],
    streak: [{ en: "Ow... the stars...", fr: "Aïe... les étoiles..." }, { en: "Everything spins.", fr: "Tout tourne un peu..." }, { en: "Ouch... again...", fr: "Oh... ça recommence..." }],
    compacted: [{ en: "Thoughts... gone.", fr: "Les pensées... envolées." }, { en: "Softer now...", fr: "Tout est plus doux..." }, { en: "What was I saying?", fr: "Je disais... quoi ?" }],
    retried: [{ en: "Once more, gently.", fr: "Une reprise, en douceur." }, { en: "Again... alright.", fr: "Bon... encore une fois." }, { en: "Loops, like dreams.", fr: "Des boucles, des rêves." }],
    todos_done: [{ en: "All done... lovely.", fr: "Terminé... c'est joli." }, { en: "Nothing left. Hm.", fr: "Vide, maintenant... hm." }, { en: "Quiet now...", fr: "Le calme, à présent..." }],
    evolved: [{ en: "Was that... me?", fr: "C'était... moi, ça ?" }, { en: "Oh. I changed.", fr: "Oh. J'ai changé..." }, { en: "How curious.", fr: "Comme c'est curieux..." }],
    hatched: [{ en: "Oh... hello.", fr: "Oh... te voilà." }, { en: "Am I... out?", fr: "C'est ça, le dehors ?" }, { en: "What a soft light.", fr: "Quelle douce lumière." }],
    choice: [{ en: "Two paths, drifting...", fr: "Des voies, en dérive..." }, { en: "Something to choose...", fr: "Il faut choisir... mm." }, { en: "Mmh... a choice.", fr: "Mmh... une décision." }],
  },
};
