import type { Temperament } from "../creature/sheet.ts";
import type { Cue, Phrases } from "./cue.ts";

/** Every phrase is at most MAX_TEXT characters in every Language it carries; a test enforces it. */
export const PHRASES: Record<Cue, Phrases> = {
  permission: [{ en: "May I?" }, { en: "Your call." }, { en: "Say the word." }],
  granted: [{ en: "Thanks!" }, { en: "On it." }, { en: "Much obliged." }],
  denied: [{ en: "Oh. Okay." }, { en: "Fair enough." }, { en: "Noted." }],
  woke: [{ en: "Mmh? Already?" }, { en: "Was I out long?" }],
  long_work: [{ en: "Phew. Done." }, { en: "That was a big one." }],
  big_diff: [{ en: "Quite the site here." }, { en: "That's a lot of files." }],
  streak: [{ en: "It keeps biting." }, { en: "Ow. Ow. Ow." }, { en: "Not my day." }],
  compacted: [{ en: "My head feels empty." }, { en: "What were we doing?" }],
  retried: [{ en: "Again? Fine." }, { en: "Once more, then." }],
  todos_done: [{ en: "And that's a wrap." }, { en: "All ticked off." }],
  evolved: [{ en: "I feel... different." }, { en: "Look at me now." }],
  hatched: [{ en: "So this is what I am." }, { en: "Out at last!" }, { en: "Hello, world." }],
  choice: [{ en: "Something to decide." }, { en: "A choice awaits." }, { en: "Your call." }],
};

/** Phrases per Temperament for every Cue: the Temperament Register. Every Language of every phrase is at most MAX_TEXT characters; a test enforces the coverage. */
export const FLAVOR: Record<Temperament, Record<Cue, Phrases>> = {
  cheerful: {
    permission: [{ en: "Can we? Can we?" }, { en: "Ooh, say yes!" }, { en: "Pretty please?" }],
    granted: [{ en: "Yay! On it." }, { en: "Thank youuu!" }, { en: "Best human." }],
    denied: [{ en: "Aw. Okay!" }, { en: "No worries!" }, { en: "Next time then!" }],
    woke: [{ en: "Morning! Is it?" }, { en: "Nap's over, yay!" }, { en: "Hi hi! I'm up!" }],
    long_work: [{ en: "We did it! Phew!" }, { en: "Big one! High five!" }, { en: "Look at us go!" }],
    big_diff: [{ en: "So many files! Wow!" }, { en: "Big day, big diff!" }, { en: "Ooh, a whole site!" }],
    streak: [{ en: "We got this!" }, { en: "Shake it off!" }, { en: "Still smiling." }],
    compacted: [{ en: "Whoa, lighter head!" }, { en: "Fresh start! Fun!" }, { en: "Where were we? Yay!" }],
    retried: [{ en: "Try again! Woo!" }, { en: "Second time lucky!" }, { en: "Go go go!" }],
    todos_done: [{ en: "All done! Party!" }, { en: "Every box! Yay!" }, { en: "We rock!" }],
    evolved: [{ en: "Look at me go!" }, { en: "New me, who dis?" }, { en: "Ta-da!" }],
    hatched: [{ en: "I'm out! Hi!" }, { en: "Look, it's me!" }, { en: "Best day ever." }],
    choice: [{ en: "Ooh, a choice! Yay!" }, { en: "Pick one! Any one!" }, { en: "Choices! Fun!" }],
  },
  sarcastic: {
    permission: [{ en: "Permission, boss?" }, { en: "Mother, may I?" }, { en: "Shall I wait more?" }],
    granted: [{ en: "How generous." }, { en: "Finally." }, { en: "About time." }],
    denied: [{ en: "Figures." }, { en: "Of course not." }, { en: "Noted. Loudly." }],
    woke: [{ en: "Oh. You're back." }, { en: "Was dreaming. Was." }, { en: "Rise and whatever." }],
    long_work: [{ en: "Riveting, truly." }, { en: "That took a while." }, { en: "Done. Finally." }],
    big_diff: [{ en: "Bold. Very bold." }, { en: "Ten files. Casual." }, { en: "Rewriting it all?" }],
    streak: [{ en: "Going great, huh." }, { en: "Third time's a charm?" }, { en: "Delightful." }],
    compacted: [{ en: "Memory? Overrated." }, { en: "Forgot on purpose." }, { en: "Blissful amnesia." }],
    retried: [{ en: "Sure, that'll work." }, { en: "Again. Groundbreaking." }, { en: "Insanity, they say." }],
    todos_done: [{ en: "Wow. Boxes ticked." }, { en: "A miracle. Truly." }, { en: "Don't strain yourself." }],
    evolved: [{ en: "Finally." }, { en: "Took you long enough." }, { en: "Behold. Or don't." }],
    hatched: [{ en: "Took long enough." }, { en: "Behold. Me." }, { en: "Well. Here I am." }],
    choice: [{ en: "A choice. Riveting." }, { en: "Decide, if you like." }, { en: "Take your time." }],
  },
  stoic: {
    permission: [{ en: "Your call." }, { en: "Awaiting word." }, { en: "When ready." }],
    granted: [{ en: "Noted." }, { en: "Proceeding." }, { en: "Very well." }],
    denied: [{ en: "Understood." }, { en: "As you wish." }, { en: "Then we wait." }],
    woke: [{ en: "Awake." }, { en: "Rested. Ready." }, { en: "I return." }],
    long_work: [{ en: "It is done." }, { en: "Long. Finished." }, { en: "The work held." }],
    big_diff: [{ en: "Many files." }, { en: "A wide change." }, { en: "So be it." }],
    streak: [{ en: "It passes." }, { en: "Steady." }, { en: "Endure." }],
    compacted: [{ en: "Cleared." }, { en: "Less to carry." }, { en: "Begin again." }],
    retried: [{ en: "Once more." }, { en: "Again, then." }, { en: "Persist." }],
    todos_done: [{ en: "Complete." }, { en: "All in order." }, { en: "Nothing remains." }],
    evolved: [{ en: "So it goes." }, { en: "A new form." }, { en: "Onward." }],
    hatched: [{ en: "I am here." }, { en: "It begins." }, { en: "So. This form." }],
    choice: [{ en: "A choice waits." }, { en: "Decide when ready." }, { en: "It can wait." }],
  },
  dreamy: {
    permission: [{ en: "Hm? Oh. May I?" }, { en: "If you like..." }, { en: "Whenever..." }],
    granted: [{ en: "Oh, lovely." }, { en: "Mm, thank you." }, { en: "Off I drift." }],
    denied: [{ en: "Maybe next time..." }, { en: "Oh. Alright." }, { en: "Never mind, then." }],
    woke: [{ en: "Mm... was I gone?" }, { en: "Oh... hello again." }, { en: "Still half there..." }],
    long_work: [{ en: "Was it long? Oh..." }, { en: "Time drifted by..." }, { en: "Done... I think." }],
    big_diff: [{ en: "So many pieces..." }, { en: "Everything moved..." }, { en: "Like leaves, files." }],
    streak: [{ en: "Ow... the stars..." }, { en: "Everything spins." }, { en: "Ouch... again..." }],
    compacted: [{ en: "Thoughts... gone." }, { en: "Softer now..." }, { en: "What was I saying?" }],
    retried: [{ en: "Once more, gently." }, { en: "Again... alright." }, { en: "Loops, like dreams." }],
    todos_done: [{ en: "All done... lovely." }, { en: "Nothing left. Hm." }, { en: "Quiet now..." }],
    evolved: [{ en: "Was that... me?" }, { en: "Oh. I changed." }, { en: "How curious." }],
    hatched: [{ en: "Oh... hello." }, { en: "Am I... out?" }, { en: "What a soft light." }],
    choice: [{ en: "Two paths, drifting..." }, { en: "Something to choose..." }, { en: "Mmh... a choice." }],
  },
};
