import type { Temperament } from "../creature/sheet.ts";
import type { Cue, Phrases } from "./cue.ts";

/** English, like the Moods. Every phrase is at most MAX_TEXT characters; a test enforces it. */
export const PHRASES: Record<Cue, Phrases> = {
  permission: ["May I?", "Your call.", "Say the word."],
  granted: ["Thanks!", "On it.", "Much obliged."],
  denied: ["Oh. Okay.", "Fair enough.", "Noted."],
  woke: ["Mmh? Already?", "Was I out long?"],
  long_work: ["Phew. Done.", "That was a big one."],
  big_diff: ["Quite the site here.", "That's a lot of files."],
  streak: ["It keeps biting.", "Ow. Ow. Ow.", "Not my day."],
  compacted: ["My head feels empty.", "What were we doing?"],
  retried: ["Again? Fine.", "Once more, then."],
  todos_done: ["And that's a wrap.", "All ticked off."],
  evolved: ["I feel... different.", "Look at me now."],
  hatched: ["So this is what I am.", "Out at last!", "Hello, world."],
};

/** Phrases per Temperament for every Cue: the Temperament Register. English, at most MAX_TEXT characters each; a test enforces the coverage. */
export const FLAVOR: Record<Temperament, Record<Cue, Phrases>> = {
  cheerful: {
    permission: ["Can we? Can we?", "Ooh, say yes!", "Pretty please?"],
    granted: ["Yay! On it.", "Thank youuu!", "Best human."],
    denied: ["Aw. Okay!", "No worries!", "Next time then!"],
    woke: ["Morning! Is it?", "Nap's over, yay!", "Hi hi! I'm up!"],
    long_work: ["We did it! Phew!", "Big one! High five!", "Look at us go!"],
    big_diff: ["So many files! Wow!", "Big day, big diff!", "Ooh, a whole site!"],
    streak: ["We got this!", "Shake it off!", "Still smiling."],
    compacted: ["Whoa, lighter head!", "Fresh start! Fun!", "Where were we? Yay!"],
    retried: ["Try again! Woo!", "Second time lucky!", "Go go go!"],
    todos_done: ["All done! Party!", "Every box! Yay!", "We rock!"],
    evolved: ["Look at me go!", "New me, who dis?", "Ta-da!"],
    hatched: ["I'm out! Hi!", "Look, it's me!", "Best day ever."],
  },
  sarcastic: {
    permission: ["Permission, boss?", "Mother, may I?", "Shall I wait more?"],
    granted: ["How generous.", "Finally.", "About time."],
    denied: ["Figures.", "Of course not.", "Noted. Loudly."],
    woke: ["Oh. You're back.", "Was dreaming. Was.", "Rise and whatever."],
    long_work: ["Riveting, truly.", "That took a while.", "Done. Finally."],
    big_diff: ["Bold. Very bold.", "Ten files. Casual.", "Rewriting it all?"],
    streak: ["Going great, huh.", "Third time's a charm?", "Delightful."],
    compacted: ["Memory? Overrated.", "Forgot on purpose.", "Blissful amnesia."],
    retried: ["Sure, that'll work.", "Again. Groundbreaking.", "Insanity, they say."],
    todos_done: ["Wow. Boxes ticked.", "A miracle. Truly.", "Don't strain yourself."],
    evolved: ["Finally.", "Took you long enough.", "Behold. Or don't."],
    hatched: ["Took long enough.", "Behold. Me.", "Well. Here I am."],
  },
  stoic: {
    permission: ["Your call.", "Awaiting word.", "When ready."],
    granted: ["Noted.", "Proceeding.", "Very well."],
    denied: ["Understood.", "As you wish.", "Then we wait."],
    woke: ["Awake.", "Rested. Ready.", "I return."],
    long_work: ["It is done.", "Long. Finished.", "The work held."],
    big_diff: ["Many files.", "A wide change.", "So be it."],
    streak: ["It passes.", "Steady.", "Endure."],
    compacted: ["Cleared.", "Less to carry.", "Begin again."],
    retried: ["Once more.", "Again, then.", "Persist."],
    todos_done: ["Complete.", "All in order.", "Nothing remains."],
    evolved: ["So it goes.", "A new form.", "Onward."],
    hatched: ["I am here.", "It begins.", "So. This form."],
  },
  dreamy: {
    permission: ["Hm? Oh. May I?", "If you like...", "Whenever..."],
    granted: ["Oh, lovely.", "Mm, thank you.", "Off I drift."],
    denied: ["Maybe next time...", "Oh. Alright.", "Never mind, then."],
    woke: ["Mm... was I gone?", "Oh... hello again.", "Still half there..."],
    long_work: ["Was it long? Oh...", "Time drifted by...", "Done... I think."],
    big_diff: ["So many pieces...", "Everything moved...", "Like leaves, files."],
    streak: ["Ow... the stars...", "Everything spins.", "Ouch... again..."],
    compacted: ["Thoughts... gone.", "Softer now...", "What was I saying?"],
    retried: ["Once more, gently.", "Again... alright.", "Loops, like dreams."],
    todos_done: ["All done... lovely.", "Nothing left. Hm.", "Quiet now..."],
    evolved: ["Was that... me?", "Oh. I changed.", "How curious."],
    hatched: ["Oh... hello.", "Am I... out?", "What a soft light."],
  },
};
