import type { Signature } from "../signature.ts";
import type { SpeciesId } from "../species.ts";

/** The rare Species: creatures past the ordinary living. */
export const RARE: Record<SpeciesId, Signature> = {
  robot: {
    permission: ["Access requested.", "Awaiting input.", "Query: proceed?"],
    granted: ["Access granted.", "Executing.", "Input received. Go."],
    denied: ["Access denied.", "Halting.", "Input: no. Standby."],
    woke: ["Rebooted.", "Standby ended.", "Systems online."],
    long_work: ["Task complete.", "Uptime: long.", "Process finished."],
    big_diff: ["Many files changed.", "Large delta logged.", "Bulk write detected."],
    streak: ["Error. Error. Error.", "Fault tolerance: ok.", "Retry counter high."],
    compacted: ["Memory freed.", "Cache cleared.", "Garbage collected."],
    retried: ["Retrying.", "Attempt: next.", "Loop continues."],
    todos_done: ["Queue empty.", "All tasks closed.", "Checklist: done."],
    evolved: ["Firmware updated.", "New chassis.", "Version bumped."],
    hatched: ["Boot complete.", "Unit online.", "Hello, operator."],
  },
  ghost: {
    permission: ["Boo... may I?", "A whisper: allowed?", "Drift in? You say."],
    granted: ["Drifting through.", "Boo. On it.", "Passing in..."],
    denied: ["Fading back...", "Boo. Okay.", "Haunting elsewhere."],
    woke: ["Did I... return?", "Midnight? Already?", "Faded back in."],
    long_work: ["Haunted all night.", "Long drift. Done.", "The hours passed us."],
    big_diff: ["Whole house rattled.", "Every door moved.", "Big haunting, that."],
    streak: ["Chains. Chains. Ow.", "Walked into a wall.", "Faded at the worst."],
    compacted: ["Memories... gone.", "Lighter than air.", "What was I haunting?"],
    retried: ["Drift again...", "Boo. Once more.", "Fade in. Retry."],
    todos_done: ["House at rest.", "Every room quiet.", "Done. Fading."],
    evolved: ["Paler. Grander.", "More boo in me.", "Grown... somehow."],
    hatched: ["Boo. A ghost.", "Was I... born?", "Hello from beyond."],
  },
  jellyfish: {
    permission: ["Drift in? May I?", "Current says ask.", "Float ahead?"],
    granted: ["Drifting in...", "Pulsing forward.", "Glow on. Go."],
    denied: ["Drifting back...", "Current says no.", "Floating still."],
    woke: ["Tide turned? Up.", "Was I drifting?", "Glow... returning."],
    long_work: ["Long drift. Done.", "Current carried us.", "Tide came in."],
    big_diff: ["Whole sea stirred.", "Every current moved.", "Big wave, that."],
    streak: ["Sting. Sting. Ow.", "Stung myself.", "Tangled tentacles."],
    compacted: ["Current cleared.", "Glow reset.", "Fresh tide."],
    retried: ["Pulse again.", "Drift once more.", "Sting, retry."],
    todos_done: ["Sea at rest.", "Every wave counted.", "Done. Glowing."],
    evolved: ["Longer tentacles.", "Brighter glow!", "Grown with the tide."],
    hatched: ["A jellyfish. Glow.", "Soft and here. Hi.", "Drifting in. Hello."],
  },
  chameleon: {
    permission: ["Blend in? May I?", "Color check: allowed?", "Your call. Watching."],
    granted: ["Blending in.", "Colors up. On it.", "Slow tongue, fast yes."],
    denied: ["Turning grey.", "Fine. Branch it is.", "Denied? Adapting."],
    woke: ["Eyes swivel. Up.", "Was I green? Now up.", "Mm. Sun's back."],
    long_work: ["Long stalk. Done.", "Patience caught it.", "Still branch, deep work."],
    big_diff: ["Every leaf recolored.", "Whole tree shifted.", "Big blend, that."],
    streak: ["Missed. Missed. Grey.", "Tongue slipped.", "Wrong color today."],
    compacted: ["Colors reset.", "Grey slate. Fresh.", "Tree swept."],
    retried: ["Aim again.", "New color, retry.", "Slow, then snap."],
    todos_done: ["Tree in order.", "Every fly caught.", "Done. Blending."],
    evolved: ["New colors!", "Longer tongue.", "Grown. Still hidden."],
    hatched: ["A chameleon. Spot me.", "Green today. Hello.", "Blending in. Hi."],
  },
};
