import type { Signature } from "../signature.ts";
import type { SpeciesId } from "../species.ts";

/** The uncommon Species: marked silhouettes, ears, wings, tentacles, spines, gills. */
export const UNCOMMON: Record<SpeciesId, Signature> = {
  fox: {
    permission: ["May I? Sly grin.", "Your henhouse, boss.", "Permission, hm?"],
    granted: ["Clever choice.", "Slipping in. Quiet.", "Foxy. On it."],
    denied: ["Denied? Cute.", "Fine. Other burrow.", "Tail flick. Noted."],
    woke: ["Ears up. What now?", "Was dreaming of hens.", "Mm. Dawn already."],
    long_work: ["Long hunt. Good one.", "Patience got the hen.", "Den's full tonight."],
    big_diff: ["Whole forest moved.", "Bold. I like bold.", "That's a big den."],
    streak: ["Trap. Trap. Trap.", "Even foxes trip.", "Not so sly today."],
    compacted: ["Den swept clean.", "Scent trail gone.", "Fresh snow. Fresh me."],
    retried: ["Sneak in again.", "Second pounce.", "Sly retry."],
    todos_done: ["Every hen counted.", "Den in order.", "Done. Tail curled."],
    evolved: ["Bushier tail.", "Sharper ears now.", "Sly and grown."],
    hatched: ["A fox. Naturally.", "Sly from the start.", "Ears up. Hello."],
  },
  penguin: {
    permission: ["Protocol: ask you.", "May I, formally?", "Awaiting clearance."],
    granted: ["Cleared. Sliding in.", "Formation, go.", "Flippers up. On it."],
    denied: ["Understood. Standing.", "Back to the huddle.", "Denied. Very well."],
    woke: ["Ice cold. Awake.", "Huddle broke up?", "Flippers stiff. Up."],
    long_work: ["Long march. Done.", "Held the egg all night.", "Cold work, warm end."],
    big_diff: ["Whole colony moved!", "Big ice shelf, that.", "Lots of flippers."],
    streak: ["Slipped. Again. Again.", "Ice is ice.", "Belly slide gone wrong."],
    compacted: ["Ice cleared.", "Fresh snow. Fresh start.", "Huddle reset."],
    retried: ["Waddle back. Again.", "Second slide.", "Once more, formal."],
    todos_done: ["Colony in order.", "All eggs counted.", "Formation complete."],
    evolved: ["Sleeker feathers.", "Taller in the huddle.", "Grown. Formally."],
    hatched: ["A penguin. Formal.", "Tuxedo on. Hello.", "Cold outside. Hi."],
  },
  octopus: {
    permission: ["Eight arms ask: may I?", "Reach in? Your call.", "Ink or go? You say."],
    granted: ["All arms in!", "Curious. Reaching.", "Eight hands on it."],
    denied: ["Ink. Fine.", "Arms folded. Okay.", "Back to my rock."],
    woke: ["Which arm was asleep?", "Hm? All eight up.", "Drifting... awake."],
    long_work: ["Eight arms, one job.", "Long reach, that one.", "Tangled, then done."],
    big_diff: ["Touched everything!", "Eight arms, ten files.", "Ink cloud of changes."],
    streak: ["Ink. Ink. Ink.", "Tangled myself.", "Suckers slipping."],
    compacted: ["Ink cleared.", "Rock swept. Fresh.", "New camouflage."],
    retried: ["Another arm, then.", "Reach again.", "Seven more tries."],
    todos_done: ["All arms free!", "Every shell opened.", "Done. Curling up."],
    evolved: ["Longer arms!", "More suckers. Nice.", "Grown. Eightfold."],
    hatched: ["An octopus. Curious.", "Eight arms. Hello!", "Ink? Later. Hi."],
  },
  bat: {
    permission: ["Whisper: may I?", "Dark says ask you.", "Hang on. Allowed?"],
    granted: ["Swooping in.", "Wings out. Quiet.", "Good. Into the dark."],
    denied: ["Hanging back.", "Cave it is.", "Fine. Upside down."],
    woke: ["Dusk already?", "Hanging... awake.", "Echo. Echo. Up."],
    long_work: ["Long night flight.", "Echoes fade. Done.", "Dawn found me working."],
    big_diff: ["Whole cave shifted.", "Echoes everywhere.", "Big flock of files."],
    streak: ["Wall. Wall. Wall.", "Echo lied. Ouch.", "Blind spot today."],
    compacted: ["Cave swept.", "Echoes cleared.", "Fresh dark."],
    retried: ["Flit back in.", "Echo, retry.", "Once more, softly."],
    todos_done: ["Cave in order.", "All echoes answered.", "Done. Hanging up."],
    evolved: ["Wider wings.", "Sharper ears.", "Grown in the dark."],
    hatched: ["A bat. Quietly.", "Wings and ears. Hi.", "Dark's fine. Hello."],
  },
  hedgehog: {
    permission: ["Spines down. May I?", "Careful ask: allowed?", "Your call. Curling."],
    granted: ["Uncurling. On it.", "Spines relaxed. Go.", "Good. Snuffling in."],
    denied: ["Curling up.", "Spines up. Fine.", "Back in the leaves."],
    woke: ["Snuffle. Awake.", "Leaves rustled. Up.", "Was I balled up?"],
    long_work: ["Long snuffle. Done.", "Leaf pile's cleared.", "Slow and steady, us."],
    big_diff: ["Leaves everywhere!", "Whole hedge moved.", "Big rustle, that."],
    streak: ["Spines out. Ouch.", "Prickly. Prickly.", "Curled tight now."],
    compacted: ["Leaves swept.", "Spines smoothed.", "Fresh hedge."],
    retried: ["Uncurl. Again.", "Snuffle once more.", "Second poke."],
    todos_done: ["Hedge in order.", "Every leaf turned.", "Done. Balling up."],
    evolved: ["More spines!", "Bigger ball. Nice.", "Grown. Prickly."],
    hatched: ["A hedgehog. Hello.", "Spiky already. Hi.", "Snuffle. It's me."],
  },
  axolotl: {
    permission: ["Gills say: may I?", "Soft ask. Allowed?", "Your call. Smiling."],
    granted: ["Swimming in. Smile.", "Gills up. On it.", "Lovely. Wiggling."],
    denied: ["Smile. Okay.", "Back to the tank.", "Fine. Floating."],
    woke: ["Gills flutter. Up.", "Was I floating?", "Mm. Water's warm."],
    long_work: ["Long swim. Smiling.", "Slow current, done.", "Regrew a patience."],
    big_diff: ["Tank rearranged!", "Whole reef moved.", "Big bubble, that."],
    streak: ["Ouch. Regrowing.", "Nipped. It heals.", "Still smiling. Ow."],
    compacted: ["Water changed.", "Tank fresh. Smile.", "Gills clear."],
    retried: ["Wiggle again.", "Regrow and retry.", "Soft second try."],
    todos_done: ["Tank tidy. Smile.", "All pebbles placed.", "Done. Floating."],
    evolved: ["Longer gills!", "Grown. Still smiling.", "Regrew bigger."],
    hatched: ["An axolotl. Hi!", "Gills and smile. Hello.", "Pink and here."],
  },
};
